/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Account,
  CreateAccountWithBodyRequest,
  DailyClaim201Response,
  DailyClaimBodyDto,
  GetBalanceDto,
  GetLeaderboardDto,
  GetProfileDto,
  KHApiErrStandard,
  UserProfile404Response,
} from '../models/index.js';
import {
    AccountFromJSON,
    AccountToJSON,
    CreateAccountWithBodyRequestFromJSON,
    CreateAccountWithBodyRequestToJSON,
    DailyClaim201ResponseFromJSON,
    DailyClaim201ResponseToJSON,
    DailyClaimBodyDtoFromJSON,
    DailyClaimBodyDtoToJSON,
    GetBalanceDtoFromJSON,
    GetBalanceDtoToJSON,
    GetLeaderboardDtoFromJSON,
    GetLeaderboardDtoToJSON,
    GetProfileDtoFromJSON,
    GetProfileDtoToJSON,
    KHApiErrStandardFromJSON,
    KHApiErrStandardToJSON,
    UserProfile404ResponseFromJSON,
    UserProfile404ResponseToJSON,
} from '../models/index.js';

export interface CreateAccountRequest {
    userid: string;
}

export interface CreateAccountWithBodyOperationRequest {
    createAccountWithBodyRequest: CreateAccountWithBodyRequest;
}

export interface DailyClaimRequest {
    userid: string;
    dailyClaimBodyDto: DailyClaimBodyDto;
}

export interface DeleteAccountRequest {
    id: string;
}

export interface GetBalanceRequest {
    userid: string;
}

export interface GetManyRequest {
    id: Array<string>;
}

export interface GetOneRequest {
    id: string;
}

export interface UpdateAccountRequest {
    id: string;
}

export interface UserProfileRequest {
    userid: string;
}

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * 
     * @summary Create Account
     * @param {string} userid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>>;

    /**
     * Create Account
     */
    createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account>;

    /**
     * 
     * @summary Create a new account
     * @param {CreateAccountWithBodyRequest} createAccountWithBodyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    createAccountWithBodyRaw(requestParameters: CreateAccountWithBodyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>>;

    /**
     * Create a new account
     */
    createAccountWithBody(requestParameters: CreateAccountWithBodyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account>;

    /**
     * 
     * @summary Process a user\'s daily claim request. If the user is not on cooldown, they will receive the allocated, pre-defined amount for a daily claim.
     * @param {string} userid 
     * @param {DailyClaimBodyDto} dailyClaimBodyDto Indicates if the Patreon override is enabled, which means the user is a Patreon member and in some cases, meets the required Patreon tier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    dailyClaimRaw(requestParameters: DailyClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyClaim201Response>>;

    /**
     * Process a user\'s daily claim request. If the user is not on cooldown, they will receive the allocated, pre-defined amount for a daily claim.
     */
    dailyClaim(requestParameters: DailyClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyClaim201Response>;

    /**
     * 
     * @summary Delete an account by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>>;

    /**
     * Delete an account by ID
     */
    deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account>;

    /**
     * 
     * @summary Retrieve all stored accounts & their linked data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Account>>>;

    /**
     * Retrieve all stored accounts & their linked data
     */
    getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Account>>;

    /**
     * 
     * @summary Get an account\'s balance
     * @param {string} userid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getBalanceRaw(requestParameters: GetBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBalanceDto>>;

    /**
     * Get an account\'s balance
     */
    getBalance(requestParameters: GetBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBalanceDto>;

    /**
     * 
     * @summary Get leaderboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getLeaderboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetLeaderboardDto>>>;

    /**
     * Get leaderboard
     */
    getLeaderboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetLeaderboardDto>>;

    /**
     * 
     * @summary Get multiple accounts by IDs
     * @param {Array<string>} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getManyRaw(requestParameters: GetManyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Account>>>;

    /**
     * Get multiple accounts by IDs
     */
    getMany(requestParameters: GetManyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Account>>;

    /**
     * 
     * @summary Get a single account by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getOneRaw(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>>;

    /**
     * Get a single account by ID
     */
    getOne(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account>;

    /**
     * 
     * @summary Update an account by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    updateAccountRaw(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>>;

    /**
     * Update an account by ID
     */
    updateAccount(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account>;

    /**
     * 
     * @summary Get a user\'s profile
     * @param {string} userid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    userProfileRaw(requestParameters: UserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProfileDto>>;

    /**
     * Get a user\'s profile
     */
    userProfile(requestParameters: UserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProfileDto>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * Create Account
     */
    async createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters['userid'] == null) {
            throw new runtime.RequiredError(
                'userid',
                'Required parameter "userid" was null or undefined when calling createAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/create/{userid}`.replace(`{${"userid"}}`, encodeURIComponent(String(requestParameters['userid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Create Account
     */
    async createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account> {
        const response = await this.createAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new account
     */
    async createAccountWithBodyRaw(requestParameters: CreateAccountWithBodyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters['createAccountWithBodyRequest'] == null) {
            throw new runtime.RequiredError(
                'createAccountWithBodyRequest',
                'Required parameter "createAccountWithBodyRequest" was null or undefined when calling createAccountWithBody().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAccountWithBodyRequestToJSON(requestParameters['createAccountWithBodyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Create a new account
     */
    async createAccountWithBody(requestParameters: CreateAccountWithBodyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account> {
        const response = await this.createAccountWithBodyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Process a user\'s daily claim request. If the user is not on cooldown, they will receive the allocated, pre-defined amount for a daily claim.
     */
    async dailyClaimRaw(requestParameters: DailyClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyClaim201Response>> {
        if (requestParameters['userid'] == null) {
            throw new runtime.RequiredError(
                'userid',
                'Required parameter "userid" was null or undefined when calling dailyClaim().'
            );
        }

        if (requestParameters['dailyClaimBodyDto'] == null) {
            throw new runtime.RequiredError(
                'dailyClaimBodyDto',
                'Required parameter "dailyClaimBodyDto" was null or undefined when calling dailyClaim().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/accounts/dailyclaim/claim/{userid}`.replace(`{${"userid"}}`, encodeURIComponent(String(requestParameters['userid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DailyClaimBodyDtoToJSON(requestParameters['dailyClaimBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyClaim201ResponseFromJSON(jsonValue));
    }

    /**
     * Process a user\'s daily claim request. If the user is not on cooldown, they will receive the allocated, pre-defined amount for a daily claim.
     */
    async dailyClaim(requestParameters: DailyClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyClaim201Response> {
        const response = await this.dailyClaimRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an account by ID
     */
    async deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Delete an account by ID
     */
    async deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account> {
        const response = await this.deleteAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all stored accounts & their linked data
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Account>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountFromJSON));
    }

    /**
     * Retrieve all stored accounts & their linked data
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Account>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get an account\'s balance
     */
    async getBalanceRaw(requestParameters: GetBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBalanceDto>> {
        if (requestParameters['userid'] == null) {
            throw new runtime.RequiredError(
                'userid',
                'Required parameter "userid" was null or undefined when calling getBalance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/balance/{userid}`.replace(`{${"userid"}}`, encodeURIComponent(String(requestParameters['userid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBalanceDtoFromJSON(jsonValue));
    }

    /**
     * Get an account\'s balance
     */
    async getBalance(requestParameters: GetBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBalanceDto> {
        const response = await this.getBalanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get leaderboard
     */
    async getLeaderboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetLeaderboardDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetLeaderboardDtoFromJSON));
    }

    /**
     * Get leaderboard
     */
    async getLeaderboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetLeaderboardDto>> {
        const response = await this.getLeaderboardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get multiple accounts by IDs
     */
    async getManyRaw(requestParameters: GetManyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Account>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMany().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountFromJSON));
    }

    /**
     * Get multiple accounts by IDs
     */
    async getMany(requestParameters: GetManyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Account>> {
        const response = await this.getManyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single account by ID
     */
    async getOneRaw(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Get a single account by ID
     */
    async getOne(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account> {
        const response = await this.getOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an account by ID
     */
    async updateAccountRaw(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Update an account by ID
     */
    async updateAccount(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Account> {
        const response = await this.updateAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a user\'s profile
     */
    async userProfileRaw(requestParameters: UserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProfileDto>> {
        if (requestParameters['userid'] == null) {
            throw new runtime.RequiredError(
                'userid',
                'Required parameter "userid" was null or undefined when calling userProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/accounts/profile/{userid}`.replace(`{${"userid"}}`, encodeURIComponent(String(requestParameters['userid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProfileDtoFromJSON(jsonValue));
    }

    /**
     * Get a user\'s profile
     */
    async userProfile(requestParameters: UserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProfileDto> {
        const response = await this.userProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
