/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';

export interface GetSeasonYearRequest {
    sport: GetSeasonYearSportEnum;
    referenceDate?: string;
}

/**
 * CalendarApi - interface
 * 
 * @export
 * @interface CalendarApiInterface
 */
export interface CalendarApiInterface {
    /**
     * 
     * @summary Get the current season year for a given sport
     * @param {'nba' | 'mlb' | 'nfl' | 'nhl'} sport The sport slug to get the season year for
     * @param {string} [referenceDate] Reference date to get the season year for. If not provided, current date will be used.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarApiInterface
     */
    getSeasonYearRaw(requestParameters: GetSeasonYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>>;

    /**
     * Get the current season year for a given sport
     */
    getSeasonYear(requestParameters: GetSeasonYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number>;

}

/**
 * 
 */
export class CalendarApi extends runtime.BaseAPI implements CalendarApiInterface {

    /**
     * Get the current season year for a given sport
     */
    async getSeasonYearRaw(requestParameters: GetSeasonYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getSeasonYear().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['referenceDate'] != null) {
            queryParameters['referenceDate'] = requestParameters['referenceDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/calendar/season-year`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get the current season year for a given sport
     */
    async getSeasonYear(requestParameters: GetSeasonYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getSeasonYearRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSeasonYearSportEnum = {
    Nba: 'nba',
    Mlb: 'mlb',
    Nfl: 'nfl',
    Nhl: 'nhl'
} as const;
export type GetSeasonYearSportEnum = typeof GetSeasonYearSportEnum[keyof typeof GetSeasonYearSportEnum];
