/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Changelog,
  CreateChangelogDto,
  UpdateChangelogDto,
} from '../models/index.js';
import {
    ChangelogFromJSON,
    ChangelogToJSON,
    CreateChangelogDtoFromJSON,
    CreateChangelogDtoToJSON,
    UpdateChangelogDtoFromJSON,
    UpdateChangelogDtoToJSON,
} from '../models/index.js';

export interface CreateChangelogRequest {
    createChangelogDto: CreateChangelogDto;
}

export interface DeleteChangelogRequest {
    id: string;
}

export interface GetChangelogsRequest {
    app?: GetChangelogsAppEnum;
    limit?: number;
}

export interface GetChangelogsSinceRequest {
    app: GetChangelogsSinceAppEnum;
    version: string;
}

export interface GetLatestChangelogRequest {
    app: GetLatestChangelogAppEnum;
}

export interface UpdateChangelogRequest {
    id: string;
    updateChangelogDto: UpdateChangelogDto;
}

/**
 * ChangelogsApi - interface
 * 
 * @export
 * @interface ChangelogsApiInterface
 */
export interface ChangelogsApiInterface {
    /**
     * 
     * @summary Create a new changelog entry
     * @param {CreateChangelogDto} createChangelogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    createChangelogRaw(requestParameters: CreateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>>;

    /**
     * Create a new changelog entry
     */
    createChangelog(requestParameters: CreateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog>;

    /**
     * 
     * @summary Delete a changelog entry
     * @param {string} id Changelog UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    deleteChangelogRaw(requestParameters: DeleteChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a changelog entry
     */
    deleteChangelog(requestParameters: DeleteChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get changelogs
     * @param {'Pluto' | 'Khronos' | 'Goracle'} [app] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    getChangelogsRaw(requestParameters: GetChangelogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Changelog>>>;

    /**
     * Get changelogs
     */
    getChangelogs(requestParameters: GetChangelogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Changelog>>;

    /**
     * Returns all changelogs for the specified app published after the given version (based on published_at date)
     * @summary Get changelogs published after a specific version
     * @param {'Pluto' | 'Khronos' | 'Goracle'} app 
     * @param {string} version 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    getChangelogsSinceRaw(requestParameters: GetChangelogsSinceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Changelog>>>;

    /**
     * Returns all changelogs for the specified app published after the given version (based on published_at date)
     * Get changelogs published after a specific version
     */
    getChangelogsSince(requestParameters: GetChangelogsSinceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Changelog>>;

    /**
     * 
     * @summary Get the single latest changelog
     * @param {'Pluto' | 'Khronos' | 'Goracle'} app 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    getLatestChangelogRaw(requestParameters: GetLatestChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>>;

    /**
     * Get the single latest changelog
     */
    getLatestChangelog(requestParameters: GetLatestChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog>;

    /**
     * 
     * @summary Update an existing changelog entry
     * @param {string} id Changelog UUID
     * @param {UpdateChangelogDto} updateChangelogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangelogsApiInterface
     */
    updateChangelogRaw(requestParameters: UpdateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>>;

    /**
     * Update an existing changelog entry
     */
    updateChangelog(requestParameters: UpdateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog>;

}

/**
 * 
 */
export class ChangelogsApi extends runtime.BaseAPI implements ChangelogsApiInterface {

    /**
     * Create a new changelog entry
     */
    async createChangelogRaw(requestParameters: CreateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>> {
        if (requestParameters['createChangelogDto'] == null) {
            throw new runtime.RequiredError(
                'createChangelogDto',
                'Required parameter "createChangelogDto" was null or undefined when calling createChangelog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/changelogs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChangelogDtoToJSON(requestParameters['createChangelogDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangelogFromJSON(jsonValue));
    }

    /**
     * Create a new changelog entry
     */
    async createChangelog(requestParameters: CreateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog> {
        const response = await this.createChangelogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a changelog entry
     */
    async deleteChangelogRaw(requestParameters: DeleteChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteChangelog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/changelogs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a changelog entry
     */
    async deleteChangelog(requestParameters: DeleteChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteChangelogRaw(requestParameters, initOverrides);
    }

    /**
     * Get changelogs
     */
    async getChangelogsRaw(requestParameters: GetChangelogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Changelog>>> {
        const queryParameters: any = {};

        if (requestParameters['app'] != null) {
            queryParameters['app'] = requestParameters['app'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/changelogs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChangelogFromJSON));
    }

    /**
     * Get changelogs
     */
    async getChangelogs(requestParameters: GetChangelogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Changelog>> {
        const response = await this.getChangelogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all changelogs for the specified app published after the given version (based on published_at date)
     * Get changelogs published after a specific version
     */
    async getChangelogsSinceRaw(requestParameters: GetChangelogsSinceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Changelog>>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getChangelogsSince().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getChangelogsSince().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['app'] != null) {
            queryParameters['app'] = requestParameters['app'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/changelogs/since`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChangelogFromJSON));
    }

    /**
     * Returns all changelogs for the specified app published after the given version (based on published_at date)
     * Get changelogs published after a specific version
     */
    async getChangelogsSince(requestParameters: GetChangelogsSinceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Changelog>> {
        const response = await this.getChangelogsSinceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the single latest changelog
     */
    async getLatestChangelogRaw(requestParameters: GetLatestChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getLatestChangelog().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['app'] != null) {
            queryParameters['app'] = requestParameters['app'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/changelogs/latest`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangelogFromJSON(jsonValue));
    }

    /**
     * Get the single latest changelog
     */
    async getLatestChangelog(requestParameters: GetLatestChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog> {
        const response = await this.getLatestChangelogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing changelog entry
     */
    async updateChangelogRaw(requestParameters: UpdateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Changelog>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateChangelog().'
            );
        }

        if (requestParameters['updateChangelogDto'] == null) {
            throw new runtime.RequiredError(
                'updateChangelogDto',
                'Required parameter "updateChangelogDto" was null or undefined when calling updateChangelog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/changelogs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateChangelogDtoToJSON(requestParameters['updateChangelogDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangelogFromJSON(jsonValue));
    }

    /**
     * Update an existing changelog entry
     */
    async updateChangelog(requestParameters: UpdateChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Changelog> {
        const response = await this.updateChangelogRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetChangelogsAppEnum = {
    Pluto: 'Pluto',
    Khronos: 'Khronos',
    Goracle: 'Goracle'
} as const;
export type GetChangelogsAppEnum = typeof GetChangelogsAppEnum[keyof typeof GetChangelogsAppEnum];
/**
 * @export
 */
export const GetChangelogsSinceAppEnum = {
    Pluto: 'Pluto',
    Khronos: 'Khronos',
    Goracle: 'Goracle'
} as const;
export type GetChangelogsSinceAppEnum = typeof GetChangelogsSinceAppEnum[keyof typeof GetChangelogsSinceAppEnum];
/**
 * @export
 */
export const GetLatestChangelogAppEnum = {
    Pluto: 'Pluto',
    Khronos: 'Khronos',
    Goracle: 'Goracle'
} as const;
export type GetLatestChangelogAppEnum = typeof GetLatestChangelogAppEnum[keyof typeof GetLatestChangelogAppEnum];
