/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AllChannelsDto,
  RemoveAllChannelsDto,
  StoredChannelDto,
  UpdateChannelDto,
} from '../models/index.js';
import {
    AllChannelsDtoFromJSON,
    AllChannelsDtoToJSON,
    RemoveAllChannelsDtoFromJSON,
    RemoveAllChannelsDtoToJSON,
    StoredChannelDtoFromJSON,
    StoredChannelDtoToJSON,
    UpdateChannelDtoFromJSON,
    UpdateChannelDtoToJSON,
} from '../models/index.js';

export interface DeleteChannelRequest {
    id: string;
}

export interface FindAllChannelsRequest {
    sport?: string;
}

export interface GameChannelControllerFindByIdV1Request {
    id: string;
}

export interface GameChannelControllerGetChannelStatusV1Request {
    timeframe?: string;
}

export interface GameChannelControllerGetCreationHistoryV1Request {
    startDate: string;
    endDate: string;
    sport?: string;
    status?: GameChannelControllerGetCreationHistoryV1StatusEnum;
    guildId?: string;
}

export interface GameChannelControllerGetScheduledForTodayV1Request {
    date?: string;
}

export interface UpdateChannelRequest {
    id: string;
    updateChannelDto: UpdateChannelDto;
}

/**
 * ChannelsApi - interface
 * 
 * @export
 * @interface ChannelsApiInterface
 */
export interface ChannelsApiInterface {
    /**
     * 
     * @summary Delete a channel by ID
     * @param {string} id Channel ID to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    deleteChannelRaw(requestParameters: DeleteChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveAllChannelsDto>>;

    /**
     * Delete a channel by ID
     */
    deleteChannel(requestParameters: DeleteChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveAllChannelsDto>;

    /**
     * 
     * @summary Find all channels
     * @param {string} [sport] Filter channels by sport
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    findAllChannelsRaw(requestParameters: FindAllChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllChannelsDto>>;

    /**
     * Find all channels
     */
    findAllChannels(requestParameters: FindAllChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllChannelsDto>;

    /**
     * 
     * @summary Find a channel by ID
     * @param {string} id Channel ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    gameChannelControllerFindByIdV1Raw(requestParameters: GameChannelControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredChannelDto>>;

    /**
     * Find a channel by ID
     */
    gameChannelControllerFindByIdV1(requestParameters: GameChannelControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredChannelDto>;

    /**
     * Dashboard view showing summary statistics, upcoming channels, and recent failures
     * @summary Get channel system status and health metrics
     * @param {string} [timeframe] Time window to analyze (e.g., \&quot;24h\&quot;, \&quot;48h\&quot;, \&quot;7d\&quot;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    gameChannelControllerGetChannelStatusV1Raw(requestParameters: GameChannelControllerGetChannelStatusV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Dashboard view showing summary statistics, upcoming channels, and recent failures
     * Get channel system status and health metrics
     */
    gameChannelControllerGetChannelStatusV1(requestParameters: GameChannelControllerGetChannelStatusV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Shows success/failure statistics and detailed history with optional filters
     * @summary Get historical channel creation data
     * @param {string} startDate Start date for history query (ISO 8601 format)
     * @param {string} endDate End date for history query (ISO 8601 format)
     * @param {string} [sport] Filter by sport (e.g., \&quot;nba\&quot;, \&quot;nfl\&quot;)
     * @param {'queued' | 'success' | 'failed'} [status] Filter by status
     * @param {string} [guildId] Filter by Discord guild ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    gameChannelControllerGetCreationHistoryV1Raw(requestParameters: GameChannelControllerGetCreationHistoryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Shows success/failure statistics and detailed history with optional filters
     * Get historical channel creation data
     */
    gameChannelControllerGetCreationHistoryV1(requestParameters: GameChannelControllerGetCreationHistoryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Shows pending, scheduled, and created channels with time estimates for observability
     * @summary Get all channels scheduled for a specific date
     * @param {string} [date] Date to query (format: \&#39;YYYY-MM-DD\&#39; or \&#39;today\&#39;). Defaults to today.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    gameChannelControllerGetScheduledForTodayV1Raw(requestParameters: GameChannelControllerGetScheduledForTodayV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Shows pending, scheduled, and created channels with time estimates for observability
     * Get all channels scheduled for a specific date
     */
    gameChannelControllerGetScheduledForTodayV1(requestParameters: GameChannelControllerGetScheduledForTodayV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    gameChannelControllerPushScheduledV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    gameChannelControllerPushScheduledV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Remove all channels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    removeAllChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveAllChannelsDto>>;

    /**
     * Remove all channels
     */
    removeAllChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveAllChannelsDto>;

    /**
     * 
     * @summary Update a channel by ID
     * @param {string} id Channel ID to update
     * @param {UpdateChannelDto} updateChannelDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApiInterface
     */
    updateChannelRaw(requestParameters: UpdateChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChannelDto>>;

    /**
     * Update a channel by ID
     */
    updateChannel(requestParameters: UpdateChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChannelDto>;

}

/**
 * 
 */
export class ChannelsApi extends runtime.BaseAPI implements ChannelsApiInterface {

    /**
     * Delete a channel by ID
     */
    async deleteChannelRaw(requestParameters: DeleteChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveAllChannelsDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveAllChannelsDtoFromJSON(jsonValue));
    }

    /**
     * Delete a channel by ID
     */
    async deleteChannel(requestParameters: DeleteChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveAllChannelsDto> {
        const response = await this.deleteChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find all channels
     */
    async findAllChannelsRaw(requestParameters: FindAllChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllChannelsDto>> {
        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllChannelsDtoFromJSON(jsonValue));
    }

    /**
     * Find all channels
     */
    async findAllChannels(requestParameters: FindAllChannelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllChannelsDto> {
        const response = await this.findAllChannelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find a channel by ID
     */
    async gameChannelControllerFindByIdV1Raw(requestParameters: GameChannelControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredChannelDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameChannelControllerFindByIdV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoredChannelDtoFromJSON(jsonValue));
    }

    /**
     * Find a channel by ID
     */
    async gameChannelControllerFindByIdV1(requestParameters: GameChannelControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredChannelDto> {
        const response = await this.gameChannelControllerFindByIdV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Dashboard view showing summary statistics, upcoming channels, and recent failures
     * Get channel system status and health metrics
     */
    async gameChannelControllerGetChannelStatusV1Raw(requestParameters: GameChannelControllerGetChannelStatusV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Dashboard view showing summary statistics, upcoming channels, and recent failures
     * Get channel system status and health metrics
     */
    async gameChannelControllerGetChannelStatusV1(requestParameters: GameChannelControllerGetChannelStatusV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gameChannelControllerGetChannelStatusV1Raw(requestParameters, initOverrides);
    }

    /**
     * Shows success/failure statistics and detailed history with optional filters
     * Get historical channel creation data
     */
    async gameChannelControllerGetCreationHistoryV1Raw(requestParameters: GameChannelControllerGetCreationHistoryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['startDate'] == null) {
            throw new runtime.RequiredError(
                'startDate',
                'Required parameter "startDate" was null or undefined when calling gameChannelControllerGetCreationHistoryV1().'
            );
        }

        if (requestParameters['endDate'] == null) {
            throw new runtime.RequiredError(
                'endDate',
                'Required parameter "endDate" was null or undefined when calling gameChannelControllerGetCreationHistoryV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['guildId'] != null) {
            queryParameters['guildId'] = requestParameters['guildId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Shows success/failure statistics and detailed history with optional filters
     * Get historical channel creation data
     */
    async gameChannelControllerGetCreationHistoryV1(requestParameters: GameChannelControllerGetCreationHistoryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gameChannelControllerGetCreationHistoryV1Raw(requestParameters, initOverrides);
    }

    /**
     * Shows pending, scheduled, and created channels with time estimates for observability
     * Get all channels scheduled for a specific date
     */
    async gameChannelControllerGetScheduledForTodayV1Raw(requestParameters: GameChannelControllerGetScheduledForTodayV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/scheduled/today`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Shows pending, scheduled, and created channels with time estimates for observability
     * Get all channels scheduled for a specific date
     */
    async gameChannelControllerGetScheduledForTodayV1(requestParameters: GameChannelControllerGetScheduledForTodayV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gameChannelControllerGetScheduledForTodayV1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async gameChannelControllerPushScheduledV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/push-scheduled`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async gameChannelControllerPushScheduledV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gameChannelControllerPushScheduledV1Raw(initOverrides);
    }

    /**
     * Remove all channels
     */
    async removeAllChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveAllChannelsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/channels/all`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveAllChannelsDtoFromJSON(jsonValue));
    }

    /**
     * Remove all channels
     */
    async removeAllChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveAllChannelsDto> {
        const response = await this.removeAllChannelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a channel by ID
     */
    async updateChannelRaw(requestParameters: UpdateChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChannelDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateChannel().'
            );
        }

        if (requestParameters['updateChannelDto'] == null) {
            throw new runtime.RequiredError(
                'updateChannelDto',
                'Required parameter "updateChannelDto" was null or undefined when calling updateChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/channels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateChannelDtoToJSON(requestParameters['updateChannelDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateChannelDtoFromJSON(jsonValue));
    }

    /**
     * Update a channel by ID
     */
    async updateChannel(requestParameters: UpdateChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChannelDto> {
        const response = await this.updateChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GameChannelControllerGetCreationHistoryV1StatusEnum = {
    Queued: 'queued',
    Success: 'success',
    Failed: 'failed'
} as const;
export type GameChannelControllerGetCreationHistoryV1StatusEnum = typeof GameChannelControllerGetCreationHistoryV1StatusEnum[keyof typeof GameChannelControllerGetCreationHistoryV1StatusEnum];
