/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CreateConfigDto,
  StoredConfigDto,
} from '../models/index.js';
import {
    CreateConfigDtoFromJSON,
    CreateConfigDtoToJSON,
    StoredConfigDtoFromJSON,
    StoredConfigDtoToJSON,
} from '../models/index.js';

export interface ConfigByTypeRequest {
    config: string;
}

export interface SetGuildConfigRequest {
    createConfigDto: CreateConfigDto;
}

/**
 * DiscordConfigApi - interface
 * 
 * @export
 * @interface DiscordConfigApiInterface
 */
export interface DiscordConfigApiInterface {
    /**
     * 
     * @summary Get all betting channels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    allBettingChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get all betting channels
     */
    allBettingChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get all categories grouped by guild
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    allCategoriesByGuildRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get all categories grouped by guild
     */
    allCategoriesByGuild(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get all values that match a configuration by type
     * @param {string} config Config type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    configByTypeRaw(requestParameters: ConfigByTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredConfigDto>>;

    /**
     * Get all values that match a configuration by type
     */
    configByType(requestParameters: ConfigByTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredConfigDto>;

    /**
     * 
     * @summary Get all game categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    discordConfigControllerGetGameCategoriesV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get all game categories
     */
    discordConfigControllerGetGameCategoriesV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get game schedules
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    getGameScheduleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get game schedules
     */
    getGameSchedule(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Add or Update a Discord configuration
     * @param {CreateConfigDto} createConfigDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscordConfigApiInterface
     */
    setGuildConfigRaw(requestParameters: SetGuildConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Add or Update a Discord configuration
     */
    setGuildConfig(requestParameters: SetGuildConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class DiscordConfigApi extends runtime.BaseAPI implements DiscordConfigApiInterface {

    /**
     * Get all betting channels
     */
    async allBettingChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/all/betting-channels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all betting channels
     */
    async allBettingChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.allBettingChannelsRaw(initOverrides);
    }

    /**
     * Get all categories grouped by guild
     */
    async allCategoriesByGuildRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/by-guild`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all categories grouped by guild
     */
    async allCategoriesByGuild(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.allCategoriesByGuildRaw(initOverrides);
    }

    /**
     * Get all values that match a configuration by type
     */
    async configByTypeRaw(requestParameters: ConfigByTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredConfigDto>> {
        if (requestParameters['config'] == null) {
            throw new runtime.RequiredError(
                'config',
                'Required parameter "config" was null or undefined when calling configByType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/type/{config}`.replace(`{${"config"}}`, encodeURIComponent(String(requestParameters['config']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoredConfigDtoFromJSON(jsonValue));
    }

    /**
     * Get all values that match a configuration by type
     */
    async configByType(requestParameters: ConfigByTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredConfigDto> {
        const response = await this.configByTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all game categories
     */
    async discordConfigControllerGetGameCategoriesV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/categories/sports/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all game categories
     */
    async discordConfigControllerGetGameCategoriesV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.discordConfigControllerGetGameCategoriesV1Raw(initOverrides);
    }

    /**
     * Get game schedules
     */
    async getGameScheduleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/games/schedule/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get game schedules
     */
    async getGameSchedule(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getGameScheduleRaw(initOverrides);
    }

    /**
     * Add or Update a Discord configuration
     */
    async setGuildConfigRaw(requestParameters: SetGuildConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createConfigDto'] == null) {
            throw new runtime.RequiredError(
                'createConfigDto',
                'Required parameter "createConfigDto" was null or undefined when calling setGuildConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/discord/configs/set`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConfigDtoToJSON(requestParameters['createConfigDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add or Update a Discord configuration
     */
    async setGuildConfig(requestParameters: SetGuildConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setGuildConfigRaw(requestParameters, initOverrides);
    }

}
