/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CreateFooterDto,
  Footer,
  FooterConfigResponseDto,
  UpdateFooterDto,
} from '../models/index.js';
import {
    CreateFooterDtoFromJSON,
    CreateFooterDtoToJSON,
    FooterFromJSON,
    FooterToJSON,
    FooterConfigResponseDtoFromJSON,
    FooterConfigResponseDtoToJSON,
    UpdateFooterDtoFromJSON,
    UpdateFooterDtoToJSON,
} from '../models/index.js';

export interface BulkCreateFootersRequest {
    requestBody: Array<string>;
}

export interface CreateFooterRequest {
    createFooterDto: CreateFooterDto;
}

export interface DeleteFooterRequest {
    id: number;
}

export interface GetFooterRequest {
    id: number;
}

export interface UpdateFooterRequest {
    id: number;
    updateFooterDto: UpdateFooterDto;
}

/**
 * FootersApi - interface
 * 
 * @export
 * @interface FootersApiInterface
 */
export interface FootersApiInterface {
    /**
     * 
     * @summary Bulk create footers (for seeding)
     * @param {Array<string>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    bulkCreateFootersRaw(requestParameters: BulkCreateFootersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Footer>>>;

    /**
     * Bulk create footers (for seeding)
     */
    bulkCreateFooters(requestParameters: BulkCreateFootersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Footer>>;

    /**
     * 
     * @summary Create a new footer
     * @param {CreateFooterDto} createFooterDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    createFooterRaw(requestParameters: CreateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>>;

    /**
     * Create a new footer
     */
    createFooter(requestParameters: CreateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer>;

    /**
     * 
     * @summary Delete a footer
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    deleteFooterRaw(requestParameters: DeleteFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a footer
     */
    deleteFooter(requestParameters: DeleteFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get a single footer by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    getFooterRaw(requestParameters: GetFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>>;

    /**
     * Get a single footer by ID
     */
    getFooter(requestParameters: GetFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer>;

    /**
     * Returns active announcement (if any) and all active footers grouped by category
     * @summary Get footer configuration for consumers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    getFooterConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FooterConfigResponseDto>>;

    /**
     * Returns active announcement (if any) and all active footers grouped by category
     * Get footer configuration for consumers
     */
    getFooterConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FooterConfigResponseDto>;

    /**
     * 
     * @summary List all footers (admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    listFootersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Footer>>>;

    /**
     * List all footers (admin)
     */
    listFooters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Footer>>;

    /**
     * 
     * @summary Update an existing footer
     * @param {number} id 
     * @param {UpdateFooterDto} updateFooterDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FootersApiInterface
     */
    updateFooterRaw(requestParameters: UpdateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>>;

    /**
     * Update an existing footer
     */
    updateFooter(requestParameters: UpdateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer>;

}

/**
 * 
 */
export class FootersApi extends runtime.BaseAPI implements FootersApiInterface {

    /**
     * Bulk create footers (for seeding)
     */
    async bulkCreateFootersRaw(requestParameters: BulkCreateFootersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Footer>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling bulkCreateFooters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/footers/bulk`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FooterFromJSON));
    }

    /**
     * Bulk create footers (for seeding)
     */
    async bulkCreateFooters(requestParameters: BulkCreateFootersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Footer>> {
        const response = await this.bulkCreateFootersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new footer
     */
    async createFooterRaw(requestParameters: CreateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>> {
        if (requestParameters['createFooterDto'] == null) {
            throw new runtime.RequiredError(
                'createFooterDto',
                'Required parameter "createFooterDto" was null or undefined when calling createFooter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/footers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFooterDtoToJSON(requestParameters['createFooterDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FooterFromJSON(jsonValue));
    }

    /**
     * Create a new footer
     */
    async createFooter(requestParameters: CreateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer> {
        const response = await this.createFooterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a footer
     */
    async deleteFooterRaw(requestParameters: DeleteFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFooter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/footers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a footer
     */
    async deleteFooter(requestParameters: DeleteFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFooterRaw(requestParameters, initOverrides);
    }

    /**
     * Get a single footer by ID
     */
    async getFooterRaw(requestParameters: GetFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFooter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/footers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FooterFromJSON(jsonValue));
    }

    /**
     * Get a single footer by ID
     */
    async getFooter(requestParameters: GetFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer> {
        const response = await this.getFooterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns active announcement (if any) and all active footers grouped by category
     * Get footer configuration for consumers
     */
    async getFooterConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FooterConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/footers/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FooterConfigResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns active announcement (if any) and all active footers grouped by category
     * Get footer configuration for consumers
     */
    async getFooterConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FooterConfigResponseDto> {
        const response = await this.getFooterConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all footers (admin)
     */
    async listFootersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Footer>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/footers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FooterFromJSON));
    }

    /**
     * List all footers (admin)
     */
    async listFooters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Footer>> {
        const response = await this.listFootersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an existing footer
     */
    async updateFooterRaw(requestParameters: UpdateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Footer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateFooter().'
            );
        }

        if (requestParameters['updateFooterDto'] == null) {
            throw new runtime.RequiredError(
                'updateFooterDto',
                'Required parameter "updateFooterDto" was null or undefined when calling updateFooter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/footers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFooterDtoToJSON(requestParameters['updateFooterDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FooterFromJSON(jsonValue));
    }

    /**
     * Update an existing footer
     */
    async updateFooter(requestParameters: UpdateFooterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Footer> {
        const response = await this.updateFooterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
