/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';

export interface GoracleControllerCollectAllV1Request {
    force?: string;
}

export interface GoracleControllerCollectOddsV1Request {
    sport: string;
    force?: string;
}

/**
 * GoracleApi - interface
 * 
 * @export
 * @interface GoracleApiInterface
 */
export interface GoracleApiInterface {
    /**
     * 
     * @summary Trigger manual odds collection for all sports
     * @param {string} [force] Force collection regardless of internal scheduling
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoracleApiInterface
     */
    goracleControllerCollectAllV1Raw(requestParameters: GoracleControllerCollectAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Trigger manual odds collection for all sports
     */
    goracleControllerCollectAllV1(requestParameters: GoracleControllerCollectAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * 
     * @summary Trigger manual odds collection for a specific sport
     * @param {string} sport Sport key to collect odds for (e.g., football, basketball)
     * @param {string} [force] Force collection regardless of internal scheduling
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoracleApiInterface
     */
    goracleControllerCollectOddsV1Raw(requestParameters: GoracleControllerCollectOddsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Trigger manual odds collection for a specific sport
     */
    goracleControllerCollectOddsV1(requestParameters: GoracleControllerCollectOddsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * 
     * @summary Health check for Goracle service
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoracleApiInterface
     */
    goracleControllerHealthCheckV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>>;

    /**
     * Health check for Goracle service
     */
    goracleControllerHealthCheckV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean>;

}

/**
 * 
 */
export class GoracleApi extends runtime.BaseAPI implements GoracleApiInterface {

    /**
     * Trigger manual odds collection for all sports
     */
    async goracleControllerCollectAllV1Raw(requestParameters: GoracleControllerCollectAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/goracle/collect/all`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger manual odds collection for all sports
     */
    async goracleControllerCollectAllV1(requestParameters: GoracleControllerCollectAllV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.goracleControllerCollectAllV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger manual odds collection for a specific sport
     */
    async goracleControllerCollectOddsV1Raw(requestParameters: GoracleControllerCollectOddsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling goracleControllerCollectOddsV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/goracle/collect`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger manual odds collection for a specific sport
     */
    async goracleControllerCollectOddsV1(requestParameters: GoracleControllerCollectOddsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.goracleControllerCollectOddsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check for Goracle service
     */
    async goracleControllerHealthCheckV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/goracle/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health check for Goracle service
     */
    async goracleControllerHealthCheckV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.goracleControllerHealthCheckV1Raw(initOverrides);
        return await response.value();
    }

}
