/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AddGuild409Response,
  CreateGuildDto,
  GetAllGuilds404Response,
  GetGuildById404Response,
  Guild,
} from '../models/index.js';
import {
    AddGuild409ResponseFromJSON,
    AddGuild409ResponseToJSON,
    CreateGuildDtoFromJSON,
    CreateGuildDtoToJSON,
    GetAllGuilds404ResponseFromJSON,
    GetAllGuilds404ResponseToJSON,
    GetGuildById404ResponseFromJSON,
    GetGuildById404ResponseToJSON,
    GuildFromJSON,
    GuildToJSON,
} from '../models/index.js';

export interface AddGuildRequest {
    createGuildDto: CreateGuildDto;
}

export interface GetGuildByIdRequest {
    id: string;
}

export interface GetGuildsBySportRequest {
    sport: string;
}

export interface GetGuildsBySportAndConfigTypeRequest {
    sport: string;
    configType: GetGuildsBySportAndConfigTypeConfigTypeEnum;
}

/**
 * GuildsApi - interface
 * 
 * @export
 * @interface GuildsApiInterface
 */
export interface GuildsApiInterface {
    /**
     * 
     * @summary Add a new guild
     * @param {CreateGuildDto} createGuildDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuildsApiInterface
     */
    addGuildRaw(requestParameters: AddGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Guild>>;

    /**
     * Add a new guild
     */
    addGuild(requestParameters: AddGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Guild>;

    /**
     * 
     * @summary Get all guilds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuildsApiInterface
     */
    getAllGuildsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>>;

    /**
     * Get all guilds
     */
    getAllGuilds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>>;

    /**
     * 
     * @summary Get guild by id
     * @param {string} id Guild id to filter guild by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuildsApiInterface
     */
    getGuildByIdRaw(requestParameters: GetGuildByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Guild>>;

    /**
     * Get guild by id
     */
    getGuildById(requestParameters: GetGuildByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Guild>;

    /**
     * 
     * @summary Get guilds by sport
     * @param {string} sport Sport to filter guilds by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuildsApiInterface
     */
    getGuildsBySportRaw(requestParameters: GetGuildsBySportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>>;

    /**
     * Get guilds by sport
     */
    getGuildsBySport(requestParameters: GetGuildsBySportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>>;

    /**
     * 
     * @summary Get guilds by sport and config type
     * @param {string} sport Sport to filter guilds by
     * @param {'GAMES_CATEGORY' | 'BETTING_CHAN' | 'DAILY_SCHEDULE_CHAN' | 'PREDICTIONS_CHAN' | 'LOGS_CHAN' | 'LOGS_ENABLED' | 'PREFERRED_TEAMS'} configType Config type to filter guilds by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuildsApiInterface
     */
    getGuildsBySportAndConfigTypeRaw(requestParameters: GetGuildsBySportAndConfigTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>>;

    /**
     * Get guilds by sport and config type
     */
    getGuildsBySportAndConfigType(requestParameters: GetGuildsBySportAndConfigTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>>;

}

/**
 * 
 */
export class GuildsApi extends runtime.BaseAPI implements GuildsApiInterface {

    /**
     * Add a new guild
     */
    async addGuildRaw(requestParameters: AddGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Guild>> {
        if (requestParameters['createGuildDto'] == null) {
            throw new runtime.RequiredError(
                'createGuildDto',
                'Required parameter "createGuildDto" was null or undefined when calling addGuild().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/guilds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGuildDtoToJSON(requestParameters['createGuildDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuildFromJSON(jsonValue));
    }

    /**
     * Add a new guild
     */
    async addGuild(requestParameters: AddGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Guild> {
        const response = await this.addGuildRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all guilds
     */
    async getAllGuildsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/guilds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GuildFromJSON));
    }

    /**
     * Get all guilds
     */
    async getAllGuilds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>> {
        const response = await this.getAllGuildsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get guild by id
     */
    async getGuildByIdRaw(requestParameters: GetGuildByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Guild>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGuildById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/guilds/id/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuildFromJSON(jsonValue));
    }

    /**
     * Get guild by id
     */
    async getGuildById(requestParameters: GetGuildByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Guild> {
        const response = await this.getGuildByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get guilds by sport
     */
    async getGuildsBySportRaw(requestParameters: GetGuildsBySportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getGuildsBySport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/guilds/sport/{sport}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GuildFromJSON));
    }

    /**
     * Get guilds by sport
     */
    async getGuildsBySport(requestParameters: GetGuildsBySportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>> {
        const response = await this.getGuildsBySportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get guilds by sport and config type
     */
    async getGuildsBySportAndConfigTypeRaw(requestParameters: GetGuildsBySportAndConfigTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Guild>>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getGuildsBySportAndConfigType().'
            );
        }

        if (requestParameters['configType'] == null) {
            throw new runtime.RequiredError(
                'configType',
                'Required parameter "configType" was null or undefined when calling getGuildsBySportAndConfigType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/guilds/sport/{sport}/config/{configType}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))).replace(`{${"configType"}}`, encodeURIComponent(String(requestParameters['configType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GuildFromJSON));
    }

    /**
     * Get guilds by sport and config type
     */
    async getGuildsBySportAndConfigType(requestParameters: GetGuildsBySportAndConfigTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Guild>> {
        const response = await this.getGuildsBySportAndConfigTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetGuildsBySportAndConfigTypeConfigTypeEnum = {
    GamesCategory: 'GAMES_CATEGORY',
    BettingChan: 'BETTING_CHAN',
    DailyScheduleChan: 'DAILY_SCHEDULE_CHAN',
    PredictionsChan: 'PREDICTIONS_CHAN',
    LogsChan: 'LOGS_CHAN',
    LogsEnabled: 'LOGS_ENABLED',
    PreferredTeams: 'PREFERRED_TEAMS'
} as const;
export type GetGuildsBySportAndConfigTypeConfigTypeEnum = typeof GetGuildsBySportAndConfigTypeConfigTypeEnum[keyof typeof GetGuildsBySportAndConfigTypeConfigTypeEnum];
