/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';

/**
 * HelloWorldApi - interface
 * 
 * @export
 * @interface HelloWorldApiInterface
 */
export interface HelloWorldApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HelloWorldApiInterface
     */
    helloWorldControllerGetHelloV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    helloWorldControllerGetHelloV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class HelloWorldApi extends runtime.BaseAPI implements HelloWorldApiInterface {

    /**
     */
    async helloWorldControllerGetHelloV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/hello-world`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async helloWorldControllerGetHelloV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.helloWorldControllerGetHelloV1Raw(initOverrides);
    }

}
