/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  LeaderboardControllerInitializeWeeksV1200Response,
  SimpleLeaderboardResponseDto,
} from '../models/index.js';
import {
    LeaderboardControllerInitializeWeeksV1200ResponseFromJSON,
    LeaderboardControllerInitializeWeeksV1200ResponseToJSON,
    SimpleLeaderboardResponseDtoFromJSON,
    SimpleLeaderboardResponseDtoToJSON,
} from '../models/index.js';

export interface LeaderboardControllerGetLeaderboardV1Request {
    guildId: string;
}

export interface LeaderboardControllerInitializeWeeksV1Request {
    sport: LeaderboardControllerInitializeWeeksV1SportEnum;
}

/**
 * LeaderboardApi - interface
 * 
 * @export
 * @interface LeaderboardApiInterface
 */
export interface LeaderboardApiInterface {
    /**
     * 
     * @summary Get leaderboard - All time user stats
     * @param {string} guildId Discord Guild ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeaderboardApiInterface
     */
    leaderboardControllerGetLeaderboardV1Raw(requestParameters: LeaderboardControllerGetLeaderboardV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLeaderboardResponseDto>>;

    /**
     * Get leaderboard - All time user stats
     */
    leaderboardControllerGetLeaderboardV1(requestParameters: LeaderboardControllerGetLeaderboardV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLeaderboardResponseDto>;

    /**
     * 
     * @summary Initialize season scheduled weeks for a given sport
     * @param {'nba' | 'nfl'} sport The sport to initialize weeks for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeaderboardApiInterface
     */
    leaderboardControllerInitializeWeeksV1Raw(requestParameters: LeaderboardControllerInitializeWeeksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardControllerInitializeWeeksV1200Response>>;

    /**
     * Initialize season scheduled weeks for a given sport
     */
    leaderboardControllerInitializeWeeksV1(requestParameters: LeaderboardControllerInitializeWeeksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardControllerInitializeWeeksV1200Response>;

}

/**
 * 
 */
export class LeaderboardApi extends runtime.BaseAPI implements LeaderboardApiInterface {

    /**
     * Get leaderboard - All time user stats
     */
    async leaderboardControllerGetLeaderboardV1Raw(requestParameters: LeaderboardControllerGetLeaderboardV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLeaderboardResponseDto>> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling leaderboardControllerGetLeaderboardV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['guildId'] != null) {
            queryParameters['guild_id'] = requestParameters['guildId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLeaderboardResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get leaderboard - All time user stats
     */
    async leaderboardControllerGetLeaderboardV1(requestParameters: LeaderboardControllerGetLeaderboardV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLeaderboardResponseDto> {
        const response = await this.leaderboardControllerGetLeaderboardV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Initialize season scheduled weeks for a given sport
     */
    async leaderboardControllerInitializeWeeksV1Raw(requestParameters: LeaderboardControllerInitializeWeeksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardControllerInitializeWeeksV1200Response>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling leaderboardControllerInitializeWeeksV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/leaderboard/init-weeks/{sport}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardControllerInitializeWeeksV1200ResponseFromJSON(jsonValue));
    }

    /**
     * Initialize season scheduled weeks for a given sport
     */
    async leaderboardControllerInitializeWeeksV1(requestParameters: LeaderboardControllerInitializeWeeksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardControllerInitializeWeeksV1200Response> {
        const response = await this.leaderboardControllerInitializeWeeksV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const LeaderboardControllerInitializeWeeksV1SportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type LeaderboardControllerInitializeWeeksV1SportEnum = typeof LeaderboardControllerInitializeWeeksV1SportEnum[keyof typeof LeaderboardControllerInitializeWeeksV1SportEnum];
