/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  GetAllMatches404Response,
  Odds,
} from '../models/index.js';
import {
    GetAllMatches404ResponseFromJSON,
    GetAllMatches404ResponseToJSON,
    OddsFromJSON,
    OddsToJSON,
} from '../models/index.js';

export interface FetchRequest {
    sport: FetchSportEnum;
}

export interface FindByIdRequest {
    id: string;
}

/**
 * OddsApi - interface
 * 
 * @export
 * @interface OddsApiInterface
 */
export interface OddsApiInterface {
    /**
     * The service this method utilizes is set on a daily schedule. This endpoint exists to manually trigger the process.
     * @summary Fetch and store odds for a sport
     * @param {'nba' | 'nfl'} sport Sport to fetch odds for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OddsApiInterface
     */
    fetchRaw(requestParameters: FetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * The service this method utilizes is set on a daily schedule. This endpoint exists to manually trigger the process.
     * Fetch and store odds for a sport
     */
    fetch(requestParameters: FetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Find odds by game ID
     * @param {string} id Game ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OddsApiInterface
     */
    findByIdRaw(requestParameters: FindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Odds>>;

    /**
     * Find odds by game ID
     */
    findById(requestParameters: FindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Odds>;

}

/**
 * 
 */
export class OddsApi extends runtime.BaseAPI implements OddsApiInterface {

    /**
     * The service this method utilizes is set on a daily schedule. This endpoint exists to manually trigger the process.
     * Fetch and store odds for a sport
     */
    async fetchRaw(requestParameters: FetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling fetch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/odds/fetch/{sport}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The service this method utilizes is set on a daily schedule. This endpoint exists to manually trigger the process.
     * Fetch and store odds for a sport
     */
    async fetch(requestParameters: FetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.fetchRaw(requestParameters, initOverrides);
    }

    /**
     * Find odds by game ID
     */
    async findByIdRaw(requestParameters: FindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Odds>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling findById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/odds/game/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OddsFromJSON(jsonValue));
    }

    /**
     * Find odds by game ID
     */
    async findById(requestParameters: FindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Odds> {
        const response = await this.findByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const FetchSportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type FetchSportEnum = typeof FetchSportEnum[keyof typeof FetchSportEnum];
