/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ProcessedPropDto,
  PropDto,
  SetPropResultDto,
  SetPropResultResponseDto,
} from '../models/index.js';
import {
    ProcessedPropDtoFromJSON,
    ProcessedPropDtoToJSON,
    PropDtoFromJSON,
    PropDtoToJSON,
    SetPropResultDtoFromJSON,
    SetPropResultDtoToJSON,
    SetPropResultResponseDtoFromJSON,
    SetPropResultResponseDtoToJSON,
} from '../models/index.js';

export interface GetPropRequest {
    marketId?: number;
    outcomeUuid?: string;
}

export interface PropsControllerGetAvailablePropsV1Request {
    sport: string;
}

export interface PropsControllerGetProcessedPropsV1Request {
    sport: PropsControllerGetProcessedPropsV1SportEnum;
    count?: number;
}

export interface PropsControllerGetRandomPropV1Request {
    sport: PropsControllerGetRandomPropV1SportEnum;
    count?: number;
}

export interface PropsControllerGetRandomPropsV1Request {
    sport: PropsControllerGetRandomPropsV1SportEnum;
    count?: number;
}

export interface PropsControllerSetPropResultV1Request {
    setPropResultDto: SetPropResultDto;
}

/**
 * PropsApi - interface
 * 
 * @export
 * @interface PropsApiInterface
 */
export interface PropsApiInterface {
    /**
     * Returns a prop from Goracle by its market_id or outcome_uuid. Market ID groups related outcomes together (e.g., Over/Under pairs share the same market_id). If market_id is provided, the system queries predictions to find an associated outcome_uuid, then fetches the full market details from Goracle. If outcome_uuid is provided, it fetches directly. Either market_id or outcome_uuid must be provided. Response contains all outcomes in the market along with event context information.
     * @summary Get a prop by market ID or outcome UUID
     * @param {number} [marketId] Market ID from Goracle - used to retrieve a prop by its market identifier. All outcomes in a market share the same market_id. If provided, the system queries predictions to find an associated outcome_uuid, then fetches the full market details.
     * @param {string} [outcomeUuid] Outcome UUID from Goracle - used to retrieve a prop by its outcome identifier. Can be used as an alternative to market_id. Either market_id or outcome_uuid must be provided.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    getPropRaw(requestParameters: GetPropRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropDto>>;

    /**
     * Returns a prop from Goracle by its market_id or outcome_uuid. Market ID groups related outcomes together (e.g., Over/Under pairs share the same market_id). If market_id is provided, the system queries predictions to find an associated outcome_uuid, then fetches the full market details from Goracle. If outcome_uuid is provided, it fetches directly. Either market_id or outcome_uuid must be provided. Response contains all outcomes in the market along with event context information.
     * Get a prop by market ID or outcome UUID
     */
    getProp(requestParameters: GetPropRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropDto>;

    /**
     * Returns ALL available props for caching purposes. No random sampling, no count limit. Used by Pluto to cache all available props for autocomplete functionality.
     * @summary Get all available props for a sport (no count limit)
     * @param {string} sport 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    propsControllerGetAvailablePropsV1Raw(requestParameters: PropsControllerGetAvailablePropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PropDto>>>;

    /**
     * Returns ALL available props for caching purposes. No random sampling, no count limit. Used by Pluto to cache all available props for autocomplete functionality.
     * Get all available props for a sport (no count limit)
     */
    propsControllerGetAvailablePropsV1(requestParameters: PropsControllerGetAvailablePropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PropDto>>;

    /**
     * Returns paired player props (over/under) ready for client consumption. Goracle returns all available outcomes; Khronos applies comprehensive filtering: Excludes h2h, spreads, totals, team_totals, and anytime touchdown markets. Groups outcomes into Over/Under pairs. Applies minimum odds filter (>= -150 American odds). Limits to 1-2 props per event for variety. Each returned object contains both over and under outcomes in a denormalized structure. No pairing logic needed on client side - each prop is self-contained.
     * @summary Get paired player props ready for predictions
     * @param {'nba' | 'nfl'} sport Sport key (nba or nfl)
     * @param {number} [count] Number of random props to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    propsControllerGetProcessedPropsV1Raw(requestParameters: PropsControllerGetProcessedPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessedPropDto>>>;

    /**
     * Returns paired player props (over/under) ready for client consumption. Goracle returns all available outcomes; Khronos applies comprehensive filtering: Excludes h2h, spreads, totals, team_totals, and anytime touchdown markets. Groups outcomes into Over/Under pairs. Applies minimum odds filter (>= -150 American odds). Limits to 1-2 props per event for variety. Each returned object contains both over and under outcomes in a denormalized structure. No pairing logic needed on client side - each prop is self-contained.
     * Get paired player props ready for predictions
     */
    propsControllerGetProcessedPropsV1(requestParameters: PropsControllerGetProcessedPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessedPropDto>>;

    /**
     * Returns a single random prop. Used by admins to swap individual props.
     * @summary Get a single random prop
     * @param {'nba' | 'nfl'} sport Sport key (nba or nfl)
     * @param {number} [count] Number of random props to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    propsControllerGetRandomPropV1Raw(requestParameters: PropsControllerGetRandomPropV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropDto>>;

    /**
     * Returns a single random prop. Used by admins to swap individual props.
     * Get a single random prop
     */
    propsControllerGetRandomPropV1(requestParameters: PropsControllerGetRandomPropV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropDto>;

    /**
     * Returns random props (outcomes) from Goracle for a specific sport. Used by Pluto to display daily props.
     * @summary Get random props for betting
     * @param {'nba' | 'nfl'} sport Sport key (nba or nfl)
     * @param {number} [count] Number of random props to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    propsControllerGetRandomPropsV1Raw(requestParameters: PropsControllerGetRandomPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PropDto>>>;

    /**
     * Returns random props (outcomes) from Goracle for a specific sport. Used by Pluto to display daily props.
     * Get random props for betting
     */
    propsControllerGetRandomPropsV1(requestParameters: PropsControllerGetRandomPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PropDto>>;

    /**
     * Allows staff to manually set the result of a prop (outcome), triggering prediction processing and leaderboard updates. The propId is the outcome_uuid from Goracle.
     * @summary Manually set prop result
     * @param {SetPropResultDto} setPropResultDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropsApiInterface
     */
    propsControllerSetPropResultV1Raw(requestParameters: PropsControllerSetPropResultV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetPropResultResponseDto>>;

    /**
     * Allows staff to manually set the result of a prop (outcome), triggering prediction processing and leaderboard updates. The propId is the outcome_uuid from Goracle.
     * Manually set prop result
     */
    propsControllerSetPropResultV1(requestParameters: PropsControllerSetPropResultV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetPropResultResponseDto>;

}

/**
 * 
 */
export class PropsApi extends runtime.BaseAPI implements PropsApiInterface {

    /**
     * Returns a prop from Goracle by its market_id or outcome_uuid. Market ID groups related outcomes together (e.g., Over/Under pairs share the same market_id). If market_id is provided, the system queries predictions to find an associated outcome_uuid, then fetches the full market details from Goracle. If outcome_uuid is provided, it fetches directly. Either market_id or outcome_uuid must be provided. Response contains all outcomes in the market along with event context information.
     * Get a prop by market ID or outcome UUID
     */
    async getPropRaw(requestParameters: GetPropRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropDto>> {
        const queryParameters: any = {};

        if (requestParameters['marketId'] != null) {
            queryParameters['market_id'] = requestParameters['marketId'];
        }

        if (requestParameters['outcomeUuid'] != null) {
            queryParameters['outcome_uuid'] = requestParameters['outcomeUuid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/props`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PropDtoFromJSON(jsonValue));
    }

    /**
     * Returns a prop from Goracle by its market_id or outcome_uuid. Market ID groups related outcomes together (e.g., Over/Under pairs share the same market_id). If market_id is provided, the system queries predictions to find an associated outcome_uuid, then fetches the full market details from Goracle. If outcome_uuid is provided, it fetches directly. Either market_id or outcome_uuid must be provided. Response contains all outcomes in the market along with event context information.
     * Get a prop by market ID or outcome UUID
     */
    async getProp(requestParameters: GetPropRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropDto> {
        const response = await this.getPropRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns ALL available props for caching purposes. No random sampling, no count limit. Used by Pluto to cache all available props for autocomplete functionality.
     * Get all available props for a sport (no count limit)
     */
    async propsControllerGetAvailablePropsV1Raw(requestParameters: PropsControllerGetAvailablePropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PropDto>>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling propsControllerGetAvailablePropsV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/props/available/{sport}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PropDtoFromJSON));
    }

    /**
     * Returns ALL available props for caching purposes. No random sampling, no count limit. Used by Pluto to cache all available props for autocomplete functionality.
     * Get all available props for a sport (no count limit)
     */
    async propsControllerGetAvailablePropsV1(requestParameters: PropsControllerGetAvailablePropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PropDto>> {
        const response = await this.propsControllerGetAvailablePropsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns paired player props (over/under) ready for client consumption. Goracle returns all available outcomes; Khronos applies comprehensive filtering: Excludes h2h, spreads, totals, team_totals, and anytime touchdown markets. Groups outcomes into Over/Under pairs. Applies minimum odds filter (>= -150 American odds). Limits to 1-2 props per event for variety. Each returned object contains both over and under outcomes in a denormalized structure. No pairing logic needed on client side - each prop is self-contained.
     * Get paired player props ready for predictions
     */
    async propsControllerGetProcessedPropsV1Raw(requestParameters: PropsControllerGetProcessedPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessedPropDto>>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling propsControllerGetProcessedPropsV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/props/random/processed`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProcessedPropDtoFromJSON));
    }

    /**
     * Returns paired player props (over/under) ready for client consumption. Goracle returns all available outcomes; Khronos applies comprehensive filtering: Excludes h2h, spreads, totals, team_totals, and anytime touchdown markets. Groups outcomes into Over/Under pairs. Applies minimum odds filter (>= -150 American odds). Limits to 1-2 props per event for variety. Each returned object contains both over and under outcomes in a denormalized structure. No pairing logic needed on client side - each prop is self-contained.
     * Get paired player props ready for predictions
     */
    async propsControllerGetProcessedPropsV1(requestParameters: PropsControllerGetProcessedPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessedPropDto>> {
        const response = await this.propsControllerGetProcessedPropsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single random prop. Used by admins to swap individual props.
     * Get a single random prop
     */
    async propsControllerGetRandomPropV1Raw(requestParameters: PropsControllerGetRandomPropV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropDto>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling propsControllerGetRandomPropV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/props/random/single`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PropDtoFromJSON(jsonValue));
    }

    /**
     * Returns a single random prop. Used by admins to swap individual props.
     * Get a single random prop
     */
    async propsControllerGetRandomPropV1(requestParameters: PropsControllerGetRandomPropV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropDto> {
        const response = await this.propsControllerGetRandomPropV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns random props (outcomes) from Goracle for a specific sport. Used by Pluto to display daily props.
     * Get random props for betting
     */
    async propsControllerGetRandomPropsV1Raw(requestParameters: PropsControllerGetRandomPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PropDto>>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling propsControllerGetRandomPropsV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/props/random`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PropDtoFromJSON));
    }

    /**
     * Returns random props (outcomes) from Goracle for a specific sport. Used by Pluto to display daily props.
     * Get random props for betting
     */
    async propsControllerGetRandomPropsV1(requestParameters: PropsControllerGetRandomPropsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PropDto>> {
        const response = await this.propsControllerGetRandomPropsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows staff to manually set the result of a prop (outcome), triggering prediction processing and leaderboard updates. The propId is the outcome_uuid from Goracle.
     * Manually set prop result
     */
    async propsControllerSetPropResultV1Raw(requestParameters: PropsControllerSetPropResultV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetPropResultResponseDto>> {
        if (requestParameters['setPropResultDto'] == null) {
            throw new runtime.RequiredError(
                'setPropResultDto',
                'Required parameter "setPropResultDto" was null or undefined when calling propsControllerSetPropResultV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/props/result`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetPropResultDtoToJSON(requestParameters['setPropResultDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetPropResultResponseDtoFromJSON(jsonValue));
    }

    /**
     * Allows staff to manually set the result of a prop (outcome), triggering prediction processing and leaderboard updates. The propId is the outcome_uuid from Goracle.
     * Manually set prop result
     */
    async propsControllerSetPropResultV1(requestParameters: PropsControllerSetPropResultV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetPropResultResponseDto> {
        const response = await this.propsControllerSetPropResultV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const PropsControllerGetProcessedPropsV1SportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type PropsControllerGetProcessedPropsV1SportEnum = typeof PropsControllerGetProcessedPropsV1SportEnum[keyof typeof PropsControllerGetProcessedPropsV1SportEnum];
/**
 * @export
 */
export const PropsControllerGetRandomPropV1SportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type PropsControllerGetRandomPropV1SportEnum = typeof PropsControllerGetRandomPropV1SportEnum[keyof typeof PropsControllerGetRandomPropV1SportEnum];
/**
 * @export
 */
export const PropsControllerGetRandomPropsV1SportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type PropsControllerGetRandomPropsV1SportEnum = typeof PropsControllerGetRandomPropsV1SportEnum[keyof typeof PropsControllerGetRandomPropsV1SportEnum];
