/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  OverallStatsDto,
} from '../models/index.js';
import {
    OverallStatsDtoFromJSON,
    OverallStatsDtoToJSON,
} from '../models/index.js';

export interface GetOverallH2hBettingStatsRequest {
    userId: string;
}

/**
 * StatsApi - interface
 * 
 * @export
 * @interface StatsApiInterface
 */
export interface StatsApiInterface {
    /**
     * 
     * @summary Get overall H2H betting stats
     * @param {string} userId The ID of the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getOverallH2hBettingStatsRaw(requestParameters: GetOverallH2hBettingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverallStatsDto>>;

    /**
     * Get overall H2H betting stats
     */
    getOverallH2hBettingStats(requestParameters: GetOverallH2hBettingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverallStatsDto>;

}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI implements StatsApiInterface {

    /**
     * Get overall H2H betting stats
     */
    async getOverallH2hBettingStatsRaw(requestParameters: GetOverallH2hBettingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverallStatsDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getOverallH2hBettingStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/stats/overall/h2h/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverallStatsDtoFromJSON(jsonValue));
    }

    /**
     * Get overall H2H betting stats
     */
    async getOverallH2hBettingStats(requestParameters: GetOverallH2hBettingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverallStatsDto> {
        const response = await this.getOverallH2hBettingStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
