/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  OutcomeSettledWebhookDto,
  WebhookAcceptedResponseDto,
  WebhookHealthResponseDto,
} from '../models/index.js';
import {
    OutcomeSettledWebhookDtoFromJSON,
    OutcomeSettledWebhookDtoToJSON,
    WebhookAcceptedResponseDtoFromJSON,
    WebhookAcceptedResponseDtoToJSON,
    WebhookHealthResponseDtoFromJSON,
    WebhookHealthResponseDtoToJSON,
} from '../models/index.js';

export interface WebhooksControllerHandleOutcomeSettledV1Request {
    outcomeSettledWebhookDto: OutcomeSettledWebhookDto;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * Webhook endpoint for Goracle to notify Khronos when an outcome has been settled. Processes predictions asynchronously. Uses standard x-api-key authentication.
     * @summary Receive outcome settlement from Goracle
     * @param {OutcomeSettledWebhookDto} outcomeSettledWebhookDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerHandleOutcomeSettledV1Raw(requestParameters: WebhooksControllerHandleOutcomeSettledV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookAcceptedResponseDto>>;

    /**
     * Webhook endpoint for Goracle to notify Khronos when an outcome has been settled. Processes predictions asynchronously. Uses standard x-api-key authentication.
     * Receive outcome settlement from Goracle
     */
    webhooksControllerHandleOutcomeSettledV1(requestParameters: WebhooksControllerHandleOutcomeSettledV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookAcceptedResponseDto>;

    /**
     * Simple endpoint for Goracle to verify it can reach Khronos and authenticate. Used on startup to test connectivity.
     * @summary Health check for webhook connectivity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerHealthCheckV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookHealthResponseDto>>;

    /**
     * Simple endpoint for Goracle to verify it can reach Khronos and authenticate. Used on startup to test connectivity.
     * Health check for webhook connectivity
     */
    webhooksControllerHealthCheckV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookHealthResponseDto>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Webhook endpoint for Goracle to notify Khronos when an outcome has been settled. Processes predictions asynchronously. Uses standard x-api-key authentication.
     * Receive outcome settlement from Goracle
     */
    async webhooksControllerHandleOutcomeSettledV1Raw(requestParameters: WebhooksControllerHandleOutcomeSettledV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookAcceptedResponseDto>> {
        if (requestParameters['outcomeSettledWebhookDto'] == null) {
            throw new runtime.RequiredError(
                'outcomeSettledWebhookDto',
                'Required parameter "outcomeSettledWebhookDto" was null or undefined when calling webhooksControllerHandleOutcomeSettledV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/khronos/v1/webhooks/goracle/outcome-settled`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OutcomeSettledWebhookDtoToJSON(requestParameters['outcomeSettledWebhookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookAcceptedResponseDtoFromJSON(jsonValue));
    }

    /**
     * Webhook endpoint for Goracle to notify Khronos when an outcome has been settled. Processes predictions asynchronously. Uses standard x-api-key authentication.
     * Receive outcome settlement from Goracle
     */
    async webhooksControllerHandleOutcomeSettledV1(requestParameters: WebhooksControllerHandleOutcomeSettledV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookAcceptedResponseDto> {
        const response = await this.webhooksControllerHandleOutcomeSettledV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simple endpoint for Goracle to verify it can reach Khronos and authenticate. Used on startup to test connectivity.
     * Health check for webhook connectivity
     */
    async webhooksControllerHealthCheckV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookHealthResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/webhooks/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookHealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Simple endpoint for Goracle to verify it can reach Khronos and authenticate. Used on startup to test connectivity.
     * Health check for webhook connectivity
     */
    async webhooksControllerHealthCheckV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookHealthResponseDto> {
        const response = await this.webhooksControllerHealthCheckV1Raw(initOverrides);
        return await response.value();
    }

}
