/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  SeasonWeekDto,
} from '../models/index.js';
import {
    SeasonWeekDtoFromJSON,
    SeasonWeekDtoToJSON,
} from '../models/index.js';

export interface GetCurrentWeekRequest {
    sport: string;
}

/**
 * WeekManagerApi - interface
 * 
 * @export
 * @interface WeekManagerApiInterface
 */
export interface WeekManagerApiInterface {
    /**
     * 
     * @summary Get the current week number for a sport
     * @param {string} sport The sport to get the current week for (e.g., \&quot;nfl\&quot; or \&quot;nba\&quot;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeekManagerApiInterface
     */
    getCurrentWeekRaw(requestParameters: GetCurrentWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeasonWeekDto>>;

    /**
     * Get the current week number for a sport
     */
    getCurrentWeek(requestParameters: GetCurrentWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeasonWeekDto>;

}

/**
 * 
 */
export class WeekManagerApi extends runtime.BaseAPI implements WeekManagerApiInterface {

    /**
     * Get the current week number for a sport
     */
    async getCurrentWeekRaw(requestParameters: GetCurrentWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeasonWeekDto>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getCurrentWeek().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/khronos/v1/week-manager/getCurrentWeek`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeasonWeekDtoFromJSON(jsonValue));
    }

    /**
     * Get the current week number for a sport
     */
    async getCurrentWeek(requestParameters: GetCurrentWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeasonWeekDto> {
        const response = await this.getCurrentWeekRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
