// Generated from scripts/matchup-assets/teams.json. Run assets:registry after edits.
export const TEAMS_REVISION =
	'0c782ca463828e97e8c08523b6b2fa40e5ecc90c4074a4981b8b02ef520b6841'
export const TEAM_REGISTRY = {
	nba: [
		{
			id: '76ers',
			name: 'Philadelphia 76ers',
			aliases: ['76ers'],
			colors: ['#006BB6', '#ED174C', '#002B5C'],
		},
		{
			id: 'blazers',
			name: 'Portland Trail Blazers',
			aliases: ['Blazers', 'Trail Blazers', 'TrailBlazers'],
			colors: ['#E03A3E', '#000000', '#FFFFFF'],
		},
		{
			id: 'bucks',
			name: 'Milwaukee Bucks',
			aliases: ['Bucks'],
			colors: ['#00471B', '#EEE1C6', '#000000'],
		},
		{
			id: 'bulls',
			name: 'Chicago Bulls',
			aliases: ['Bulls'],
			colors: ['#CE1141', '#000000', '#000000'],
		},
		{
			id: 'cavaliers',
			name: 'Cleveland Cavaliers',
			aliases: ['Cavaliers'],
			colors: ['#860038', '#041E42', '#000000'],
		},
		{
			id: 'celtics',
			name: 'Boston Celtics',
			aliases: ['Celtics'],
			colors: ['#007A33', '#BA9653', '#000000'],
		},
		{
			id: 'clippers',
			name: 'LA Clippers',
			aliases: ['Clippers'],
			colors: ['#ED174C', '#006BB6', '#000000'],
		},
		{
			id: 'grizzlies',
			name: 'Memphis Grizzlies',
			aliases: ['Grizzlies'],
			colors: ['#5D76A9', '#12173F', '#000000'],
		},
		{
			id: 'hawks',
			name: 'Atlanta Hawks',
			aliases: ['Hawks'],
			colors: ['#E03A3E', '#C1D32F', '#000000'],
		},
		{
			id: 'heat',
			name: 'Miami Heat',
			aliases: ['Heat'],
			colors: ['#98002E', '#F9A01B', '#000000'],
		},
		{
			id: 'hornets',
			name: 'Charlotte Hornets',
			aliases: ['Hornets'],
			colors: ['#1D1160', '#00788C', '#000000'],
		},
		{
			id: 'jazz',
			name: 'Utah Jazz',
			aliases: ['Jazz'],
			colors: ['#002B5C', '#00471B', '#F9A01B', '#FFFFFF'],
		},
		{
			id: 'kings',
			name: 'Sacramento Kings',
			aliases: ['Kings'],
			colors: ['#5A2D81', '#63727A', '#BEC0C2'],
		},
		{
			id: 'knicks',
			name: 'New York Knicks',
			aliases: ['Knicks'],
			colors: ['#006BB6', '#F58426', '#BEC0C2'],
		},
		{
			id: 'lakers',
			name: 'Los Angeles Lakers',
			aliases: ['Lakers'],
			colors: ['#552583', '#FDB927', '#000000'],
		},
		{
			id: 'magic',
			name: 'Orlando Magic',
			aliases: ['Magic'],
			colors: ['#0077C0', '#C4CED4', '#000000'],
		},
		{
			id: 'mavericks',
			name: 'Dallas Mavericks',
			aliases: ['Mavericks'],
			colors: ['#00538C', '#B8C4CA', '#000000'],
		},
		{
			id: 'nets',
			name: 'Brooklyn Nets',
			aliases: ['Nets'],
			colors: ['#000000', '#FFFFFF', '#000000'],
		},
		{
			id: 'nuggets',
			name: 'Denver Nuggets',
			aliases: ['Nuggets'],
			colors: ['#0E2240', '#FEC524', '#000000'],
		},
		{
			id: 'pacers',
			name: 'Indiana Pacers',
			aliases: ['Pacers'],
			colors: ['#002D62', '#FDBB30', '#000000'],
		},
		{
			id: 'pelicans',
			name: 'New Orleans Pelicans',
			aliases: ['Pelicans'],
			colors: ['#002B5C', '#B4975A', '#E31837', '#85714D'],
		},
		{
			id: 'pistons',
			name: 'Detroit Pistons',
			aliases: ['Pistons'],
			colors: ['#C8102E', '#1D42BA', '#000000'],
		},
		{
			id: 'raptors',
			name: 'Toronto Raptors',
			aliases: ['Raptors'],
			colors: ['#CE1141', '#000000', '#A1A1A4', '#B4975A'],
		},
		{
			id: 'rockets',
			name: 'Houston Rockets',
			aliases: ['Rockets'],
			colors: ['#CE1141', '#000000', '#000000'],
		},
		{
			id: 'spurs',
			name: 'San Antonio Spurs',
			aliases: ['Spurs'],
			colors: ['#000000', '#C4CED4', '#BAC3C9', '#AC1A2F'],
		},
		{
			id: 'suns',
			name: 'Phoenix Suns',
			aliases: ['Suns'],
			colors: ['#1D1160', '#E56020', '#63727A'],
		},
		{
			id: 'thunder',
			name: 'Oklahoma City Thunder',
			aliases: ['Thunder'],
			colors: ['#007AC1', '#F05133', '#002D62', '#EF3B24', '#C4CED4'],
		},
		{
			id: 'timberwolves',
			name: 'Minnesota Timberwolves',
			aliases: ['Timberwolves'],
			colors: ['#0C2340', '#236192', '#000000'],
		},
		{
			id: 'warriors',
			name: 'Golden State Warriors',
			aliases: ['Warriors'],
			colors: ['#1D428A', '#FFC72C', '#000000'],
		},
		{
			id: 'wizards',
			name: 'Washington Wizards',
			aliases: ['Wizards'],
			colors: ['#002B5C', '#E31837', '#C4CED4', '#002244'],
		},
	],
	nfl: [
		{
			id: '49ers',
			name: 'San Francisco 49ers',
			aliases: ['49ers'],
			colors: ['#AA0000', '#B3995D'],
		},
		{
			id: 'bears',
			name: 'Chicago Bears',
			aliases: ['Bears'],
			colors: ['#0B162A', '#C83803'],
		},
		{
			id: 'bengals',
			name: 'Cincinnati Bengals',
			aliases: ['Bengals'],
			colors: ['#FB4F14', '#000000'],
		},
		{
			id: 'bills',
			name: 'Buffalo Bills',
			aliases: ['Bills'],
			colors: ['#00338D', '#C60C30'],
		},
		{
			id: 'broncos',
			name: 'Denver Broncos',
			aliases: ['Broncos'],
			colors: ['#FB4F14', '#002244'],
		},
		{
			id: 'browns',
			name: 'Cleveland Browns',
			aliases: ['Browns'],
			colors: ['#311D00', '#FF3C00'],
		},
		{
			id: 'buccaneers',
			name: 'Tampa Bay Buccaneers',
			aliases: ['Buccaneers'],
			colors: ['#D50A0A', '#34302B', '#FF7900', '#B1BABF', '#FFFFFF'],
		},
		{
			id: 'cardinals',
			name: 'Arizona Cardinals',
			aliases: ['Cardinals'],
			colors: ['#97233F', '#000000'],
		},
		{
			id: 'chargers',
			name: 'Los Angeles Chargers',
			aliases: ['Chargers'],
			colors: ['#0072C6', '#FFC20E', '#000000'],
		},
		{
			id: 'chiefs',
			name: 'Kansas City Chiefs',
			aliases: ['Chiefs'],
			colors: ['#E31837', '#FFB81C'],
		},
		{
			id: 'colts',
			name: 'Indianapolis Colts',
			aliases: ['Colts'],
			colors: ['#002C5F', '#A5ACAF', '#FFFFFF'],
		},
		{
			id: 'commanders',
			name: 'Washington Commanders',
			aliases: [
				'Commanders',
				'Washington Redskins',
				'Redskins',
				'Washington Football Team',
			],
			colors: ['#773141', '#FFB612', '#FFFFFF'],
		},
		{
			id: 'cowboys',
			name: 'Dallas Cowboys',
			aliases: ['Cowboys'],
			colors: ['#003594', '#041E42', '#A5ACAF'],
		},
		{
			id: 'dolphins',
			name: 'Miami Dolphins',
			aliases: ['Dolphins'],
			colors: ['#008E97', '#F58220', '#005778', '#FB4F14'],
		},
		{
			id: 'eagles',
			name: 'Philadelphia Eagles',
			aliases: ['Eagles'],
			colors: ['#004C54', '#A5ACAF', '#000000', '#FFD814'],
		},
		{
			id: 'falcons',
			name: 'Atlanta Falcons',
			aliases: ['Falcons'],
			colors: ['#A71930', '#000000', '#A5ACAF'],
		},
		{
			id: 'giants',
			name: 'New York Giants',
			aliases: ['Giants'],
			colors: ['#0B2265', '#A71930', '#A5ACAF'],
		},
		{
			id: 'jaguars',
			name: 'Jacksonville Jaguars',
			aliases: ['Jaguars'],
			colors: ['#006778', '#D7A22A', '#9F792C', '#000000'],
		},
		{
			id: 'jets',
			name: 'New York Jets',
			aliases: ['Jets'],
			colors: ['#0C371D', '#FFFFFF'],
		},
		{
			id: 'lions',
			name: 'Detroit Lions',
			aliases: ['Lions'],
			colors: ['#0076B6', '#B0B7BC', '#000000'],
		},
		{
			id: 'packers',
			name: 'Green Bay Packers',
			aliases: ['Packers'],
			colors: ['#203731', '#FFB612'],
		},
		{
			id: 'panthers',
			name: 'Carolina Panthers',
			aliases: ['Panthers'],
			colors: ['#0085CA', '#101820', '#A5ACAF'],
		},
		{
			id: 'patriots',
			name: 'New England Patriots',
			aliases: ['Patriots'],
			colors: ['#002244', '#C60C30', '#B0B7BC', '#FFFFFF'],
		},
		{
			id: 'raiders',
			name: 'Las Vegas Raiders',
			aliases: ['Raiders'],
			colors: ['#000000', '#A5ACAF', '#C4C9CC'],
		},
		{
			id: 'rams',
			name: 'Los Angeles Rams',
			aliases: ['Rams'],
			colors: ['#002244', '#869397', '#FFFFFF'],
		},
		{
			id: 'ravens',
			name: 'Baltimore Ravens',
			aliases: ['Ravens'],
			colors: ['#241773', '#9E7C0C', '#000000'],
		},
		{
			id: 'saints',
			name: 'New Orleans Saints',
			aliases: ['Saints'],
			colors: ['#D3BC8D', '#000000'],
		},
		{
			id: 'seahawks',
			name: 'Seattle Seahawks',
			aliases: ['Seahawks'],
			colors: ['#002244', '#69BE28', '#A5ACAF'],
		},
		{
			id: 'steelers',
			name: 'Pittsburgh Steelers',
			aliases: ['Steelers'],
			colors: ['#101820', '#FFB81C'],
		},
		{
			id: 'texans',
			name: 'Houston Texans',
			aliases: ['Texans'],
			colors: ['#03202F', '#A71930', '#FFFFFF'],
		},
		{
			id: 'titans',
			name: 'Tennessee Titans',
			aliases: ['Titans'],
			colors: ['#0C2340', '#4B92DB', '#C8102E', '#B3995D'],
		},
		{
			id: 'vikings',
			name: 'Minnesota Vikings',
			aliases: ['Vikings'],
			colors: ['#4F2683', '#FFC62F', '#FFFFFF'],
		},
	],
} as const
