/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetslipPending } from './BetslipPending.js';
import {
    BetslipPendingFromJSON,
    BetslipPendingFromJSONTyped,
    BetslipPendingToJSON,
    BetslipPendingToJSONTyped,
} from './BetslipPending.js';
import type { Monies } from './Monies.js';
import {
    MoniesFromJSON,
    MoniesFromJSONTyped,
    MoniesToJSON,
    MoniesToJSONTyped,
} from './Monies.js';
import type { XpEntity } from './XpEntity.js';
import {
    XpEntityFromJSON,
    XpEntityFromJSONTyped,
    XpEntityToJSON,
    XpEntityToJSONTyped,
} from './XpEntity.js';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * User ID
     * @type {string}
     * @memberof Account
     */
    userid: string;
    /**
     * Last claim time
     * @type {string}
     * @memberof Account
     */
    lastclaimtime: string | null;
    /**
     * Registration date
     * @type {string}
     * @memberof Account
     */
    registerdate: string;
    /**
     * 
     * @type {Monies}
     * @memberof Account
     */
    monies: Monies;
    /**
     * 
     * @type {XpEntity}
     * @memberof Account
     */
    xp: XpEntity;
    /**
     * 
     * @type {BetslipPending}
     * @memberof Account
     */
    pending_betslip: BetslipPending | null;
    /**
     * Claims today
     * @type {number}
     * @memberof Account
     */
    claimstoday: number;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('lastclaimtime' in value) || value['lastclaimtime'] === undefined) return false;
    if (!('registerdate' in value) || value['registerdate'] === undefined) return false;
    if (!('monies' in value) || value['monies'] === undefined) return false;
    if (!('xp' in value) || value['xp'] === undefined) return false;
    if (!('pending_betslip' in value) || value['pending_betslip'] === undefined) return false;
    if (!('claimstoday' in value) || value['claimstoday'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'lastclaimtime': json['lastclaimtime'],
        'registerdate': json['registerdate'],
        'monies': MoniesFromJSON(json['monies']),
        'xp': XpEntityFromJSON(json['xp']),
        'pending_betslip': BetslipPendingFromJSON(json['pending_betslip']),
        'claimstoday': json['claimstoday'],
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
        'lastclaimtime': value['lastclaimtime'],
        'registerdate': value['registerdate'],
        'monies': MoniesToJSON(value['monies']),
        'xp': XpEntityToJSON(value['xp']),
        'pending_betslip': BetslipPendingToJSON(value['pending_betslip']),
        'claimstoday': value['claimstoday'],
    };
}

