/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActiveOutcomePropDto
 */
export interface ActiveOutcomePropDto {
    /**
     * Primary outcome UUID (prop ID) - used for display/formatter compatibility. For markets with market_id, this is one of the UUIDs in outcome_uuids.
     * @type {string}
     * @memberof ActiveOutcomePropDto
     */
    outcome_uuid: string;
    /**
     * Market key (e.g., player_points, h2h)
     * @type {string}
     * @memberof ActiveOutcomePropDto
     */
    market_key: string;
    /**
     * Market ID from Goracle - groups related outcomes together (e.g., Over/Under pairs share the same market_id). Null for legacy data.
     * @type {number}
     * @memberof ActiveOutcomePropDto
     */
    market_id?: number | null;
    /**
     * Array of all outcome UUIDs in this market. For markets with market_id, contains all outcomes (e.g., Over and Under). For legacy data without market_id, contains only the primary outcome_uuid.
     * @type {Array<string>}
     * @memberof ActiveOutcomePropDto
     */
    outcome_uuids?: Array<string>;
    /**
     * Prop description (e.g., player name for player props)
     * @type {string}
     * @memberof ActiveOutcomePropDto
     */
    description?: string;
    /**
     * Point value (e.g., 25.5 for over/under)
     * @type {number}
     * @memberof ActiveOutcomePropDto
     */
    point?: number;
    /**
     * Total number of pending predictions on this prop
     * @type {number}
     * @memberof ActiveOutcomePropDto
     */
    prediction_count: number;
}

/**
 * Check if a given object implements the ActiveOutcomePropDto interface.
 */
export function instanceOfActiveOutcomePropDto(value: object): value is ActiveOutcomePropDto {
    if (!('outcome_uuid' in value) || value['outcome_uuid'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    if (!('prediction_count' in value) || value['prediction_count'] === undefined) return false;
    return true;
}

export function ActiveOutcomePropDtoFromJSON(json: any): ActiveOutcomePropDto {
    return ActiveOutcomePropDtoFromJSONTyped(json, false);
}

export function ActiveOutcomePropDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveOutcomePropDto {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome_uuid': json['outcome_uuid'],
        'market_key': json['market_key'],
        'market_id': json['market_id'] == null ? undefined : json['market_id'],
        'outcome_uuids': json['outcome_uuids'] == null ? undefined : json['outcome_uuids'],
        'description': json['description'] == null ? undefined : json['description'],
        'point': json['point'] == null ? undefined : json['point'],
        'prediction_count': json['prediction_count'],
    };
}

export function ActiveOutcomePropDtoToJSON(json: any): ActiveOutcomePropDto {
    return ActiveOutcomePropDtoToJSONTyped(json, false);
}

export function ActiveOutcomePropDtoToJSONTyped(value?: ActiveOutcomePropDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome_uuid': value['outcome_uuid'],
        'market_key': value['market_key'],
        'market_id': value['market_id'],
        'outcome_uuids': value['outcome_uuids'],
        'description': value['description'],
        'point': value['point'],
        'prediction_count': value['prediction_count'],
    };
}

