/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AnnouncementDto
 */
export interface AnnouncementDto {
    /**
     * 
     * @type {string}
     * @memberof AnnouncementDto
     */
    text: string;
    /**
     * 
     * @type {boolean}
     * @memberof AnnouncementDto
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the AnnouncementDto interface.
 */
export function instanceOfAnnouncementDto(value: object): value is AnnouncementDto {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function AnnouncementDtoFromJSON(json: any): AnnouncementDto {
    return AnnouncementDtoFromJSONTyped(json, false);
}

export function AnnouncementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'isActive': json['isActive'],
    };
}

export function AnnouncementDtoToJSON(json: any): AnnouncementDto {
    return AnnouncementDtoToJSONTyped(json, false);
}

export function AnnouncementDtoToJSONTyped(value?: AnnouncementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'isActive': value['isActive'],
    };
}

