/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MatchDetailDto } from './MatchDetailDto.js';
import {
    MatchDetailDtoFromJSON,
    MatchDetailDtoFromJSONTyped,
    MatchDetailDtoToJSON,
    MatchDetailDtoToJSONTyped,
} from './MatchDetailDto.js';

/**
 * 
 * @export
 * @interface BetslipWithAggregationDTO
 */
export interface BetslipWithAggregationDTO {
    /**
     * The user ID associated with the betslip
     * @type {string}
     * @memberof BetslipWithAggregationDTO
     */
    userid: string;
    /**
     * The team (or player) chosen in the bet
     * @type {string}
     * @memberof BetslipWithAggregationDTO
     */
    team: string;
    /**
     * The amount bet
     * @type {number}
     * @memberof BetslipWithAggregationDTO
     */
    amount: number;
    /**
     * The profit from the bet, if applicable
     * @type {number}
     * @memberof BetslipWithAggregationDTO
     */
    profit: number | null;
    /**
     * The total payout from the bet, if applicable
     * @type {number}
     * @memberof BetslipWithAggregationDTO
     */
    payout: number | null;
    /**
     * Opposing team in the match the user has bet on
     * @type {string}
     * @memberof BetslipWithAggregationDTO
     */
    opponent: string;
    /**
     * Date of the match the user has bet on
     * @type {string}
     * @memberof BetslipWithAggregationDTO
     */
    dateofmatchup: string;
    /**
     * Match details
     * @type {MatchDetailDto}
     * @memberof BetslipWithAggregationDTO
     */
    match: MatchDetailDto;
    /**
     * Flag indicating if this is a newly created account
     * @type {boolean}
     * @memberof BetslipWithAggregationDTO
     */
    isNewUser?: boolean;
}

/**
 * Check if a given object implements the BetslipWithAggregationDTO interface.
 */
export function instanceOfBetslipWithAggregationDTO(value: object): value is BetslipWithAggregationDTO {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('profit' in value) || value['profit'] === undefined) return false;
    if (!('payout' in value) || value['payout'] === undefined) return false;
    if (!('opponent' in value) || value['opponent'] === undefined) return false;
    if (!('dateofmatchup' in value) || value['dateofmatchup'] === undefined) return false;
    if (!('match' in value) || value['match'] === undefined) return false;
    return true;
}

export function BetslipWithAggregationDTOFromJSON(json: any): BetslipWithAggregationDTO {
    return BetslipWithAggregationDTOFromJSONTyped(json, false);
}

export function BetslipWithAggregationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetslipWithAggregationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'team': json['team'],
        'amount': json['amount'],
        'profit': json['profit'],
        'payout': json['payout'],
        'opponent': json['opponent'],
        'dateofmatchup': json['dateofmatchup'],
        'match': MatchDetailDtoFromJSON(json['match']),
        'isNewUser': json['isNewUser'] == null ? undefined : json['isNewUser'],
    };
}

export function BetslipWithAggregationDTOToJSON(json: any): BetslipWithAggregationDTO {
    return BetslipWithAggregationDTOToJSONTyped(json, false);
}

export function BetslipWithAggregationDTOToJSONTyped(value?: BetslipWithAggregationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
        'team': value['team'],
        'amount': value['amount'],
        'profit': value['profit'],
        'payout': value['payout'],
        'opponent': value['opponent'],
        'dateofmatchup': value['dateofmatchup'],
        'match': MatchDetailDtoToJSON(value['match']),
        'isNewUser': value['isNewUser'],
    };
}

