/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetslipPending
 */
export interface BetslipPending {
    /**
     * User ID
     * @type {string}
     * @memberof BetslipPending
     */
    userid: string;
    /**
     * Pending bet amount
     * @type {number}
     * @memberof BetslipPending
     */
    amount: number;
    /**
     * Match start datetime
     * @type {Date}
     * @memberof BetslipPending
     */
    gamestart: Date;
}

/**
 * Check if a given object implements the BetslipPending interface.
 */
export function instanceOfBetslipPending(value: object): value is BetslipPending {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('gamestart' in value) || value['gamestart'] === undefined) return false;
    return true;
}

export function BetslipPendingFromJSON(json: any): BetslipPending {
    return BetslipPendingFromJSONTyped(json, false);
}

export function BetslipPendingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetslipPending {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'amount': json['amount'],
        'gamestart': (new Date(json['gamestart'])),
    };
}

export function BetslipPendingToJSON(json: any): BetslipPending {
    return BetslipPendingToJSONTyped(json, false);
}

export function BetslipPendingToJSONTyped(value?: BetslipPending | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
        'amount': value['amount'],
        'gamestart': ((value['gamestart']).toISOString()),
    };
}

