/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BettingLeaderboardEntity
 */
export interface BettingLeaderboardEntity {
    /**
     * Unique identifier for the leaderboard entry
     * @type {string}
     * @memberof BettingLeaderboardEntity
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof BettingLeaderboardEntity
     */
    user_id: string;
    /**
     * Total number of bets placed
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    total_bets: number;
    /**
     * Total number of winning bets
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    total_wins: number;
    /**
     * Total number of losing bets
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    total_losses: number;
    /**
     * Total profit from bets
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    total_profit: number;
    /**
     * Total amount wagered
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    total_wagered: number;
    /**
     * Win rate percentage
     * @type {number}
     * @memberof BettingLeaderboardEntity
     */
    win_rate: number;
    /**
     * Timestamp of last processed bet
     * @type {Date}
     * @memberof BettingLeaderboardEntity
     */
    last_bet_at: Date;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof BettingLeaderboardEntity
     */
    created_at: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof BettingLeaderboardEntity
     */
    updated_at: Date;
}

/**
 * Check if a given object implements the BettingLeaderboardEntity interface.
 */
export function instanceOfBettingLeaderboardEntity(value: object): value is BettingLeaderboardEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('total_bets' in value) || value['total_bets'] === undefined) return false;
    if (!('total_wins' in value) || value['total_wins'] === undefined) return false;
    if (!('total_losses' in value) || value['total_losses'] === undefined) return false;
    if (!('total_profit' in value) || value['total_profit'] === undefined) return false;
    if (!('total_wagered' in value) || value['total_wagered'] === undefined) return false;
    if (!('win_rate' in value) || value['win_rate'] === undefined) return false;
    if (!('last_bet_at' in value) || value['last_bet_at'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function BettingLeaderboardEntityFromJSON(json: any): BettingLeaderboardEntity {
    return BettingLeaderboardEntityFromJSONTyped(json, false);
}

export function BettingLeaderboardEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BettingLeaderboardEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'total_bets': json['total_bets'],
        'total_wins': json['total_wins'],
        'total_losses': json['total_losses'],
        'total_profit': json['total_profit'],
        'total_wagered': json['total_wagered'],
        'win_rate': json['win_rate'],
        'last_bet_at': (new Date(json['last_bet_at'])),
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function BettingLeaderboardEntityToJSON(json: any): BettingLeaderboardEntity {
    return BettingLeaderboardEntityToJSONTyped(json, false);
}

export function BettingLeaderboardEntityToJSONTyped(value?: BettingLeaderboardEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'total_bets': value['total_bets'],
        'total_wins': value['total_wins'],
        'total_losses': value['total_losses'],
        'total_profit': value['total_profit'],
        'total_wagered': value['total_wagered'],
        'win_rate': value['win_rate'],
        'last_bet_at': ((value['last_bet_at']).toISOString()),
        'created_at': ((value['created_at']).toISOString()),
        'updated_at': ((value['updated_at']).toISOString()),
    };
}

