/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MarketDataDto } from './MarketDataDto.js';
import {
    MarketDataDtoFromJSON,
    MarketDataDtoFromJSONTyped,
    MarketDataDtoToJSON,
    MarketDataDtoToJSONTyped,
} from './MarketDataDto.js';

/**
 * 
 * @export
 * @interface BookmakerDataDto
 */
export interface BookmakerDataDto {
    /**
     * Bookmaker key
     * @type {string}
     * @memberof BookmakerDataDto
     */
    key?: string;
    /**
     * Markets offered by this bookmaker
     * @type {Array<MarketDataDto>}
     * @memberof BookmakerDataDto
     */
    markets?: Array<MarketDataDto>;
}

/**
 * Check if a given object implements the BookmakerDataDto interface.
 */
export function instanceOfBookmakerDataDto(value: object): value is BookmakerDataDto {
    return true;
}

export function BookmakerDataDtoFromJSON(json: any): BookmakerDataDto {
    return BookmakerDataDtoFromJSONTyped(json, false);
}

export function BookmakerDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmakerDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'markets': json['markets'] == null ? undefined : ((json['markets'] as Array<any>).map(MarketDataDtoFromJSON)),
    };
}

export function BookmakerDataDtoToJSON(json: any): BookmakerDataDto {
    return BookmakerDataDtoToJSONTyped(json, false);
}

export function BookmakerDataDtoToJSONTyped(value?: BookmakerDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'markets': value['markets'] == null ? undefined : ((value['markets'] as Array<any>).map(MarketDataDtoToJSON)),
    };
}

