/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CancelBetslipResponseDto
 */
export interface CancelBetslipResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof CancelBetslipResponseDto
     */
    statusCode: number;
    /**
     * Success message
     * @type {string}
     * @memberof CancelBetslipResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the CancelBetslipResponseDto interface.
 */
export function instanceOfCancelBetslipResponseDto(value: object): value is CancelBetslipResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CancelBetslipResponseDtoFromJSON(json: any): CancelBetslipResponseDto {
    return CancelBetslipResponseDtoFromJSONTyped(json, false);
}

export function CancelBetslipResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelBetslipResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
    };
}

export function CancelBetslipResponseDtoToJSON(json: any): CancelBetslipResponseDto {
    return CancelBetslipResponseDtoToJSONTyped(json, false);
}

export function CancelBetslipResponseDtoToJSONTyped(value?: CancelBetslipResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

