/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Modified } from './Modified.js';
import {
    ModifiedFromJSON,
    ModifiedFromJSONTyped,
    ModifiedToJSON,
    ModifiedToJSONTyped,
} from './Modified.js';

/**
 * 
 * @export
 * @interface ChangeBetAmountResponseDto
 */
export interface ChangeBetAmountResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ChangeBetAmountResponseDto
     */
    statusCode: number;
    /**
     * Success message with balance information
     * @type {string}
     * @memberof ChangeBetAmountResponseDto
     */
    message: string;
    /**
     * Details of the modifications including new balance, profit, and payout
     * @type {Modified}
     * @memberof ChangeBetAmountResponseDto
     */
    modified: Modified;
}

/**
 * Check if a given object implements the ChangeBetAmountResponseDto interface.
 */
export function instanceOfChangeBetAmountResponseDto(value: object): value is ChangeBetAmountResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    return true;
}

export function ChangeBetAmountResponseDtoFromJSON(json: any): ChangeBetAmountResponseDto {
    return ChangeBetAmountResponseDtoFromJSONTyped(json, false);
}

export function ChangeBetAmountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeBetAmountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'modified': ModifiedFromJSON(json['modified']),
    };
}

export function ChangeBetAmountResponseDtoToJSON(json: any): ChangeBetAmountResponseDto {
    return ChangeBetAmountResponseDtoToJSONTyped(json, false);
}

export function ChangeBetAmountResponseDtoToJSONTyped(value?: ChangeBetAmountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'modified': ModifiedToJSON(value['modified']),
    };
}

