/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ChangeBetAmountDto
 */
export interface ChangeBetAmountDto {
    /**
     * 
     * @type {number}
     * @memberof ChangeBetAmountDto
     */
    newAmount: number;
    /**
     * 
     * @type {string}
     * @memberof ChangeBetAmountDto
     */
    userid: string;
}

/**
 * Check if a given object implements the ChangeBetAmountDto interface.
 */
export function instanceOfChangeBetAmountDto(value: object): value is ChangeBetAmountDto {
    if (!('newAmount' in value) || value['newAmount'] === undefined) return false;
    if (!('userid' in value) || value['userid'] === undefined) return false;
    return true;
}

export function ChangeBetAmountDtoFromJSON(json: any): ChangeBetAmountDto {
    return ChangeBetAmountDtoFromJSONTyped(json, false);
}

export function ChangeBetAmountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeBetAmountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'newAmount': json['newAmount'],
        'userid': json['userid'],
    };
}

export function ChangeBetAmountDtoToJSON(json: any): ChangeBetAmountDto {
    return ChangeBetAmountDtoToJSONTyped(json, false);
}

export function ChangeBetAmountDtoToJSONTyped(value?: ChangeBetAmountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newAmount': value['newAmount'],
        'userid': value['userid'],
    };
}

