/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CleanupStaleMatches200ResponseResults
 */
export interface CleanupStaleMatches200ResponseResults {
    /**
     * IDs of successfully archived matches
     * @type {Array<string>}
     * @memberof CleanupStaleMatches200ResponseResults
     */
    successful?: Array<string>;
    /**
     * IDs of matches that failed to archive
     * @type {Array<string>}
     * @memberof CleanupStaleMatches200ResponseResults
     */
    failed?: Array<string>;
}

/**
 * Check if a given object implements the CleanupStaleMatches200ResponseResults interface.
 */
export function instanceOfCleanupStaleMatches200ResponseResults(value: object): value is CleanupStaleMatches200ResponseResults {
    return true;
}

export function CleanupStaleMatches200ResponseResultsFromJSON(json: any): CleanupStaleMatches200ResponseResults {
    return CleanupStaleMatches200ResponseResultsFromJSONTyped(json, false);
}

export function CleanupStaleMatches200ResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleanupStaleMatches200ResponseResults {
    if (json == null) {
        return json;
    }
    return {
        
        'successful': json['successful'] == null ? undefined : json['successful'],
        'failed': json['failed'] == null ? undefined : json['failed'],
    };
}

export function CleanupStaleMatches200ResponseResultsToJSON(json: any): CleanupStaleMatches200ResponseResults {
    return CleanupStaleMatches200ResponseResultsToJSONTyped(json, false);
}

export function CleanupStaleMatches200ResponseResultsToJSONTyped(value?: CleanupStaleMatches200ResponseResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'successful': value['successful'],
        'failed': value['failed'],
    };
}

