/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CleanupStaleMatches200ResponseResults } from './CleanupStaleMatches200ResponseResults.js';
import {
    CleanupStaleMatches200ResponseResultsFromJSON,
    CleanupStaleMatches200ResponseResultsFromJSONTyped,
    CleanupStaleMatches200ResponseResultsToJSON,
    CleanupStaleMatches200ResponseResultsToJSONTyped,
} from './CleanupStaleMatches200ResponseResults.js';

/**
 * 
 * @export
 * @interface CleanupStaleMatches200Response
 */
export interface CleanupStaleMatches200Response {
    /**
     * 
     * @type {number}
     * @memberof CleanupStaleMatches200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CleanupStaleMatches200Response
     */
    message?: string;
    /**
     * 
     * @type {CleanupStaleMatches200ResponseResults}
     * @memberof CleanupStaleMatches200Response
     */
    results?: CleanupStaleMatches200ResponseResults;
}

/**
 * Check if a given object implements the CleanupStaleMatches200Response interface.
 */
export function instanceOfCleanupStaleMatches200Response(value: object): value is CleanupStaleMatches200Response {
    return true;
}

export function CleanupStaleMatches200ResponseFromJSON(json: any): CleanupStaleMatches200Response {
    return CleanupStaleMatches200ResponseFromJSONTyped(json, false);
}

export function CleanupStaleMatches200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CleanupStaleMatches200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'results': json['results'] == null ? undefined : CleanupStaleMatches200ResponseResultsFromJSON(json['results']),
    };
}

export function CleanupStaleMatches200ResponseToJSON(json: any): CleanupStaleMatches200Response {
    return CleanupStaleMatches200ResponseToJSONTyped(json, false);
}

export function CleanupStaleMatches200ResponseToJSONTyped(value?: CleanupStaleMatches200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'results': CleanupStaleMatches200ResponseResultsToJSON(value['results']),
    };
}

