/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ClearPendingResponseDto
 */
export interface ClearPendingResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ClearPendingResponseDto
     */
    statusCode: number;
    /**
     * Success message
     * @type {string}
     * @memberof ClearPendingResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the ClearPendingResponseDto interface.
 */
export function instanceOfClearPendingResponseDto(value: object): value is ClearPendingResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ClearPendingResponseDtoFromJSON(json: any): ClearPendingResponseDto {
    return ClearPendingResponseDtoFromJSONTyped(json, false);
}

export function ClearPendingResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClearPendingResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
    };
}

export function ClearPendingResponseDtoToJSON(json: any): ClearPendingResponseDto {
    return ClearPendingResponseDtoToJSONTyped(json, false);
}

export function ClearPendingResponseDtoToJSONTyped(value?: ClearPendingResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

