/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CloseOutstandingResponseDto
 */
export interface CloseOutstandingResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof CloseOutstandingResponseDto
     */
    statusCode: number;
    /**
     * Success message
     * @type {string}
     * @memberof CloseOutstandingResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the CloseOutstandingResponseDto interface.
 */
export function instanceOfCloseOutstandingResponseDto(value: object): value is CloseOutstandingResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CloseOutstandingResponseDtoFromJSON(json: any): CloseOutstandingResponseDto {
    return CloseOutstandingResponseDtoFromJSONTyped(json, false);
}

export function CloseOutstandingResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseOutstandingResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
    };
}

export function CloseOutstandingResponseDtoToJSON(json: any): CloseOutstandingResponseDto {
    return CloseOutstandingResponseDtoToJSONTyped(json, false);
}

export function CloseOutstandingResponseDtoToJSONTyped(value?: CloseOutstandingResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

