/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateChangelogDto
 */
export interface CreateChangelogDto {
    /**
     * 
     * @type {string}
     * @memberof CreateChangelogDto
     */
    app_name: CreateChangelogDtoAppNameEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateChangelogDto
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChangelogDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChangelogDto
     */
    content: string;
    /**
     * ISO Date string
     * @type {Date}
     * @memberof CreateChangelogDto
     */
    published_at?: Date;
}


/**
 * @export
 */
export const CreateChangelogDtoAppNameEnum = {
    Pluto: 'Pluto',
    Khronos: 'Khronos',
    Goracle: 'Goracle'
} as const;
export type CreateChangelogDtoAppNameEnum = typeof CreateChangelogDtoAppNameEnum[keyof typeof CreateChangelogDtoAppNameEnum];


/**
 * Check if a given object implements the CreateChangelogDto interface.
 */
export function instanceOfCreateChangelogDto(value: object): value is CreateChangelogDto {
    if (!('app_name' in value) || value['app_name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateChangelogDtoFromJSON(json: any): CreateChangelogDto {
    return CreateChangelogDtoFromJSONTyped(json, false);
}

export function CreateChangelogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChangelogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'app_name': json['app_name'],
        'version': json['version'],
        'title': json['title'],
        'content': json['content'],
        'published_at': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
    };
}

export function CreateChangelogDtoToJSON(json: any): CreateChangelogDto {
    return CreateChangelogDtoToJSONTyped(json, false);
}

export function CreateChangelogDtoToJSONTyped(value?: CreateChangelogDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_name': value['app_name'],
        'version': value['version'],
        'title': value['title'],
        'content': value['content'],
        'published_at': value['published_at'] == null ? undefined : ((value['published_at']).toISOString()),
    };
}

