/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAccountWithBodyRequest
 */
export interface CreateAccountWithBodyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountWithBodyRequest
     */
    userid?: string;
}

/**
 * Check if a given object implements the CreateAccountWithBodyRequest interface.
 */
export function instanceOfCreateAccountWithBodyRequest(value: object): value is CreateAccountWithBodyRequest {
    return true;
}

export function CreateAccountWithBodyRequestFromJSON(json: any): CreateAccountWithBodyRequest {
    return CreateAccountWithBodyRequestFromJSONTyped(json, false);
}

export function CreateAccountWithBodyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountWithBodyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'] == null ? undefined : json['userid'],
    };
}

export function CreateAccountWithBodyRequestToJSON(json: any): CreateAccountWithBodyRequest {
    return CreateAccountWithBodyRequestToJSONTyped(json, false);
}

export function CreateAccountWithBodyRequestToJSONTyped(value?: CreateAccountWithBodyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
    };
}

