/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DailyClaimBodyDto
 */
export interface DailyClaimBodyDto {
    /**
     * Indicates if the Patreon override is enabled, which means the user is a Patreon member and in some cases, meets the required Patreon tier.
     * @type {boolean}
     * @memberof DailyClaimBodyDto
     */
    patreonOverride: boolean;
}

/**
 * Check if a given object implements the DailyClaimBodyDto interface.
 */
export function instanceOfDailyClaimBodyDto(value: object): value is DailyClaimBodyDto {
    if (!('patreonOverride' in value) || value['patreonOverride'] === undefined) return false;
    return true;
}

export function DailyClaimBodyDtoFromJSON(json: any): DailyClaimBodyDto {
    return DailyClaimBodyDtoFromJSONTyped(json, false);
}

export function DailyClaimBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyClaimBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'patreonOverride': json['patreonOverride'],
    };
}

export function DailyClaimBodyDtoToJSON(json: any): DailyClaimBodyDto {
    return DailyClaimBodyDtoToJSONTyped(json, false);
}

export function DailyClaimBodyDtoToJSONTyped(value?: DailyClaimBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patreonOverride': value['patreonOverride'],
    };
}

