/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DiscordConfig
 */
export interface DiscordConfig {
    /**
     * Unique identifier for the Discord configuration entry
     * @type {string}
     * @memberof DiscordConfig
     */
    id: string;
    /**
     * Guild ID associated with the setting
     * @type {string}
     * @memberof DiscordConfig
     */
    guild_id: string;
    /**
     * Type of setting
     * @type {string}
     * @memberof DiscordConfig
     */
    setting_type: DiscordConfigSettingTypeEnum;
    /**
     * Value of the setting. When the setting type is 'preferred_teams', it is a comma separated list. E.g, 'lakers,hawks'
     * @type {string}
     * @memberof DiscordConfig
     */
    setting_value: string;
}


/**
 * @export
 */
export const DiscordConfigSettingTypeEnum = {
    GamesCategory: 'GAMES_CATEGORY',
    BettingChan: 'BETTING_CHAN',
    DailyScheduleChan: 'DAILY_SCHEDULE_CHAN',
    PredictionsChan: 'PREDICTIONS_CHAN',
    LogsChan: 'LOGS_CHAN',
    LogsEnabled: 'LOGS_ENABLED',
    PreferredTeams: 'PREFERRED_TEAMS'
} as const;
export type DiscordConfigSettingTypeEnum = typeof DiscordConfigSettingTypeEnum[keyof typeof DiscordConfigSettingTypeEnum];


/**
 * Check if a given object implements the DiscordConfig interface.
 */
export function instanceOfDiscordConfig(value: object): value is DiscordConfig {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('guild_id' in value) || value['guild_id'] === undefined) return false;
    if (!('setting_type' in value) || value['setting_type'] === undefined) return false;
    if (!('setting_value' in value) || value['setting_value'] === undefined) return false;
    return true;
}

export function DiscordConfigFromJSON(json: any): DiscordConfig {
    return DiscordConfigFromJSONTyped(json, false);
}

export function DiscordConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscordConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'guild_id': json['guild_id'],
        'setting_type': json['setting_type'],
        'setting_value': json['setting_value'],
    };
}

export function DiscordConfigToJSON(json: any): DiscordConfig {
    return DiscordConfigToJSONTyped(json, false);
}

export function DiscordConfigToJSONTyped(value?: DiscordConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'guild_id': value['guild_id'],
        'setting_type': value['setting_type'],
        'setting_value': value['setting_value'],
    };
}

