/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DoubledBetslipDto } from './DoubledBetslipDto.js';
import {
    DoubledBetslipDtoFromJSON,
    DoubledBetslipDtoFromJSONTyped,
    DoubledBetslipDtoToJSON,
    DoubledBetslipDtoToJSONTyped,
} from './DoubledBetslipDto.js';

/**
 * 
 * @export
 * @interface DoubleDownDto
 */
export interface DoubleDownDto {
    /**
     * The HTTP status code of the response.
     * @type {number}
     * @memberof DoubleDownDto
     */
    status: number;
    /**
     * A message detailing the result of the operation.
     * @type {string}
     * @memberof DoubleDownDto
     */
    message: string;
    /**
     * The detailed information about the doubled betslip.
     * @type {DoubledBetslipDto}
     * @memberof DoubleDownDto
     */
    betslip: DoubledBetslipDto;
}

/**
 * Check if a given object implements the DoubleDownDto interface.
 */
export function instanceOfDoubleDownDto(value: object): value is DoubleDownDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('betslip' in value) || value['betslip'] === undefined) return false;
    return true;
}

export function DoubleDownDtoFromJSON(json: any): DoubleDownDto {
    return DoubleDownDtoFromJSONTyped(json, false);
}

export function DoubleDownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoubleDownDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'betslip': DoubledBetslipDtoFromJSON(json['betslip']),
    };
}

export function DoubleDownDtoToJSON(json: any): DoubleDownDto {
    return DoubleDownDtoToJSONTyped(json, false);
}

export function DoubleDownDtoToJSONTyped(value?: DoubleDownDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'betslip': DoubledBetslipDtoToJSON(value['betslip']),
    };
}

