/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DoubledBetslipDto
 */
export interface DoubledBetslipDto {
    /**
     * The new amount of the bet after doubling.
     * @type {number}
     * @memberof DoubledBetslipDto
     */
    newBetAmount: number;
    /**
     * The profit expected if the bet wins, calculated based on the doubled bet amount.
     * @type {number}
     * @memberof DoubledBetslipDto
     */
    newProfit: number;
    /**
     * The total potential payout (original bet plus profit) if the bet wins.
     * @type {number}
     * @memberof DoubledBetslipDto
     */
    newPayout: number;
    /**
     * The new balance of the user’s account after the bet amount has been doubled and deducted.
     * @type {number}
     * @memberof DoubledBetslipDto
     */
    newBalance: number;
    /**
     * The unique identifier of the user who owns the bet.
     * @type {string}
     * @memberof DoubledBetslipDto
     */
    userid: string;
    /**
     * The unique identifier of the bet that has been doubled.
     * @type {number}
     * @memberof DoubledBetslipDto
     */
    betId: number;
    /**
     * Flag indicating if this is a newly created account
     * @type {boolean}
     * @memberof DoubledBetslipDto
     */
    isNewUser?: boolean;
}

/**
 * Check if a given object implements the DoubledBetslipDto interface.
 */
export function instanceOfDoubledBetslipDto(value: object): value is DoubledBetslipDto {
    if (!('newBetAmount' in value) || value['newBetAmount'] === undefined) return false;
    if (!('newProfit' in value) || value['newProfit'] === undefined) return false;
    if (!('newPayout' in value) || value['newPayout'] === undefined) return false;
    if (!('newBalance' in value) || value['newBalance'] === undefined) return false;
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('betId' in value) || value['betId'] === undefined) return false;
    return true;
}

export function DoubledBetslipDtoFromJSON(json: any): DoubledBetslipDto {
    return DoubledBetslipDtoFromJSONTyped(json, false);
}

export function DoubledBetslipDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoubledBetslipDto {
    if (json == null) {
        return json;
    }
    return {
        
        'newBetAmount': json['newBetAmount'],
        'newProfit': json['newProfit'],
        'newPayout': json['newPayout'],
        'newBalance': json['newBalance'],
        'userid': json['userid'],
        'betId': json['betId'],
        'isNewUser': json['isNewUser'] == null ? undefined : json['isNewUser'],
    };
}

export function DoubledBetslipDtoToJSON(json: any): DoubledBetslipDto {
    return DoubledBetslipDtoToJSONTyped(json, false);
}

export function DoubledBetslipDtoToJSONTyped(value?: DoubledBetslipDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newBetAmount': value['newBetAmount'],
        'newProfit': value['newProfit'],
        'newPayout': value['newPayout'],
        'newBalance': value['newBalance'],
        'userid': value['userid'],
        'betId': value['betId'],
        'isNewUser': value['isNewUser'],
    };
}

