/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Footer
 */
export interface Footer {
    /**
     * 
     * @type {number}
     * @memberof Footer
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Footer
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof Footer
     */
    category: FooterCategoryEnum | null;
    /**
     * 
     * @type {boolean}
     * @memberof Footer
     */
    isAnnouncement: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Footer
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Footer
     */
    expiresAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Footer
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Footer
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const FooterCategoryEnum = {
    Core: 'core',
    General: 'general',
    Betting: 'betting',
    PlacedBet: 'placedBet',
    HighBetPlaced: 'highBetPlaced',
    LowBetPlaced: 'lowBetPlaced',
    Error: 'error'
} as const;
export type FooterCategoryEnum = typeof FooterCategoryEnum[keyof typeof FooterCategoryEnum];


/**
 * Check if a given object implements the Footer interface.
 */
export function instanceOfFooter(value: object): value is Footer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('isAnnouncement' in value) || value['isAnnouncement'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function FooterFromJSON(json: any): Footer {
    return FooterFromJSONTyped(json, false);
}

export function FooterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Footer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
        'category': json['category'],
        'isAnnouncement': json['isAnnouncement'],
        'isActive': json['isActive'],
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function FooterToJSON(json: any): Footer {
    return FooterToJSONTyped(json, false);
}

export function FooterToJSONTyped(value?: Footer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'category': value['category'],
        'isAnnouncement': value['isAnnouncement'],
        'isActive': value['isActive'],
        'expiresAt': (value['expiresAt'] == null ? null : (value['expiresAt'] as any).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

