/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AnnouncementDto } from './AnnouncementDto.js';
import {
    AnnouncementDtoFromJSON,
    AnnouncementDtoFromJSONTyped,
    AnnouncementDtoToJSON,
    AnnouncementDtoToJSONTyped,
} from './AnnouncementDto.js';

/**
 * 
 * @export
 * @interface FooterConfigResponseDto
 */
export interface FooterConfigResponseDto {
    /**
     * 
     * @type {AnnouncementDto}
     * @memberof FooterConfigResponseDto
     */
    announcement?: AnnouncementDto | null;
    /**
     * Footer messages grouped by category
     * @type {object}
     * @memberof FooterConfigResponseDto
     */
    categories: object;
}

/**
 * Check if a given object implements the FooterConfigResponseDto interface.
 */
export function instanceOfFooterConfigResponseDto(value: object): value is FooterConfigResponseDto {
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function FooterConfigResponseDtoFromJSON(json: any): FooterConfigResponseDto {
    return FooterConfigResponseDtoFromJSONTyped(json, false);
}

export function FooterConfigResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooterConfigResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'announcement': json['announcement'] == null ? undefined : AnnouncementDtoFromJSON(json['announcement']),
        'categories': json['categories'],
    };
}

export function FooterConfigResponseDtoToJSON(json: any): FooterConfigResponseDto {
    return FooterConfigResponseDtoToJSONTyped(json, false);
}

export function FooterConfigResponseDtoToJSONTyped(value?: FooterConfigResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'announcement': AnnouncementDtoToJSON(value['announcement']),
        'categories': value['categories'],
    };
}

