/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ActiveOutcomePropDto } from './ActiveOutcomePropDto.js';
import {
    ActiveOutcomePropDtoFromJSON,
    ActiveOutcomePropDtoFromJSONTyped,
    ActiveOutcomePropDtoToJSON,
    ActiveOutcomePropDtoToJSONTyped,
} from './ActiveOutcomePropDto.js';

/**
 * 
 * @export
 * @interface GameDto
 */
export interface GameDto {
    /**
     * Event ID
     * @type {string}
     * @memberof GameDto
     */
    event_id: string;
    /**
     * Matchup string (e.g., "BOS vs LAL")
     * @type {string}
     * @memberof GameDto
     */
    matchup: string;
    /**
     * Home team name
     * @type {string}
     * @memberof GameDto
     */
    home_team: string;
    /**
     * Away team name
     * @type {string}
     * @memberof GameDto
     */
    away_team: string;
    /**
     * Game commence time (ISO 8601)
     * @type {string}
     * @memberof GameDto
     */
    commence_time: string;
    /**
     * Sport title (e.g., NBA, NFL)
     * @type {string}
     * @memberof GameDto
     */
    sport_title: string;
    /**
     * List of props for this game, sorted by prediction count DESC
     * @type {Array<ActiveOutcomePropDto>}
     * @memberof GameDto
     */
    props: Array<ActiveOutcomePropDto>;
}

/**
 * Check if a given object implements the GameDto interface.
 */
export function instanceOfGameDto(value: object): value is GameDto {
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('matchup' in value) || value['matchup'] === undefined) return false;
    if (!('home_team' in value) || value['home_team'] === undefined) return false;
    if (!('away_team' in value) || value['away_team'] === undefined) return false;
    if (!('commence_time' in value) || value['commence_time'] === undefined) return false;
    if (!('sport_title' in value) || value['sport_title'] === undefined) return false;
    if (!('props' in value) || value['props'] === undefined) return false;
    return true;
}

export function GameDtoFromJSON(json: any): GameDto {
    return GameDtoFromJSONTyped(json, false);
}

export function GameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'],
        'matchup': json['matchup'],
        'home_team': json['home_team'],
        'away_team': json['away_team'],
        'commence_time': json['commence_time'],
        'sport_title': json['sport_title'],
        'props': ((json['props'] as Array<any>).map(ActiveOutcomePropDtoFromJSON)),
    };
}

export function GameDtoToJSON(json: any): GameDto {
    return GameDtoToJSONTyped(json, false);
}

export function GameDtoToJSONTyped(value?: GameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'matchup': value['matchup'],
        'home_team': value['home_team'],
        'away_team': value['away_team'],
        'commence_time': value['commence_time'],
        'sport_title': value['sport_title'],
        'props': ((value['props'] as Array<any>).map(ActiveOutcomePropDtoToJSON)),
    };
}

