/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetAllMatchesDtoMatchesInner } from './GetAllMatchesDtoMatchesInner.js';
import {
    GetAllMatchesDtoMatchesInnerFromJSON,
    GetAllMatchesDtoMatchesInnerFromJSONTyped,
    GetAllMatchesDtoMatchesInnerToJSON,
    GetAllMatchesDtoMatchesInnerToJSONTyped,
} from './GetAllMatchesDtoMatchesInner.js';

/**
 * 
 * @export
 * @interface GetAllMatchesDto
 */
export interface GetAllMatchesDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof GetAllMatchesDto
     */
    statusCode: number;
    /**
     * List of all matches from Goracle across all supported sports
     * @type {Array<GetAllMatchesDtoMatchesInner>}
     * @memberof GetAllMatchesDto
     */
    matches: Array<GetAllMatchesDtoMatchesInner>;
}

/**
 * Check if a given object implements the GetAllMatchesDto interface.
 */
export function instanceOfGetAllMatchesDto(value: object): value is GetAllMatchesDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('matches' in value) || value['matches'] === undefined) return false;
    return true;
}

export function GetAllMatchesDtoFromJSON(json: any): GetAllMatchesDto {
    return GetAllMatchesDtoFromJSONTyped(json, false);
}

export function GetAllMatchesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllMatchesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'matches': ((json['matches'] as Array<any>).map(GetAllMatchesDtoMatchesInnerFromJSON)),
    };
}

export function GetAllMatchesDtoToJSON(json: any): GetAllMatchesDto {
    return GetAllMatchesDtoToJSONTyped(json, false);
}

export function GetAllMatchesDtoToJSONTyped(value?: GetAllMatchesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'matches': ((value['matches'] as Array<any>).map(GetAllMatchesDtoMatchesInnerToJSON)),
    };
}

