/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetAllMatchesDtoMatchesInner
 */
export interface GetAllMatchesDtoMatchesInner {
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    sport_title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    home_team?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    away_team?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    commence_time?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    home_score?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    away_score?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    home_team_odds?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    away_team_odds?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAllMatchesDtoMatchesInner
     */
    winner?: string;
}

/**
 * Check if a given object implements the GetAllMatchesDtoMatchesInner interface.
 */
export function instanceOfGetAllMatchesDtoMatchesInner(value: object): value is GetAllMatchesDtoMatchesInner {
    return true;
}

export function GetAllMatchesDtoMatchesInnerFromJSON(json: any): GetAllMatchesDtoMatchesInner {
    return GetAllMatchesDtoMatchesInnerFromJSONTyped(json, false);
}

export function GetAllMatchesDtoMatchesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllMatchesDtoMatchesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'sport_title': json['sport_title'] == null ? undefined : json['sport_title'],
        'home_team': json['home_team'] == null ? undefined : json['home_team'],
        'away_team': json['away_team'] == null ? undefined : json['away_team'],
        'commence_time': json['commence_time'] == null ? undefined : json['commence_time'],
        'home_score': json['home_score'] == null ? undefined : json['home_score'],
        'away_score': json['away_score'] == null ? undefined : json['away_score'],
        'status': json['status'] == null ? undefined : json['status'],
        'home_team_odds': json['home_team_odds'] == null ? undefined : json['home_team_odds'],
        'away_team_odds': json['away_team_odds'] == null ? undefined : json['away_team_odds'],
        'winner': json['winner'] == null ? undefined : json['winner'],
    };
}

export function GetAllMatchesDtoMatchesInnerToJSON(json: any): GetAllMatchesDtoMatchesInner {
    return GetAllMatchesDtoMatchesInnerToJSONTyped(json, false);
}

export function GetAllMatchesDtoMatchesInnerToJSONTyped(value?: GetAllMatchesDtoMatchesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sport': value['sport'],
        'sport_title': value['sport_title'],
        'home_team': value['home_team'],
        'away_team': value['away_team'],
        'commence_time': value['commence_time'],
        'home_score': value['home_score'],
        'away_score': value['away_score'],
        'status': value['status'],
        'home_team_odds': value['home_team_odds'],
        'away_team_odds': value['away_team_odds'],
        'winner': value['winner'],
    };
}

