/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetBalanceDto
 */
export interface GetBalanceDto {
    /**
     * 
     * @type {number}
     * @memberof GetBalanceDto
     */
    statusCode: number;
    /**
     * The balance of the user
     * @type {number}
     * @memberof GetBalanceDto
     */
    balance: number;
    /**
     * The identifier of the user
     * @type {string}
     * @memberof GetBalanceDto
     */
    userid: string;
    /**
     * Whether the user is new or not. This is flagged within the service if an account has to be created for them.
     * @type {boolean}
     * @memberof GetBalanceDto
     */
    isNewUser: boolean;
}

/**
 * Check if a given object implements the GetBalanceDto interface.
 */
export function instanceOfGetBalanceDto(value: object): value is GetBalanceDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('isNewUser' in value) || value['isNewUser'] === undefined) return false;
    return true;
}

export function GetBalanceDtoFromJSON(json: any): GetBalanceDto {
    return GetBalanceDtoFromJSONTyped(json, false);
}

export function GetBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'balance': json['balance'],
        'userid': json['userid'],
        'isNewUser': json['isNewUser'],
    };
}

export function GetBalanceDtoToJSON(json: any): GetBalanceDto {
    return GetBalanceDtoToJSONTyped(json, false);
}

export function GetBalanceDtoToJSONTyped(value?: GetBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'balance': value['balance'],
        'userid': value['userid'],
        'isNewUser': value['isNewUser'],
    };
}

