/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MatchDetailDto } from './MatchDetailDto.js';
import {
    MatchDetailDtoFromJSON,
    MatchDetailDtoFromJSONTyped,
    MatchDetailDtoToJSON,
    MatchDetailDtoToJSONTyped,
} from './MatchDetailDto.js';

/**
 * 
 * @export
 * @interface GetMatchInfoDto
 */
export interface GetMatchInfoDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof GetMatchInfoDto
     */
    statusCode: number;
    /**
     * Response message
     * @type {string}
     * @memberof GetMatchInfoDto
     */
    message: string;
    /**
     * Detailed match information from Goracle
     * @type {MatchDetailDto}
     * @memberof GetMatchInfoDto
     */
    match: MatchDetailDto;
}

/**
 * Check if a given object implements the GetMatchInfoDto interface.
 */
export function instanceOfGetMatchInfoDto(value: object): value is GetMatchInfoDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('match' in value) || value['match'] === undefined) return false;
    return true;
}

export function GetMatchInfoDtoFromJSON(json: any): GetMatchInfoDto {
    return GetMatchInfoDtoFromJSONTyped(json, false);
}

export function GetMatchInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMatchInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'match': MatchDetailDtoFromJSON(json['match']),
    };
}

export function GetMatchInfoDtoToJSON(json: any): GetMatchInfoDto {
    return GetMatchInfoDtoToJSONTyped(json, false);
}

export function GetMatchInfoDtoToJSONTyped(value?: GetMatchInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'match': MatchDetailDtoToJSON(value['match']),
    };
}

