/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetRandomPropsDto
 */
export interface GetRandomPropsDto {
    /**
     * Sport key (nba or nfl)
     * @type {string}
     * @memberof GetRandomPropsDto
     */
    sport: GetRandomPropsDtoSportEnum;
    /**
     * Number of random props to return
     * @type {number}
     * @memberof GetRandomPropsDto
     */
    count?: number;
}


/**
 * @export
 */
export const GetRandomPropsDtoSportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type GetRandomPropsDtoSportEnum = typeof GetRandomPropsDtoSportEnum[keyof typeof GetRandomPropsDtoSportEnum];


/**
 * Check if a given object implements the GetRandomPropsDto interface.
 */
export function instanceOfGetRandomPropsDto(value: object): value is GetRandomPropsDto {
    if (!('sport' in value) || value['sport'] === undefined) return false;
    return true;
}

export function GetRandomPropsDtoFromJSON(json: any): GetRandomPropsDto {
    return GetRandomPropsDtoFromJSONTyped(json, false);
}

export function GetRandomPropsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRandomPropsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sport': json['sport'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetRandomPropsDtoToJSON(json: any): GetRandomPropsDto {
    return GetRandomPropsDtoToJSONTyped(json, false);
}

export function GetRandomPropsDtoToJSONTyped(value?: GetRandomPropsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sport': value['sport'],
        'count': value['count'],
    };
}

