/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DiscordConfig } from './DiscordConfig.js';
import {
    DiscordConfigFromJSON,
    DiscordConfigFromJSONTyped,
    DiscordConfigToJSON,
    DiscordConfigToJSONTyped,
} from './DiscordConfig.js';

/**
 * 
 * @export
 * @interface Guild
 */
export interface Guild {
    /**
     * Unique identifier of the guild
     * @type {string}
     * @memberof Guild
     */
    guild_id: string;
    /**
     * Name of the guild
     * @type {string}
     * @memberof Guild
     */
    guild_name: string;
    /**
     * Date when the guild joined
     * @type {string}
     * @memberof Guild
     */
    date_joined: string;
    /**
     * Sport associated with the guild
     * @type {string}
     * @memberof Guild
     */
    sport: string;
    /**
     * Discord configurations associated with the guild
     * @type {Array<DiscordConfig>}
     * @memberof Guild
     */
    config?: Array<DiscordConfig>;
}

/**
 * Check if a given object implements the Guild interface.
 */
export function instanceOfGuild(value: object): value is Guild {
    if (!('guild_id' in value) || value['guild_id'] === undefined) return false;
    if (!('guild_name' in value) || value['guild_name'] === undefined) return false;
    if (!('date_joined' in value) || value['date_joined'] === undefined) return false;
    if (!('sport' in value) || value['sport'] === undefined) return false;
    return true;
}

export function GuildFromJSON(json: any): Guild {
    return GuildFromJSONTyped(json, false);
}

export function GuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): Guild {
    if (json == null) {
        return json;
    }
    return {
        
        'guild_id': json['guild_id'],
        'guild_name': json['guild_name'],
        'date_joined': json['date_joined'],
        'sport': json['sport'],
        'config': json['config'] == null ? undefined : ((json['config'] as Array<any>).map(DiscordConfigFromJSON)),
    };
}

export function GuildToJSON(json: any): Guild {
    return GuildToJSONTyped(json, false);
}

export function GuildToJSONTyped(value?: Guild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guild_id'],
        'guild_name': value['guild_name'],
        'date_joined': value['date_joined'],
        'sport': value['sport'],
        'config': value['config'] == null ? undefined : ((value['config'] as Array<any>).map(DiscordConfigToJSON)),
    };
}

