/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetslipWithAggregationDTO } from './BetslipWithAggregationDTO.js';
import {
    BetslipWithAggregationDTOFromJSON,
    BetslipWithAggregationDTOFromJSONTyped,
    BetslipWithAggregationDTOToJSON,
    BetslipWithAggregationDTOToJSONTyped,
} from './BetslipWithAggregationDTO.js';

/**
 * 
 * @export
 * @interface InitBetslipRespDTO
 */
export interface InitBetslipRespDTO {
    /**
     * The HTTP status code
     * @type {number}
     * @memberof InitBetslipRespDTO
     */
    statusCode: number;
    /**
     * The data containing finalized betslip details -- This is sent back to the client (Pluto) for the user to confirm their betslip
     * @type {BetslipWithAggregationDTO}
     * @memberof InitBetslipRespDTO
     */
    betslip: BetslipWithAggregationDTO;
}

/**
 * Check if a given object implements the InitBetslipRespDTO interface.
 */
export function instanceOfInitBetslipRespDTO(value: object): value is InitBetslipRespDTO {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('betslip' in value) || value['betslip'] === undefined) return false;
    return true;
}

export function InitBetslipRespDTOFromJSON(json: any): InitBetslipRespDTO {
    return InitBetslipRespDTOFromJSONTyped(json, false);
}

export function InitBetslipRespDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitBetslipRespDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'betslip': BetslipWithAggregationDTOFromJSON(json['betslip']),
    };
}

export function InitBetslipRespDTOToJSON(json: any): InitBetslipRespDTO {
    return InitBetslipRespDTOToJSONTyped(json, false);
}

export function InitBetslipRespDTOToJSONTyped(value?: InitBetslipRespDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'betslip': BetslipWithAggregationDTOToJSON(value['betslip']),
    };
}

