/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ManualSettleMatchResultDto } from './ManualSettleMatchResultDto.js';
import {
    ManualSettleMatchResultDtoFromJSON,
    ManualSettleMatchResultDtoFromJSONTyped,
    ManualSettleMatchResultDtoToJSON,
    ManualSettleMatchResultDtoToJSONTyped,
} from './ManualSettleMatchResultDto.js';

/**
 * 
 * @export
 * @interface ManualSettleMatchResponseDto
 */
export interface ManualSettleMatchResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ManualSettleMatchResponseDto
     */
    statusCode: number;
    /**
     * Response message
     * @type {string}
     * @memberof ManualSettleMatchResponseDto
     */
    message: string;
    /**
     * Settlement result details
     * @type {ManualSettleMatchResultDto}
     * @memberof ManualSettleMatchResponseDto
     */
    result: ManualSettleMatchResultDto;
}

/**
 * Check if a given object implements the ManualSettleMatchResponseDto interface.
 */
export function instanceOfManualSettleMatchResponseDto(value: object): value is ManualSettleMatchResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ManualSettleMatchResponseDtoFromJSON(json: any): ManualSettleMatchResponseDto {
    return ManualSettleMatchResponseDtoFromJSONTyped(json, false);
}

export function ManualSettleMatchResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualSettleMatchResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'result': ManualSettleMatchResultDtoFromJSON(json['result']),
    };
}

export function ManualSettleMatchResponseDtoToJSON(json: any): ManualSettleMatchResponseDto {
    return ManualSettleMatchResponseDtoToJSONTyped(json, false);
}

export function ManualSettleMatchResponseDtoToJSONTyped(value?: ManualSettleMatchResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'result': ManualSettleMatchResultDtoToJSON(value['result']),
    };
}

