/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ManualSettleMatchBetsProcessedDto } from './ManualSettleMatchBetsProcessedDto.js';
import {
    ManualSettleMatchBetsProcessedDtoFromJSON,
    ManualSettleMatchBetsProcessedDtoFromJSONTyped,
    ManualSettleMatchBetsProcessedDtoToJSON,
    ManualSettleMatchBetsProcessedDtoToJSONTyped,
} from './ManualSettleMatchBetsProcessedDto.js';

/**
 * 
 * @export
 * @interface ManualSettleMatchResultDto
 */
export interface ManualSettleMatchResultDto {
    /**
     * Match ID
     * @type {string}
     * @memberof ManualSettleMatchResultDto
     */
    matchId: string;
    /**
     * Winning team name (null for ties)
     * @type {string}
     * @memberof ManualSettleMatchResultDto
     */
    winner?: string | null;
    /**
     * Losing team name (null for ties)
     * @type {string}
     * @memberof ManualSettleMatchResultDto
     */
    loser?: string | null;
    /**
     * Indicates if the match ended in a tie
     * @type {boolean}
     * @memberof ManualSettleMatchResultDto
     */
    tie?: boolean | null;
    /**
     * Home team final score
     * @type {number}
     * @memberof ManualSettleMatchResultDto
     */
    homeScore: number;
    /**
     * Away team final score
     * @type {number}
     * @memberof ManualSettleMatchResultDto
     */
    awayScore: number;
    /**
     * Bet processing summary
     * @type {ManualSettleMatchBetsProcessedDto}
     * @memberof ManualSettleMatchResultDto
     */
    betsProcessed: ManualSettleMatchBetsProcessedDto;
}

/**
 * Check if a given object implements the ManualSettleMatchResultDto interface.
 */
export function instanceOfManualSettleMatchResultDto(value: object): value is ManualSettleMatchResultDto {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('homeScore' in value) || value['homeScore'] === undefined) return false;
    if (!('awayScore' in value) || value['awayScore'] === undefined) return false;
    if (!('betsProcessed' in value) || value['betsProcessed'] === undefined) return false;
    return true;
}

export function ManualSettleMatchResultDtoFromJSON(json: any): ManualSettleMatchResultDto {
    return ManualSettleMatchResultDtoFromJSONTyped(json, false);
}

export function ManualSettleMatchResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualSettleMatchResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'winner': json['winner'] == null ? undefined : json['winner'],
        'loser': json['loser'] == null ? undefined : json['loser'],
        'tie': json['tie'] == null ? undefined : json['tie'],
        'homeScore': json['homeScore'],
        'awayScore': json['awayScore'],
        'betsProcessed': ManualSettleMatchBetsProcessedDtoFromJSON(json['betsProcessed']),
    };
}

export function ManualSettleMatchResultDtoToJSON(json: any): ManualSettleMatchResultDto {
    return ManualSettleMatchResultDtoToJSONTyped(json, false);
}

export function ManualSettleMatchResultDtoToJSONTyped(value?: ManualSettleMatchResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'winner': value['winner'],
        'loser': value['loser'],
        'tie': value['tie'],
        'homeScore': value['homeScore'],
        'awayScore': value['awayScore'],
        'betsProcessed': ManualSettleMatchBetsProcessedDtoToJSON(value['betsProcessed']),
    };
}

