/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ManualSettleMatchDto
 */
export interface ManualSettleMatchDto {
    /**
     * Home team final score
     * @type {number}
     * @memberof ManualSettleMatchDto
     */
    homeScore: number;
    /**
     * Away team final score
     * @type {number}
     * @memberof ManualSettleMatchDto
     */
    awayScore: number;
    /**
     * Optional admin user ID for audit trail
     * @type {string}
     * @memberof ManualSettleMatchDto
     */
    adminUserId?: string;
    /**
     * If true, forces settlement even if the event was already processed. Use to fix "zombie" events where bets remain pending despite settlement. Corresponds to forceSettlement in manualSettleMatchSchema.
     * @type {boolean}
     * @memberof ManualSettleMatchDto
     */
    forceSettlement?: boolean;
}

/**
 * Check if a given object implements the ManualSettleMatchDto interface.
 */
export function instanceOfManualSettleMatchDto(value: object): value is ManualSettleMatchDto {
    if (!('homeScore' in value) || value['homeScore'] === undefined) return false;
    if (!('awayScore' in value) || value['awayScore'] === undefined) return false;
    return true;
}

export function ManualSettleMatchDtoFromJSON(json: any): ManualSettleMatchDto {
    return ManualSettleMatchDtoFromJSONTyped(json, false);
}

export function ManualSettleMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualSettleMatchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'homeScore': json['homeScore'],
        'awayScore': json['awayScore'],
        'adminUserId': json['adminUserId'] == null ? undefined : json['adminUserId'],
        'forceSettlement': json['forceSettlement'] == null ? undefined : json['forceSettlement'],
    };
}

export function ManualSettleMatchDtoToJSON(json: any): ManualSettleMatchDto {
    return ManualSettleMatchDtoToJSONTyped(json, false);
}

export function ManualSettleMatchDtoToJSONTyped(value?: ManualSettleMatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'homeScore': value['homeScore'],
        'awayScore': value['awayScore'],
        'adminUserId': value['adminUserId'],
        'forceSettlement': value['forceSettlement'],
    };
}

