/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OutcomeDataDto } from './OutcomeDataDto.js';
import {
    OutcomeDataDtoFromJSON,
    OutcomeDataDtoFromJSONTyped,
    OutcomeDataDtoToJSON,
    OutcomeDataDtoToJSONTyped,
} from './OutcomeDataDto.js';

/**
 * 
 * @export
 * @interface MarketDataDto
 */
export interface MarketDataDto {
    /**
     * Market key (h2h, spreads, totals, etc.)
     * @type {string}
     * @memberof MarketDataDto
     */
    key?: string;
    /**
     * Last update timestamp (ISO 8601)
     * @type {string}
     * @memberof MarketDataDto
     */
    last_update?: string;
    /**
     * Outcomes in this market
     * @type {Array<OutcomeDataDto>}
     * @memberof MarketDataDto
     */
    outcomes?: Array<OutcomeDataDto>;
    /**
     * Reflects the status of prop/outcome or match - typically "completed" for final scores, "in_progress" for ongoing games, or "scheduled" for future events. `result` being present is a more valid indicator of completion
     * @type {string}
     * @memberof MarketDataDto
     */
    status?: string;
}

/**
 * Check if a given object implements the MarketDataDto interface.
 */
export function instanceOfMarketDataDto(value: object): value is MarketDataDto {
    return true;
}

export function MarketDataDtoFromJSON(json: any): MarketDataDto {
    return MarketDataDtoFromJSONTyped(json, false);
}

export function MarketDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'last_update': json['last_update'] == null ? undefined : json['last_update'],
        'outcomes': json['outcomes'] == null ? undefined : ((json['outcomes'] as Array<any>).map(OutcomeDataDtoFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MarketDataDtoToJSON(json: any): MarketDataDto {
    return MarketDataDtoToJSONTyped(json, false);
}

export function MarketDataDtoToJSONTyped(value?: MarketDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'last_update': value['last_update'],
        'outcomes': value['outcomes'] == null ? undefined : ((value['outcomes'] as Array<any>).map(OutcomeDataDtoToJSON)),
        'status': value['status'],
    };
}

