/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MatchupTeamRecordsDto } from './MatchupTeamRecordsDto.js';
import {
    MatchupTeamRecordsDtoFromJSON,
    MatchupTeamRecordsDtoFromJSONTyped,
    MatchupTeamRecordsDtoToJSON,
    MatchupTeamRecordsDtoToJSONTyped,
} from './MatchupTeamRecordsDto.js';
import type { MatchupSeriesInfoDto } from './MatchupSeriesInfoDto.js';
import {
    MatchupSeriesInfoDtoFromJSON,
    MatchupSeriesInfoDtoFromJSONTyped,
    MatchupSeriesInfoDtoToJSON,
    MatchupSeriesInfoDtoToJSONTyped,
} from './MatchupSeriesInfoDto.js';

/**
 * 
 * @export
 * @interface MatchupRecordsDto
 */
export interface MatchupRecordsDto {
    /**
     * Records for the home team
     * @type {MatchupTeamRecordsDto}
     * @memberof MatchupRecordsDto
     */
    home_team: MatchupTeamRecordsDto;
    /**
     * Records for the away team
     * @type {MatchupTeamRecordsDto}
     * @memberof MatchupRecordsDto
     */
    away_team: MatchupTeamRecordsDto;
    /**
     * Populated only when the matchup resolves to an active playoff series on ESPN for the supplied date.
     * @type {MatchupSeriesInfoDto}
     * @memberof MatchupRecordsDto
     */
    series?: MatchupSeriesInfoDto;
}

/**
 * Check if a given object implements the MatchupRecordsDto interface.
 */
export function instanceOfMatchupRecordsDto(value: object): value is MatchupRecordsDto {
    if (!('home_team' in value) || value['home_team'] === undefined) return false;
    if (!('away_team' in value) || value['away_team'] === undefined) return false;
    return true;
}

export function MatchupRecordsDtoFromJSON(json: any): MatchupRecordsDto {
    return MatchupRecordsDtoFromJSONTyped(json, false);
}

export function MatchupRecordsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupRecordsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'home_team': MatchupTeamRecordsDtoFromJSON(json['home_team']),
        'away_team': MatchupTeamRecordsDtoFromJSON(json['away_team']),
        'series': json['series'] == null ? undefined : MatchupSeriesInfoDtoFromJSON(json['series']),
    };
}

export function MatchupRecordsDtoToJSON(json: any): MatchupRecordsDto {
    return MatchupRecordsDtoToJSONTyped(json, false);
}

export function MatchupRecordsDtoToJSONTyped(value?: MatchupRecordsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'home_team': MatchupTeamRecordsDtoToJSON(value['home_team']),
        'away_team': MatchupTeamRecordsDtoToJSON(value['away_team']),
        'series': MatchupSeriesInfoDtoToJSON(value['series']),
    };
}

