/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MatchupTeamRecordsDto
 */
export interface MatchupTeamRecordsDto {
    /**
     * Full team display name as returned by ESPN
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    display_name: string;
    /**
     * Three-letter team abbreviation
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    abbreviation?: string;
    /**
     * Total regular-season record (wins-losses)
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    total_record: string | null;
    /**
     * Home game record for the regular season
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    home_record?: string | null;
    /**
     * Away game record for the regular season
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    away_record?: string | null;
    /**
     * Postseason record; populated only during or after the playoffs
     * @type {string}
     * @memberof MatchupTeamRecordsDto
     */
    playoff_record?: string | null;
}

/**
 * Check if a given object implements the MatchupTeamRecordsDto interface.
 */
export function instanceOfMatchupTeamRecordsDto(value: object): value is MatchupTeamRecordsDto {
    if (!('display_name' in value) || value['display_name'] === undefined) return false;
    if (!('total_record' in value) || value['total_record'] === undefined) return false;
    return true;
}

export function MatchupTeamRecordsDtoFromJSON(json: any): MatchupTeamRecordsDto {
    return MatchupTeamRecordsDtoFromJSONTyped(json, false);
}

export function MatchupTeamRecordsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupTeamRecordsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'display_name': json['display_name'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'total_record': json['total_record'],
        'home_record': json['home_record'] == null ? undefined : json['home_record'],
        'away_record': json['away_record'] == null ? undefined : json['away_record'],
        'playoff_record': json['playoff_record'] == null ? undefined : json['playoff_record'],
    };
}

export function MatchupTeamRecordsDtoToJSON(json: any): MatchupTeamRecordsDto {
    return MatchupTeamRecordsDtoToJSONTyped(json, false);
}

export function MatchupTeamRecordsDtoToJSONTyped(value?: MatchupTeamRecordsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['display_name'],
        'abbreviation': value['abbreviation'],
        'total_record': value['total_record'],
        'home_record': value['home_record'],
        'away_record': value['away_record'],
        'playoff_record': value['playoff_record'],
    };
}

