/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MatchupSeriesInfoDto
 */
export interface MatchupSeriesInfoDto {
    /**
     * Playoff round label from ESPN (e.g. First Round, Conference Finals, Finals)
     * @type {string}
     * @memberof MatchupSeriesInfoDto
     */
    round?: string;
    /**
     * Human-readable series standing summary from ESPN
     * @type {string}
     * @memberof MatchupSeriesInfoDto
     */
    summary?: string;
    /**
     * Number of series wins for the home team
     * @type {number}
     * @memberof MatchupSeriesInfoDto
     */
    home_wins?: number;
    /**
     * Number of series wins for the away team
     * @type {number}
     * @memberof MatchupSeriesInfoDto
     */
    away_wins?: number;
    /**
     * Maximum number of games in the series (typically 7)
     * @type {number}
     * @memberof MatchupSeriesInfoDto
     */
    total_games?: number;
    /**
     * Whether the playoff series has concluded
     * @type {boolean}
     * @memberof MatchupSeriesInfoDto
     */
    completed?: boolean;
}

/**
 * Check if a given object implements the MatchupSeriesInfoDto interface.
 */
export function instanceOfMatchupSeriesInfoDto(value: object): value is MatchupSeriesInfoDto {
    return true;
}

export function MatchupSeriesInfoDtoFromJSON(json: any): MatchupSeriesInfoDto {
    return MatchupSeriesInfoDtoFromJSONTyped(json, false);
}

export function MatchupSeriesInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupSeriesInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'round': json['round'] == null ? undefined : json['round'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'home_wins': json['home_wins'] == null ? undefined : json['home_wins'],
        'away_wins': json['away_wins'] == null ? undefined : json['away_wins'],
        'total_games': json['total_games'] == null ? undefined : json['total_games'],
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function MatchupSeriesInfoDtoToJSON(json: any): MatchupSeriesInfoDto {
    return MatchupSeriesInfoDtoToJSONTyped(json, false);
}

export function MatchupSeriesInfoDtoToJSONTyped(value?: MatchupSeriesInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round': value['round'],
        'summary': value['summary'],
        'home_wins': value['home_wins'],
        'away_wins': value['away_wins'],
        'total_games': value['total_games'],
        'completed': value['completed'],
    };
}

