/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MatchInfo404Response
 */
export interface MatchInfo404Response {
    /**
     * 
     * @type {any}
     * @memberof MatchInfo404Response
     */
    statusCode: any | null;
    /**
     * 
     * @type {any}
     * @memberof MatchInfo404Response
     */
    message: any | null;
    /**
     * 
     * @type {any}
     * @memberof MatchInfo404Response
     */
    exception: any | null;
}

/**
 * Check if a given object implements the MatchInfo404Response interface.
 */
export function instanceOfMatchInfo404Response(value: object): value is MatchInfo404Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('exception' in value) || value['exception'] === undefined) return false;
    return true;
}

export function MatchInfo404ResponseFromJSON(json: any): MatchInfo404Response {
    return MatchInfo404ResponseFromJSONTyped(json, false);
}

export function MatchInfo404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchInfo404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'exception': json['exception'],
    };
}

export function MatchInfo404ResponseToJSON(json: any): MatchInfo404Response {
    return MatchInfo404ResponseToJSONTyped(json, false);
}

export function MatchInfo404ResponseToJSONTyped(value?: MatchInfo404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'exception': value['exception'],
    };
}

