/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Account } from './Account.js';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account.js';

/**
 * 
 * @export
 * @interface Monies
 */
export interface Monies {
    /**
     * Unique identifier for the money record
     * @type {string}
     * @memberof Monies
     */
    id: string;
    /**
     * Current balance amount
     * @type {number}
     * @memberof Monies
     */
    balance: number;
    /**
     * 
     * @type {Account}
     * @memberof Monies
     */
    account: Account;
}

/**
 * Check if a given object implements the Monies interface.
 */
export function instanceOfMonies(value: object): value is Monies {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function MoniesFromJSON(json: any): Monies {
    return MoniesFromJSONTyped(json, false);
}

export function MoniesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Monies {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'balance': json['balance'],
        'account': AccountFromJSON(json['account']),
    };
}

export function MoniesToJSON(json: any): Monies {
    return MoniesToJSONTyped(json, false);
}

export function MoniesToJSONTyped(value?: Monies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'balance': value['balance'],
        'account': AccountToJSON(value['account']),
    };
}

