/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Outcome
 */
export interface Outcome {
    /**
     * The name of the outcome
     * @type {string}
     * @memberof Outcome
     */
    name: string;
    /**
     * The price for the outcome
     * @type {number}
     * @memberof Outcome
     */
    price: number;
    /**
     * The point for the outcome
     * @type {number}
     * @memberof Outcome
     */
    point: number | null;
}

/**
 * Check if a given object implements the Outcome interface.
 */
export function instanceOfOutcome(value: object): value is Outcome {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('point' in value) || value['point'] === undefined) return false;
    return true;
}

export function OutcomeFromJSON(json: any): Outcome {
    return OutcomeFromJSONTyped(json, false);
}

export function OutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Outcome {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'point': json['point'],
    };
}

export function OutcomeToJSON(json: any): Outcome {
    return OutcomeToJSONTyped(json, false);
}

export function OutcomeToJSONTyped(value?: Outcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': value['price'],
        'point': value['point'],
    };
}

