/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OutcomeSettledWebhookDto
 */
export interface OutcomeSettledWebhookDto {
    /**
     * Unique identifier for the outcome in Goracle
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    outcome_uuid: string;
    /**
     * Event ID from Goracle - corresponds 1:1 with our database match IDs
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    event_id: string;
    /**
     * Market key (e.g., h2h, totals, player_points)
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    market_key: string;
    /**
     * Bookmaker key (e.g., fanduel, draftkings)
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    bookmaker_key: string;
    /**
     * Outcome-specific result indicating if this particular outcome won, lost, pushed, or was cancelled. Values: "win", "loss", "push", "cancelled"
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    result: string;
    /**
     * The actual numeric value that determined the result. Examples: Final score for moneyline (108), Total points for Over/Under (215.5), Point differential for spread (7), Total touchdowns, etc. Primarily used for player props.
     * @type {number}
     * @memberof OutcomeSettledWebhookDto
     */
    actual_value?: number;
    /**
     * Correlation ID for tracking webhook across systems
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    correlation_id?: string;
    /**
     * Timestamp when the outcome was completed
     * @type {Date}
     * @memberof OutcomeSettledWebhookDto
     */
    completed_at: Date;
    /**
     * Home team name
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    home_team: string;
    /**
     * Away team name
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    away_team: string;
    /**
     * Final home team score
     * @type {number}
     * @memberof OutcomeSettledWebhookDto
     */
    home_score: number;
    /**
     * Final away team score
     * @type {number}
     * @memberof OutcomeSettledWebhookDto
     */
    away_score: number;
    /**
     * The winning team name (e.g., "Los Angeles Lakers") or "Draw" for ties
     * @type {string}
     * @memberof OutcomeSettledWebhookDto
     */
    winner: string;
}

/**
 * Check if a given object implements the OutcomeSettledWebhookDto interface.
 */
export function instanceOfOutcomeSettledWebhookDto(value: object): value is OutcomeSettledWebhookDto {
    if (!('outcome_uuid' in value) || value['outcome_uuid'] === undefined) return false;
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    if (!('bookmaker_key' in value) || value['bookmaker_key'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('completed_at' in value) || value['completed_at'] === undefined) return false;
    if (!('home_team' in value) || value['home_team'] === undefined) return false;
    if (!('away_team' in value) || value['away_team'] === undefined) return false;
    if (!('home_score' in value) || value['home_score'] === undefined) return false;
    if (!('away_score' in value) || value['away_score'] === undefined) return false;
    if (!('winner' in value) || value['winner'] === undefined) return false;
    return true;
}

export function OutcomeSettledWebhookDtoFromJSON(json: any): OutcomeSettledWebhookDto {
    return OutcomeSettledWebhookDtoFromJSONTyped(json, false);
}

export function OutcomeSettledWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutcomeSettledWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome_uuid': json['outcome_uuid'],
        'event_id': json['event_id'],
        'market_key': json['market_key'],
        'bookmaker_key': json['bookmaker_key'],
        'result': json['result'],
        'actual_value': json['actual_value'] == null ? undefined : json['actual_value'],
        'correlation_id': json['correlation_id'] == null ? undefined : json['correlation_id'],
        'completed_at': (new Date(json['completed_at'])),
        'home_team': json['home_team'],
        'away_team': json['away_team'],
        'home_score': json['home_score'],
        'away_score': json['away_score'],
        'winner': json['winner'],
    };
}

export function OutcomeSettledWebhookDtoToJSON(json: any): OutcomeSettledWebhookDto {
    return OutcomeSettledWebhookDtoToJSONTyped(json, false);
}

export function OutcomeSettledWebhookDtoToJSONTyped(value?: OutcomeSettledWebhookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome_uuid': value['outcome_uuid'],
        'event_id': value['event_id'],
        'market_key': value['market_key'],
        'bookmaker_key': value['bookmaker_key'],
        'result': value['result'],
        'actual_value': value['actual_value'],
        'correlation_id': value['correlation_id'],
        'completed_at': ((value['completed_at']).toISOString()),
        'home_team': value['home_team'],
        'away_team': value['away_team'],
        'home_score': value['home_score'],
        'away_score': value['away_score'],
        'winner': value['winner'],
    };
}

