/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TeamBetStats } from './TeamBetStats.js';
import {
    TeamBetStatsFromJSON,
    TeamBetStatsFromJSONTyped,
    TeamBetStatsToJSON,
    TeamBetStatsToJSONTyped,
} from './TeamBetStats.js';
import type { ProfitLossSummary } from './ProfitLossSummary.js';
import {
    ProfitLossSummaryFromJSON,
    ProfitLossSummaryFromJSONTyped,
    ProfitLossSummaryToJSON,
    ProfitLossSummaryToJSONTyped,
} from './ProfitLossSummary.js';
import type { TeamLossStats } from './TeamLossStats.js';
import {
    TeamLossStatsFromJSON,
    TeamLossStatsFromJSONTyped,
    TeamLossStatsToJSON,
    TeamLossStatsToJSONTyped,
} from './TeamLossStats.js';

/**
 * 
 * @export
 * @interface OverallStatsDto
 */
export interface OverallStatsDto {
    /**
     * Total number of bets
     * @type {number}
     * @memberof OverallStatsDto
     */
    totalBets: number;
    /**
     * Total number of wins
     * @type {number}
     * @memberof OverallStatsDto
     */
    totalWins: number;
    /**
     * Total number of losses
     * @type {number}
     * @memberof OverallStatsDto
     */
    totalLosses: number;
    /**
     * Win rate
     * @type {number}
     * @memberof OverallStatsDto
     */
    winRate: number;
    /**
     * Most bet team statistics
     * @type {TeamBetStats}
     * @memberof OverallStatsDto
     */
    mostBetTeam: TeamBetStats;
    /**
     * Team with most losses statistics
     * @type {TeamLossStats}
     * @memberof OverallStatsDto
     */
    mostLossesTeam: TeamLossStats;
    /**
     * Highest bet amount
     * @type {number}
     * @memberof OverallStatsDto
     */
    highestBetAmount: number;
    /**
     * Profit and loss summary
     * @type {ProfitLossSummary}
     * @memberof OverallStatsDto
     */
    profitLossSummary: ProfitLossSummary;
}

/**
 * Check if a given object implements the OverallStatsDto interface.
 */
export function instanceOfOverallStatsDto(value: object): value is OverallStatsDto {
    if (!('totalBets' in value) || value['totalBets'] === undefined) return false;
    if (!('totalWins' in value) || value['totalWins'] === undefined) return false;
    if (!('totalLosses' in value) || value['totalLosses'] === undefined) return false;
    if (!('winRate' in value) || value['winRate'] === undefined) return false;
    if (!('mostBetTeam' in value) || value['mostBetTeam'] === undefined) return false;
    if (!('mostLossesTeam' in value) || value['mostLossesTeam'] === undefined) return false;
    if (!('highestBetAmount' in value) || value['highestBetAmount'] === undefined) return false;
    if (!('profitLossSummary' in value) || value['profitLossSummary'] === undefined) return false;
    return true;
}

export function OverallStatsDtoFromJSON(json: any): OverallStatsDto {
    return OverallStatsDtoFromJSONTyped(json, false);
}

export function OverallStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverallStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBets': json['totalBets'],
        'totalWins': json['totalWins'],
        'totalLosses': json['totalLosses'],
        'winRate': json['winRate'],
        'mostBetTeam': TeamBetStatsFromJSON(json['mostBetTeam']),
        'mostLossesTeam': TeamLossStatsFromJSON(json['mostLossesTeam']),
        'highestBetAmount': json['highestBetAmount'],
        'profitLossSummary': ProfitLossSummaryFromJSON(json['profitLossSummary']),
    };
}

export function OverallStatsDtoToJSON(json: any): OverallStatsDto {
    return OverallStatsDtoToJSONTyped(json, false);
}

export function OverallStatsDtoToJSONTyped(value?: OverallStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalBets': value['totalBets'],
        'totalWins': value['totalWins'],
        'totalLosses': value['totalLosses'],
        'winRate': value['winRate'],
        'mostBetTeam': TeamBetStatsToJSON(value['mostBetTeam']),
        'mostLossesTeam': TeamLossStatsToJSON(value['mostLossesTeam']),
        'highestBetAmount': value['highestBetAmount'],
        'profitLossSummary': ProfitLossSummaryToJSON(value['profitLossSummary']),
    };
}

