/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PlaceBetDto
 */
export interface PlaceBetDto {
    /**
     * 
     * @type {string}
     * @memberof PlaceBetDto
     */
    userid: string;
    /**
     * 
     * @type {string}
     * @memberof PlaceBetDto
     */
    team: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceBetDto
     */
    amount: number;
    /**
     * The guild id - The origin of where the bet was placed
     * @type {string}
     * @memberof PlaceBetDto
     */
    guild_id: string;
    /**
     * The Identifier for a match. // aka event_id
     * @type {string}
     * @memberof PlaceBetDto
     */
    matchup_id: string;
    /**
     * The prop type the match & bet belongs to.
     * @type {string}
     * @memberof PlaceBetDto
     */
    market_key: PlaceBetDtoMarketKeyEnum;
}


/**
 * @export
 */
export const PlaceBetDtoMarketKeyEnum = {
    H2h: 'h2h',
    Totals: 'totals',
    PlayerPassTds: 'player_pass_tds',
    PlayerPassYds: 'player_pass_yds',
    PlayerPassCompletions: 'player_pass_completions',
    PlayerPassAttempts: 'player_pass_attempts',
    PlayerPassInterceptions: 'player_pass_interceptions',
    PlayerPassLongestCompletion: 'player_pass_longest_completion',
    PlayerRushYds: 'player_rush_yds',
    PlayerRushAttempts: 'player_rush_attempts',
    PlayerRushLongest: 'player_rush_longest',
    PlayerReceptions: 'player_receptions',
    PlayerReceptionYds: 'player_reception_yds',
    PlayerReceptionLongest: 'player_reception_longest',
    PlayerKickingPoints: 'player_kicking_points',
    PlayerFieldGoals: 'player_field_goals',
    PlayerTacklesAssists: 'player_tackles_assists',
    Player1stTd: 'player_1st_td',
    PlayerLastTd: 'player_last_td',
    PlayerAnytimeTd: 'player_anytime_td',
    PlayerPassTdsAlternate: 'player_pass_tds_alternate',
    PlayerPassYdsAlternate: 'player_pass_yds_alternate',
    PlayerRushYdsAlternate: 'player_rush_yds_alternate',
    PlayerRushReceptionYdsAlternate: 'player_rush_reception_yds_alternate',
    PlayerReceptionYdsAlternate: 'player_reception_yds_alternate',
    PlayerReceptionsAlternate: 'player_receptions_alternate',
    PlayerPoints: 'player_points',
    PlayerRebounds: 'player_rebounds',
    PlayerAssists: 'player_assists',
    PlayerThrees: 'player_threes',
    PlayerBlocks: 'player_blocks',
    PlayerSteals: 'player_steals',
    PlayerBlocksSteals: 'player_blocks_steals',
    PlayerTurnovers: 'player_turnovers',
    PlayerPointsReboundsAssists: 'player_points_rebounds_assists',
    PlayerPointsRebounds: 'player_points_rebounds',
    PlayerPointsAssists: 'player_points_assists',
    PlayerReboundsAssists: 'player_rebounds_assists',
    PlayerFirstBasket: 'player_first_basket',
    PlayerDoubleDouble: 'player_double_double',
    PlayerTripleDouble: 'player_triple_double',
    PlayerPointsAlternate: 'player_points_alternate',
    PlayerReboundsAlternate: 'player_rebounds_alternate',
    PlayerAssistsAlternate: 'player_assists_alternate',
    PlayerBlocksAlternate: 'player_blocks_alternate',
    PlayerStealsAlternate: 'player_steals_alternate',
    PlayerThreesAlternate: 'player_threes_alternate',
    PlayerPointsAssistsAlternate: 'player_points_assists_alternate',
    PlayerPointsReboundsAlternate: 'player_points_rebounds_alternate',
    PlayerReboundsAssistsAlternate: 'player_rebounds_assists_alternate',
    PlayerPointsReboundsAssistsAlternate: 'player_points_rebounds_assists_alternate'
} as const;
export type PlaceBetDtoMarketKeyEnum = typeof PlaceBetDtoMarketKeyEnum[keyof typeof PlaceBetDtoMarketKeyEnum];


/**
 * Check if a given object implements the PlaceBetDto interface.
 */
export function instanceOfPlaceBetDto(value: object): value is PlaceBetDto {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('guild_id' in value) || value['guild_id'] === undefined) return false;
    if (!('matchup_id' in value) || value['matchup_id'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    return true;
}

export function PlaceBetDtoFromJSON(json: any): PlaceBetDto {
    return PlaceBetDtoFromJSONTyped(json, false);
}

export function PlaceBetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'team': json['team'],
        'amount': json['amount'],
        'guild_id': json['guild_id'],
        'matchup_id': json['matchup_id'],
        'market_key': json['market_key'],
    };
}

export function PlaceBetDtoToJSON(json: any): PlaceBetDto {
    return PlaceBetDtoToJSONTyped(json, false);
}

export function PlaceBetDtoToJSONTyped(value?: PlaceBetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
        'team': value['team'],
        'amount': value['amount'],
        'guild_id': value['guild_id'],
        'matchup_id': value['matchup_id'],
        'market_key': value['market_key'],
    };
}

