/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PredictionDTO
 */
export interface PredictionDTO {
    /**
     * Unique identifier for the prediction
     * @type {string}
     * @memberof PredictionDTO
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof PredictionDTO
     */
    user_id: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof PredictionDTO
     */
    created_at: Date;
    /**
     * Outcome UUID from Goracle
     * @type {string}
     * @memberof PredictionDTO
     */
    outcome_uuid: string;
    /**
     * Event ID from Goracle
     * @type {string}
     * @memberof PredictionDTO
     */
    event_id: string;
    /**
     * Market ID from Goracle - used for grouping paired outcomes
     * @type {number}
     * @memberof PredictionDTO
     */
    market_id?: number;
    /**
     * Sport key
     * @type {string}
     * @memberof PredictionDTO
     */
    sport: string;
    /**
     * User's choice
     * @type {string}
     * @memberof PredictionDTO
     */
    choice: string;
    /**
     * Whether the prediction is correct
     * @type {boolean}
     * @memberof PredictionDTO
     */
    is_correct?: boolean | null;
    /**
     * Status of the prediction
     * @type {string}
     * @memberof PredictionDTO
     */
    status: PredictionDTOStatusEnum;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof PredictionDTO
     */
    updated_at: Date;
    /**
     * Guild ID
     * @type {string}
     * @memberof PredictionDTO
     */
    guild_id: string;
    /**
     * Market key
     * @type {string}
     * @memberof PredictionDTO
     */
    market_key: string;
    /**
     * Bookmaker key
     * @type {string}
     * @memberof PredictionDTO
     */
    bookmaker_key: string;
}


/**
 * @export
 */
export const PredictionDTOStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Error: 'error'
} as const;
export type PredictionDTOStatusEnum = typeof PredictionDTOStatusEnum[keyof typeof PredictionDTOStatusEnum];


/**
 * Check if a given object implements the PredictionDTO interface.
 */
export function instanceOfPredictionDTO(value: object): value is PredictionDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('outcome_uuid' in value) || value['outcome_uuid'] === undefined) return false;
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('sport' in value) || value['sport'] === undefined) return false;
    if (!('choice' in value) || value['choice'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('guild_id' in value) || value['guild_id'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    if (!('bookmaker_key' in value) || value['bookmaker_key'] === undefined) return false;
    return true;
}

export function PredictionDTOFromJSON(json: any): PredictionDTO {
    return PredictionDTOFromJSONTyped(json, false);
}

export function PredictionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'created_at': (new Date(json['created_at'])),
        'outcome_uuid': json['outcome_uuid'],
        'event_id': json['event_id'],
        'market_id': json['market_id'] == null ? undefined : json['market_id'],
        'sport': json['sport'],
        'choice': json['choice'],
        'is_correct': json['is_correct'] == null ? undefined : json['is_correct'],
        'status': json['status'],
        'updated_at': (new Date(json['updated_at'])),
        'guild_id': json['guild_id'],
        'market_key': json['market_key'],
        'bookmaker_key': json['bookmaker_key'],
    };
}

export function PredictionDTOToJSON(json: any): PredictionDTO {
    return PredictionDTOToJSONTyped(json, false);
}

export function PredictionDTOToJSONTyped(value?: PredictionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'created_at': ((value['created_at']).toISOString()),
        'outcome_uuid': value['outcome_uuid'],
        'event_id': value['event_id'],
        'market_id': value['market_id'],
        'sport': value['sport'],
        'choice': value['choice'],
        'is_correct': value['is_correct'],
        'status': value['status'],
        'updated_at': ((value['updated_at']).toISOString()),
        'guild_id': value['guild_id'],
        'market_key': value['market_key'],
        'bookmaker_key': value['bookmaker_key'],
    };
}

