/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PredictionsCountDto
 */
export interface PredictionsCountDto {
    /**
     * Total number of predictions
     * @type {number}
     * @memberof PredictionsCountDto
     */
    total: number;
    /**
     * Total number of unique users
     * @type {number}
     * @memberof PredictionsCountDto
     */
    unique_users: number;
}

/**
 * Check if a given object implements the PredictionsCountDto interface.
 */
export function instanceOfPredictionsCountDto(value: object): value is PredictionsCountDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('unique_users' in value) || value['unique_users'] === undefined) return false;
    return true;
}

export function PredictionsCountDtoFromJSON(json: any): PredictionsCountDto {
    return PredictionsCountDtoFromJSONTyped(json, false);
}

export function PredictionsCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionsCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'unique_users': json['unique_users'],
    };
}

export function PredictionsCountDtoToJSON(json: any): PredictionsCountDto {
    return PredictionsCountDtoToJSONTyped(json, false);
}

export function PredictionsCountDtoToJSONTyped(value?: PredictionsCountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'unique_users': value['unique_users'],
    };
}

