/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PropOutcomeSideDto } from './PropOutcomeSideDto.js';
import {
    PropOutcomeSideDtoFromJSON,
    PropOutcomeSideDtoFromJSONTyped,
    PropOutcomeSideDtoToJSON,
    PropOutcomeSideDtoToJSONTyped,
} from './PropOutcomeSideDto.js';

/**
 * 
 * @export
 * @interface ProcessedPropDto
 */
export interface ProcessedPropDto {
    /**
     * Event ID
     * @type {string}
     * @memberof ProcessedPropDto
     */
    event_id: string;
    /**
     * Game commence time (ISO 8601)
     * @type {string}
     * @memberof ProcessedPropDto
     */
    commence_time: string;
    /**
     * Home team name
     * @type {string}
     * @memberof ProcessedPropDto
     */
    home_team: string;
    /**
     * Away team name
     * @type {string}
     * @memberof ProcessedPropDto
     */
    away_team: string;
    /**
     * Sport title (e.g., "NBA", "NFL")
     * @type {string}
     * @memberof ProcessedPropDto
     */
    sport_title: string;
    /**
     * Market key (e.g., player_pass_tds, player_rush_yds)
     * @type {string}
     * @memberof ProcessedPropDto
     */
    market_key: string;
    /**
     * Bookmaker key (e.g., draftkings)
     * @type {string}
     * @memberof ProcessedPropDto
     */
    bookmaker_key: string;
    /**
     * Player name or outcome description
     * @type {string}
     * @memberof ProcessedPropDto
     */
    description: string;
    /**
     * Point value (e.g., 250.5 for over/under)
     * @type {number}
     * @memberof ProcessedPropDto
     */
    point: number;
    /**
     * Over outcome details
     * @type {PropOutcomeSideDto}
     * @memberof ProcessedPropDto
     */
    over: PropOutcomeSideDto;
    /**
     * Under outcome details
     * @type {PropOutcomeSideDto}
     * @memberof ProcessedPropDto
     */
    under: PropOutcomeSideDto;
}

/**
 * Check if a given object implements the ProcessedPropDto interface.
 */
export function instanceOfProcessedPropDto(value: object): value is ProcessedPropDto {
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('commence_time' in value) || value['commence_time'] === undefined) return false;
    if (!('home_team' in value) || value['home_team'] === undefined) return false;
    if (!('away_team' in value) || value['away_team'] === undefined) return false;
    if (!('sport_title' in value) || value['sport_title'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    if (!('bookmaker_key' in value) || value['bookmaker_key'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('point' in value) || value['point'] === undefined) return false;
    if (!('over' in value) || value['over'] === undefined) return false;
    if (!('under' in value) || value['under'] === undefined) return false;
    return true;
}

export function ProcessedPropDtoFromJSON(json: any): ProcessedPropDto {
    return ProcessedPropDtoFromJSONTyped(json, false);
}

export function ProcessedPropDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessedPropDto {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'],
        'commence_time': json['commence_time'],
        'home_team': json['home_team'],
        'away_team': json['away_team'],
        'sport_title': json['sport_title'],
        'market_key': json['market_key'],
        'bookmaker_key': json['bookmaker_key'],
        'description': json['description'],
        'point': json['point'],
        'over': PropOutcomeSideDtoFromJSON(json['over']),
        'under': PropOutcomeSideDtoFromJSON(json['under']),
    };
}

export function ProcessedPropDtoToJSON(json: any): ProcessedPropDto {
    return ProcessedPropDtoToJSONTyped(json, false);
}

export function ProcessedPropDtoToJSONTyped(value?: ProcessedPropDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'commence_time': value['commence_time'],
        'home_team': value['home_team'],
        'away_team': value['away_team'],
        'sport_title': value['sport_title'],
        'market_key': value['market_key'],
        'bookmaker_key': value['bookmaker_key'],
        'description': value['description'],
        'point': value['point'],
        'over': PropOutcomeSideDtoToJSON(value['over']),
        'under': PropOutcomeSideDtoToJSON(value['under']),
    };
}

