/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProfitLossSummary
 */
export interface ProfitLossSummary {
    /**
     * The total amount won
     * @type {number}
     * @memberof ProfitLossSummary
     */
    totalWon: number;
    /**
     * The total amount lost
     * @type {number}
     * @memberof ProfitLossSummary
     */
    totalLost: number;
    /**
     * The net profit
     * @type {number}
     * @memberof ProfitLossSummary
     */
    netProfit: number;
}

/**
 * Check if a given object implements the ProfitLossSummary interface.
 */
export function instanceOfProfitLossSummary(value: object): value is ProfitLossSummary {
    if (!('totalWon' in value) || value['totalWon'] === undefined) return false;
    if (!('totalLost' in value) || value['totalLost'] === undefined) return false;
    if (!('netProfit' in value) || value['netProfit'] === undefined) return false;
    return true;
}

export function ProfitLossSummaryFromJSON(json: any): ProfitLossSummary {
    return ProfitLossSummaryFromJSONTyped(json, false);
}

export function ProfitLossSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfitLossSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalWon': json['totalWon'],
        'totalLost': json['totalLost'],
        'netProfit': json['netProfit'],
    };
}

export function ProfitLossSummaryToJSON(json: any): ProfitLossSummary {
    return ProfitLossSummaryToJSONTyped(json, false);
}

export function ProfitLossSummaryToJSONTyped(value?: ProfitLossSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalWon': value['totalWon'],
        'totalLost': value['totalLost'],
        'netProfit': value['netProfit'],
    };
}

