/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PropOutcomeSideDto
 */
export interface PropOutcomeSideDto {
    /**
     * Outcome UUID for placing predictions
     * @type {string}
     * @memberof PropOutcomeSideDto
     */
    outcome_uuid: string;
    /**
     * Outcome name (e.g., "Over", "Under")
     * @type {string}
     * @memberof PropOutcomeSideDto
     */
    outcome_name: string;
    /**
     * Odds price (American format)
     * @type {number}
     * @memberof PropOutcomeSideDto
     */
    price: number;
}

/**
 * Check if a given object implements the PropOutcomeSideDto interface.
 */
export function instanceOfPropOutcomeSideDto(value: object): value is PropOutcomeSideDto {
    if (!('outcome_uuid' in value) || value['outcome_uuid'] === undefined) return false;
    if (!('outcome_name' in value) || value['outcome_name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PropOutcomeSideDtoFromJSON(json: any): PropOutcomeSideDto {
    return PropOutcomeSideDtoFromJSONTyped(json, false);
}

export function PropOutcomeSideDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropOutcomeSideDto {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome_uuid': json['outcome_uuid'],
        'outcome_name': json['outcome_name'],
        'price': json['price'],
    };
}

export function PropOutcomeSideDtoToJSON(json: any): PropOutcomeSideDto {
    return PropOutcomeSideDtoToJSONTyped(json, false);
}

export function PropOutcomeSideDtoToJSONTyped(value?: PropOutcomeSideDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome_uuid': value['outcome_uuid'],
        'outcome_name': value['outcome_name'],
        'price': value['price'],
    };
}

