/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PropEventContextDto } from './PropEventContextDto.js';
import {
    PropEventContextDtoFromJSON,
    PropEventContextDtoFromJSONTyped,
    PropEventContextDtoToJSON,
    PropEventContextDtoToJSONTyped,
} from './PropEventContextDto.js';
import type { PropOutcomeDetailDto } from './PropOutcomeDetailDto.js';
import {
    PropOutcomeDetailDtoFromJSON,
    PropOutcomeDetailDtoFromJSONTyped,
    PropOutcomeDetailDtoToJSON,
    PropOutcomeDetailDtoToJSONTyped,
} from './PropOutcomeDetailDto.js';

/**
 * 
 * @export
 * @interface PropDto
 */
export interface PropDto {
    /**
     * Event ID
     * @type {string}
     * @memberof PropDto
     */
    event_id: string;
    /**
     * Event context (teams, time, sport)
     * @type {PropEventContextDto}
     * @memberof PropDto
     */
    event_context: PropEventContextDto;
    /**
     * Market key (e.g., player_pass_tds, spreads, totals)
     * @type {string}
     * @memberof PropDto
     */
    market_key: string;
    /**
     * Bookmaker key (e.g., draftkings)
     * @type {string}
     * @memberof PropDto
     */
    bookmaker_key: string;
    /**
     * Market ID from Goracle - groups related outcomes together (e.g., Over/Under pairs share the same market_id). Null for legacy data.
     * @type {number}
     * @memberof PropDto
     */
    market_id?: number | null;
    /**
     * All possible outcomes for this market (Over/Under, Yes/No, team options for spreads, etc.). Each outcome is a bettable "prop". For player props, all outcomes share the same player name in their description field.
     * @type {Array<PropOutcomeDetailDto>}
     * @memberof PropDto
     */
    outcomes: Array<PropOutcomeDetailDto>;
}

/**
 * Check if a given object implements the PropDto interface.
 */
export function instanceOfPropDto(value: object): value is PropDto {
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('event_context' in value) || value['event_context'] === undefined) return false;
    if (!('market_key' in value) || value['market_key'] === undefined) return false;
    if (!('bookmaker_key' in value) || value['bookmaker_key'] === undefined) return false;
    if (!('outcomes' in value) || value['outcomes'] === undefined) return false;
    return true;
}

export function PropDtoFromJSON(json: any): PropDto {
    return PropDtoFromJSONTyped(json, false);
}

export function PropDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropDto {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'],
        'event_context': PropEventContextDtoFromJSON(json['event_context']),
        'market_key': json['market_key'],
        'bookmaker_key': json['bookmaker_key'],
        'market_id': json['market_id'] == null ? undefined : json['market_id'],
        'outcomes': ((json['outcomes'] as Array<any>).map(PropOutcomeDetailDtoFromJSON)),
    };
}

export function PropDtoToJSON(json: any): PropDto {
    return PropDtoToJSONTyped(json, false);
}

export function PropDtoToJSONTyped(value?: PropDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'event_context': PropEventContextDtoToJSON(value['event_context']),
        'market_key': value['market_key'],
        'bookmaker_key': value['bookmaker_key'],
        'market_id': value['market_id'],
        'outcomes': ((value['outcomes'] as Array<any>).map(PropOutcomeDetailDtoToJSON)),
    };
}

