/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PropOutcomeDetailDto
 */
export interface PropOutcomeDetailDto {
    /**
     * Outcome UUID for placing predictions
     * @type {string}
     * @memberof PropOutcomeDetailDto
     */
    outcome_uuid: string;
    /**
     * Outcome name (e.g., Over, Under, Yes, No, team name for spreads)
     * @type {string}
     * @memberof PropOutcomeDetailDto
     */
    name: string;
    /**
     * Outcome type categorization: OVER, UNDER, TEAM_HOME, TEAM_AWAY, YES, NO
     * @type {string}
     * @memberof PropOutcomeDetailDto
     */
    outcome_type?: PropOutcomeDetailDtoOutcomeTypeEnum;
    /**
     * Outcome description - typically the player name for player props (e.g., "Patrick Mahomes"). Null for team markets like spreads/totals.
     * @type {string}
     * @memberof PropOutcomeDetailDto
     */
    description?: string;
    /**
     * Odds price (decimal format)
     * @type {number}
     * @memberof PropOutcomeDetailDto
     */
    price: number;
    /**
     * Point value (e.g., 25.5 for over/under)
     * @type {number}
     * @memberof PropOutcomeDetailDto
     */
    point?: number;
    /**
     * Position (for h2h: home/away/draw)
     * @type {string}
     * @memberof PropOutcomeDetailDto
     */
    position?: string;
    /**
     * Market ID from Goracle - groups related outcomes together (e.g., Over/Under pairs share the same market_id)
     * @type {number}
     * @memberof PropOutcomeDetailDto
     */
    market_id?: number | null;
}


/**
 * @export
 */
export const PropOutcomeDetailDtoOutcomeTypeEnum = {
    Over: 'OVER',
    Under: 'UNDER',
    TeamHome: 'TEAM_HOME',
    TeamAway: 'TEAM_AWAY',
    Yes: 'YES',
    No: 'NO'
} as const;
export type PropOutcomeDetailDtoOutcomeTypeEnum = typeof PropOutcomeDetailDtoOutcomeTypeEnum[keyof typeof PropOutcomeDetailDtoOutcomeTypeEnum];


/**
 * Check if a given object implements the PropOutcomeDetailDto interface.
 */
export function instanceOfPropOutcomeDetailDto(value: object): value is PropOutcomeDetailDto {
    if (!('outcome_uuid' in value) || value['outcome_uuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PropOutcomeDetailDtoFromJSON(json: any): PropOutcomeDetailDto {
    return PropOutcomeDetailDtoFromJSONTyped(json, false);
}

export function PropOutcomeDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropOutcomeDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome_uuid': json['outcome_uuid'],
        'name': json['name'],
        'outcome_type': json['outcome_type'] == null ? undefined : json['outcome_type'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'point': json['point'] == null ? undefined : json['point'],
        'position': json['position'] == null ? undefined : json['position'],
        'market_id': json['market_id'] == null ? undefined : json['market_id'],
    };
}

export function PropOutcomeDetailDtoToJSON(json: any): PropOutcomeDetailDto {
    return PropOutcomeDetailDtoToJSONTyped(json, false);
}

export function PropOutcomeDetailDtoToJSONTyped(value?: PropOutcomeDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome_uuid': value['outcome_uuid'],
        'name': value['name'],
        'outcome_type': value['outcome_type'],
        'description': value['description'],
        'price': value['price'],
        'point': value['point'],
        'position': value['position'],
        'market_id': value['market_id'],
    };
}

