/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PropEventContextDto
 */
export interface PropEventContextDto {
    /**
     * Home team name
     * @type {string}
     * @memberof PropEventContextDto
     */
    home_team: string;
    /**
     * Away team name
     * @type {string}
     * @memberof PropEventContextDto
     */
    away_team: string;
    /**
     * Game commence time (ISO 8601)
     * @type {string}
     * @memberof PropEventContextDto
     */
    commence_time: string;
    /**
     * Sport title
     * @type {string}
     * @memberof PropEventContextDto
     */
    sport_title: string;
}

/**
 * Check if a given object implements the PropEventContextDto interface.
 */
export function instanceOfPropEventContextDto(value: object): value is PropEventContextDto {
    if (!('home_team' in value) || value['home_team'] === undefined) return false;
    if (!('away_team' in value) || value['away_team'] === undefined) return false;
    if (!('commence_time' in value) || value['commence_time'] === undefined) return false;
    if (!('sport_title' in value) || value['sport_title'] === undefined) return false;
    return true;
}

export function PropEventContextDtoFromJSON(json: any): PropEventContextDto {
    return PropEventContextDtoFromJSONTyped(json, false);
}

export function PropEventContextDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropEventContextDto {
    if (json == null) {
        return json;
    }
    return {
        
        'home_team': json['home_team'],
        'away_team': json['away_team'],
        'commence_time': json['commence_time'],
        'sport_title': json['sport_title'],
    };
}

export function PropEventContextDtoToJSON(json: any): PropEventContextDto {
    return PropEventContextDtoToJSONTyped(json, false);
}

export function PropEventContextDtoToJSONTyped(value?: PropEventContextDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'home_team': value['home_team'],
        'away_team': value['away_team'],
        'commence_time': value['commence_time'],
        'sport_title': value['sport_title'],
    };
}

