/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ReconcileOutstandingBetsDto
 */
export interface ReconcileOutstandingBetsDto {
    /**
     * Array of match IDs to reconcile
     * @type {Array<string>}
     * @memberof ReconcileOutstandingBetsDto
     */
    matchIds?: Array<string>;
    /**
     * If true, upserts the settlement record even if it exists. Use to fix "zombie" events where bets remain pending despite settlement.
     * @type {boolean}
     * @memberof ReconcileOutstandingBetsDto
     */
    forceSettlement?: boolean;
}

/**
 * Check if a given object implements the ReconcileOutstandingBetsDto interface.
 */
export function instanceOfReconcileOutstandingBetsDto(value: object): value is ReconcileOutstandingBetsDto {
    return true;
}

export function ReconcileOutstandingBetsDtoFromJSON(json: any): ReconcileOutstandingBetsDto {
    return ReconcileOutstandingBetsDtoFromJSONTyped(json, false);
}

export function ReconcileOutstandingBetsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReconcileOutstandingBetsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'matchIds': json['matchIds'] == null ? undefined : json['matchIds'],
        'forceSettlement': json['forceSettlement'] == null ? undefined : json['forceSettlement'],
    };
}

export function ReconcileOutstandingBetsDtoToJSON(json: any): ReconcileOutstandingBetsDto {
    return ReconcileOutstandingBetsDtoToJSONTyped(json, false);
}

export function ReconcileOutstandingBetsDtoToJSONTyped(value?: ReconcileOutstandingBetsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchIds': value['matchIds'],
        'forceSettlement': value['forceSettlement'],
    };
}

