/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RefundBetsResponseDto
 */
export interface RefundBetsResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof RefundBetsResponseDto
     */
    statusCode: number;
    /**
     * Success message
     * @type {string}
     * @memberof RefundBetsResponseDto
     */
    message: string;
    /**
     * Number of bets refunded
     * @type {number}
     * @memberof RefundBetsResponseDto
     */
    refundedCount: number;
    /**
     * Array of refunded bet IDs
     * @type {Array<number>}
     * @memberof RefundBetsResponseDto
     */
    refundedBetIds: Array<number>;
}

/**
 * Check if a given object implements the RefundBetsResponseDto interface.
 */
export function instanceOfRefundBetsResponseDto(value: object): value is RefundBetsResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('refundedCount' in value) || value['refundedCount'] === undefined) return false;
    if (!('refundedBetIds' in value) || value['refundedBetIds'] === undefined) return false;
    return true;
}

export function RefundBetsResponseDtoFromJSON(json: any): RefundBetsResponseDto {
    return RefundBetsResponseDtoFromJSONTyped(json, false);
}

export function RefundBetsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundBetsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'refundedCount': json['refundedCount'],
        'refundedBetIds': json['refundedBetIds'],
    };
}

export function RefundBetsResponseDtoToJSON(json: any): RefundBetsResponseDto {
    return RefundBetsResponseDtoToJSONTyped(json, false);
}

export function RefundBetsResponseDtoToJSONTyped(value?: RefundBetsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'refundedCount': value['refundedCount'],
        'refundedBetIds': value['refundedBetIds'],
    };
}

