/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RefundBetsDto
 */
export interface RefundBetsDto {
    /**
     * Array of bet IDs to refund
     * @type {Array<number>}
     * @memberof RefundBetsDto
     */
    betIds: Array<number>;
}

/**
 * Check if a given object implements the RefundBetsDto interface.
 */
export function instanceOfRefundBetsDto(value: object): value is RefundBetsDto {
    if (!('betIds' in value) || value['betIds'] === undefined) return false;
    return true;
}

export function RefundBetsDtoFromJSON(json: any): RefundBetsDto {
    return RefundBetsDtoFromJSONTyped(json, false);
}

export function RefundBetsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundBetsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'betIds': json['betIds'],
    };
}

export function RefundBetsDtoToJSON(json: any): RefundBetsDto {
    return RefundBetsDtoToJSONTyped(json, false);
}

export function RefundBetsDtoToJSONTyped(value?: RefundBetsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'betIds': value['betIds'],
    };
}

