/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RemoveAllChannelsDto
 */
export interface RemoveAllChannelsDto {
    /**
     * 
     * @type {number}
     * @memberof RemoveAllChannelsDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof RemoveAllChannelsDto
     */
    message: string;
}

/**
 * Check if a given object implements the RemoveAllChannelsDto interface.
 */
export function instanceOfRemoveAllChannelsDto(value: object): value is RemoveAllChannelsDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function RemoveAllChannelsDtoFromJSON(json: any): RemoveAllChannelsDto {
    return RemoveAllChannelsDtoFromJSONTyped(json, false);
}

export function RemoveAllChannelsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveAllChannelsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
    };
}

export function RemoveAllChannelsDtoToJSON(json: any): RemoveAllChannelsDto {
    return RemoveAllChannelsDtoToJSONTyped(json, false);
}

export function RemoveAllChannelsDtoToJSONTyped(value?: RemoveAllChannelsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

