/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SeasonWeekDto
 */
export interface SeasonWeekDto {
    /**
     * The sport associated with this season week
     * @type {string}
     * @memberof SeasonWeekDto
     */
    sport: SeasonWeekDtoSportEnum;
    /**
     * The year of the season
     * @type {number}
     * @memberof SeasonWeekDto
     */
    seasonYear: number;
    /**
     * The week number in the season
     * @type {number}
     * @memberof SeasonWeekDto
     */
    weekNumber: number;
}


/**
 * @export
 */
export const SeasonWeekDtoSportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type SeasonWeekDtoSportEnum = typeof SeasonWeekDtoSportEnum[keyof typeof SeasonWeekDtoSportEnum];


/**
 * Check if a given object implements the SeasonWeekDto interface.
 */
export function instanceOfSeasonWeekDto(value: object): value is SeasonWeekDto {
    if (!('sport' in value) || value['sport'] === undefined) return false;
    if (!('seasonYear' in value) || value['seasonYear'] === undefined) return false;
    if (!('weekNumber' in value) || value['weekNumber'] === undefined) return false;
    return true;
}

export function SeasonWeekDtoFromJSON(json: any): SeasonWeekDto {
    return SeasonWeekDtoFromJSONTyped(json, false);
}

export function SeasonWeekDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonWeekDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sport': json['sport'],
        'seasonYear': json['seasonYear'],
        'weekNumber': json['weekNumber'],
    };
}

export function SeasonWeekDtoToJSON(json: any): SeasonWeekDto {
    return SeasonWeekDtoToJSONTyped(json, false);
}

export function SeasonWeekDtoToJSONTyped(value?: SeasonWeekDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sport': value['sport'],
        'seasonYear': value['seasonYear'],
        'weekNumber': value['weekNumber'],
    };
}

