/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SetPropResultResponseDto
 */
export interface SetPropResultResponseDto {
    /**
     * Number of correct predictions
     * @type {number}
     * @memberof SetPropResultResponseDto
     */
    correct_predictions_count: number;
    /**
     * Number of incorrect predictions
     * @type {number}
     * @memberof SetPropResultResponseDto
     */
    incorrect_predictions_count: number;
    /**
     * Total number of predictions processed
     * @type {number}
     * @memberof SetPropResultResponseDto
     */
    total_predictions_count: number;
}

/**
 * Check if a given object implements the SetPropResultResponseDto interface.
 */
export function instanceOfSetPropResultResponseDto(value: object): value is SetPropResultResponseDto {
    if (!('correct_predictions_count' in value) || value['correct_predictions_count'] === undefined) return false;
    if (!('incorrect_predictions_count' in value) || value['incorrect_predictions_count'] === undefined) return false;
    if (!('total_predictions_count' in value) || value['total_predictions_count'] === undefined) return false;
    return true;
}

export function SetPropResultResponseDtoFromJSON(json: any): SetPropResultResponseDto {
    return SetPropResultResponseDtoFromJSONTyped(json, false);
}

export function SetPropResultResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPropResultResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'correct_predictions_count': json['correct_predictions_count'],
        'incorrect_predictions_count': json['incorrect_predictions_count'],
        'total_predictions_count': json['total_predictions_count'],
    };
}

export function SetPropResultResponseDtoToJSON(json: any): SetPropResultResponseDto {
    return SetPropResultResponseDtoToJSONTyped(json, false);
}

export function SetPropResultResponseDtoToJSONTyped(value?: SetPropResultResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correct_predictions_count': value['correct_predictions_count'],
        'incorrect_predictions_count': value['incorrect_predictions_count'],
        'total_predictions_count': value['total_predictions_count'],
    };
}

