/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SetPropResultDto
 */
export interface SetPropResultDto {
    /**
     * The outcome UUID (propId) from Goracle
     * @type {string}
     * @memberof SetPropResultDto
     */
    propId: string;
    /**
     * The winning result/choice for the prop
     * @type {string}
     * @memberof SetPropResultDto
     */
    winner: string;
    /**
     * Status of the prop after setting result
     * @type {string}
     * @memberof SetPropResultDto
     */
    status: SetPropResultDtoStatusEnum;
    /**
     * Discord user ID of the admin setting the result
     * @type {string}
     * @memberof SetPropResultDto
     */
    user_id: string;
}


/**
 * @export
 */
export const SetPropResultDtoStatusEnum = {
    Completed: 'completed'
} as const;
export type SetPropResultDtoStatusEnum = typeof SetPropResultDtoStatusEnum[keyof typeof SetPropResultDtoStatusEnum];


/**
 * Check if a given object implements the SetPropResultDto interface.
 */
export function instanceOfSetPropResultDto(value: object): value is SetPropResultDto {
    if (!('propId' in value) || value['propId'] === undefined) return false;
    if (!('winner' in value) || value['winner'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function SetPropResultDtoFromJSON(json: any): SetPropResultDto {
    return SetPropResultDtoFromJSONTyped(json, false);
}

export function SetPropResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPropResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'propId': json['propId'],
        'winner': json['winner'],
        'status': json['status'],
        'user_id': json['user_id'],
    };
}

export function SetPropResultDtoToJSON(json: any): SetPropResultDto {
    return SetPropResultDtoToJSONTyped(json, false);
}

export function SetPropResultDtoToJSONTyped(value?: SetPropResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'propId': value['propId'],
        'winner': value['winner'],
        'status': value['status'],
        'user_id': value['user_id'],
    };
}

