/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SimpleLeaderboardEntryDto
 */
export interface SimpleLeaderboardEntryDto {
    /**
     * User ID
     * @type {string}
     * @memberof SimpleLeaderboardEntryDto
     */
    user_id: string;
    /**
     * Total number of predictions
     * @type {number}
     * @memberof SimpleLeaderboardEntryDto
     */
    total_predictions: number;
    /**
     * Number of correct predictions
     * @type {number}
     * @memberof SimpleLeaderboardEntryDto
     */
    correct_predictions: number;
    /**
     * Number of incorrect predictions
     * @type {number}
     * @memberof SimpleLeaderboardEntryDto
     */
    incorrect_predictions: number;
    /**
     * Success rate as a percentage (0-100)
     * @type {number}
     * @memberof SimpleLeaderboardEntryDto
     */
    success_rate: number;
}

/**
 * Check if a given object implements the SimpleLeaderboardEntryDto interface.
 */
export function instanceOfSimpleLeaderboardEntryDto(value: object): value is SimpleLeaderboardEntryDto {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('total_predictions' in value) || value['total_predictions'] === undefined) return false;
    if (!('correct_predictions' in value) || value['correct_predictions'] === undefined) return false;
    if (!('incorrect_predictions' in value) || value['incorrect_predictions'] === undefined) return false;
    if (!('success_rate' in value) || value['success_rate'] === undefined) return false;
    return true;
}

export function SimpleLeaderboardEntryDtoFromJSON(json: any): SimpleLeaderboardEntryDto {
    return SimpleLeaderboardEntryDtoFromJSONTyped(json, false);
}

export function SimpleLeaderboardEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleLeaderboardEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'total_predictions': json['total_predictions'],
        'correct_predictions': json['correct_predictions'],
        'incorrect_predictions': json['incorrect_predictions'],
        'success_rate': json['success_rate'],
    };
}

export function SimpleLeaderboardEntryDtoToJSON(json: any): SimpleLeaderboardEntryDto {
    return SimpleLeaderboardEntryDtoToJSONTyped(json, false);
}

export function SimpleLeaderboardEntryDtoToJSONTyped(value?: SimpleLeaderboardEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'total_predictions': value['total_predictions'],
        'correct_predictions': value['correct_predictions'],
        'incorrect_predictions': value['incorrect_predictions'],
        'success_rate': value['success_rate'],
    };
}

