/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SimpleLeaderboardEntryDto } from './SimpleLeaderboardEntryDto.js';
import {
    SimpleLeaderboardEntryDtoFromJSON,
    SimpleLeaderboardEntryDtoFromJSONTyped,
    SimpleLeaderboardEntryDtoToJSON,
    SimpleLeaderboardEntryDtoToJSONTyped,
} from './SimpleLeaderboardEntryDto.js';

/**
 * 
 * @export
 * @interface SimpleLeaderboardResponseDto
 */
export interface SimpleLeaderboardResponseDto {
    /**
     * Array of leaderboard entries ranked by success rate
     * @type {Array<SimpleLeaderboardEntryDto>}
     * @memberof SimpleLeaderboardResponseDto
     */
    entries: Array<SimpleLeaderboardEntryDto>;
    /**
     * Total number of users in the leaderboard
     * @type {number}
     * @memberof SimpleLeaderboardResponseDto
     */
    total_users: number;
}

/**
 * Check if a given object implements the SimpleLeaderboardResponseDto interface.
 */
export function instanceOfSimpleLeaderboardResponseDto(value: object): value is SimpleLeaderboardResponseDto {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('total_users' in value) || value['total_users'] === undefined) return false;
    return true;
}

export function SimpleLeaderboardResponseDtoFromJSON(json: any): SimpleLeaderboardResponseDto {
    return SimpleLeaderboardResponseDtoFromJSONTyped(json, false);
}

export function SimpleLeaderboardResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleLeaderboardResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(SimpleLeaderboardEntryDtoFromJSON)),
        'total_users': json['total_users'],
    };
}

export function SimpleLeaderboardResponseDtoToJSON(json: any): SimpleLeaderboardResponseDto {
    return SimpleLeaderboardResponseDtoToJSONTyped(json, false);
}

export function SimpleLeaderboardResponseDtoToJSONTyped(value?: SimpleLeaderboardResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(SimpleLeaderboardEntryDtoToJSON)),
        'total_users': value['total_users'],
    };
}

