/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StoredConfigDto
 */
export interface StoredConfigDto {
    /**
     * Unique identifier for the Discord configuration entry
     * @type {string}
     * @memberof StoredConfigDto
     */
    id: string;
    /**
     * Guild ID associated with the setting
     * @type {string}
     * @memberof StoredConfigDto
     */
    guild_id: string;
    /**
     * Type of setting
     * @type {string}
     * @memberof StoredConfigDto
     */
    setting_type: StoredConfigDtoSettingTypeEnum;
    /**
     * Value of the setting. When the setting type is 'preferred_teams', it is a comma separated list. E.g, 'lakers,hawks'
     * @type {string}
     * @memberof StoredConfigDto
     */
    setting_value: string;
}


/**
 * @export
 */
export const StoredConfigDtoSettingTypeEnum = {
    GamesCategory: 'GAMES_CATEGORY',
    BettingChan: 'BETTING_CHAN',
    DailyScheduleChan: 'DAILY_SCHEDULE_CHAN',
    PredictionsChan: 'PREDICTIONS_CHAN',
    LogsChan: 'LOGS_CHAN',
    LogsEnabled: 'LOGS_ENABLED',
    PreferredTeams: 'PREFERRED_TEAMS'
} as const;
export type StoredConfigDtoSettingTypeEnum = typeof StoredConfigDtoSettingTypeEnum[keyof typeof StoredConfigDtoSettingTypeEnum];


/**
 * Check if a given object implements the StoredConfigDto interface.
 */
export function instanceOfStoredConfigDto(value: object): value is StoredConfigDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('guild_id' in value) || value['guild_id'] === undefined) return false;
    if (!('setting_type' in value) || value['setting_type'] === undefined) return false;
    if (!('setting_value' in value) || value['setting_value'] === undefined) return false;
    return true;
}

export function StoredConfigDtoFromJSON(json: any): StoredConfigDto {
    return StoredConfigDtoFromJSONTyped(json, false);
}

export function StoredConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoredConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'guild_id': json['guild_id'],
        'setting_type': json['setting_type'],
        'setting_value': json['setting_value'],
    };
}

export function StoredConfigDtoToJSON(json: any): StoredConfigDto {
    return StoredConfigDtoToJSONTyped(json, false);
}

export function StoredConfigDtoToJSONTyped(value?: StoredConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'guild_id': value['guild_id'],
        'setting_type': value['setting_type'],
        'setting_value': value['setting_value'],
    };
}

