/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateFooterDto
 */
export interface UpdateFooterDto {
    /**
     * Footer message text
     * @type {string}
     * @memberof UpdateFooterDto
     */
    text?: string;
    /**
     * Category for the footer. Null if announcement.
     * @type {string}
     * @memberof UpdateFooterDto
     */
    category?: UpdateFooterDtoCategoryEnum;
    /**
     * If true, this footer overrides all others when active
     * @type {boolean}
     * @memberof UpdateFooterDto
     */
    isAnnouncement?: boolean;
    /**
     * Whether this footer is active
     * @type {boolean}
     * @memberof UpdateFooterDto
     */
    isActive?: boolean;
    /**
     * Expiration date for the footer (ISO 8601). Footer will be auto-filtered after this date.
     * @type {Date}
     * @memberof UpdateFooterDto
     */
    expiresAt?: Date;
}


/**
 * @export
 */
export const UpdateFooterDtoCategoryEnum = {
    Core: 'core',
    General: 'general',
    Betting: 'betting',
    PlacedBet: 'placedBet',
    HighBetPlaced: 'highBetPlaced',
    LowBetPlaced: 'lowBetPlaced',
    Error: 'error'
} as const;
export type UpdateFooterDtoCategoryEnum = typeof UpdateFooterDtoCategoryEnum[keyof typeof UpdateFooterDtoCategoryEnum];


/**
 * Check if a given object implements the UpdateFooterDto interface.
 */
export function instanceOfUpdateFooterDto(value: object): value is UpdateFooterDto {
    return true;
}

export function UpdateFooterDtoFromJSON(json: any): UpdateFooterDto {
    return UpdateFooterDtoFromJSONTyped(json, false);
}

export function UpdateFooterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFooterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'category': json['category'] == null ? undefined : json['category'],
        'isAnnouncement': json['isAnnouncement'] == null ? undefined : json['isAnnouncement'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function UpdateFooterDtoToJSON(json: any): UpdateFooterDto {
    return UpdateFooterDtoToJSONTyped(json, false);
}

export function UpdateFooterDtoToJSONTyped(value?: UpdateFooterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'category': value['category'],
        'isAnnouncement': value['isAnnouncement'],
        'isActive': value['isActive'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
    };
}

