/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdatePredictionDto
 */
export interface UpdatePredictionDto {
    /**
     * Unique identifier for the prediction
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    id?: string;
    /**
     * User ID
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    user_id?: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof UpdatePredictionDto
     */
    created_at?: Date;
    /**
     * Outcome UUID from Goracle
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    outcome_uuid?: string;
    /**
     * Event ID from Goracle
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    event_id?: string;
    /**
     * Market ID from Goracle - used for grouping paired outcomes
     * @type {number}
     * @memberof UpdatePredictionDto
     */
    market_id?: number;
    /**
     * Sport key
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    sport?: string;
    /**
     * User's choice
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    choice?: string;
    /**
     * Whether the prediction is correct
     * @type {boolean}
     * @memberof UpdatePredictionDto
     */
    is_correct?: boolean | null;
    /**
     * Status of the prediction
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    status?: UpdatePredictionDtoStatusEnum;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof UpdatePredictionDto
     */
    updated_at?: Date;
    /**
     * Guild ID
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    guild_id?: string;
    /**
     * Market key
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    market_key?: string;
    /**
     * Bookmaker key
     * @type {string}
     * @memberof UpdatePredictionDto
     */
    bookmaker_key?: string;
}


/**
 * @export
 */
export const UpdatePredictionDtoStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Error: 'error'
} as const;
export type UpdatePredictionDtoStatusEnum = typeof UpdatePredictionDtoStatusEnum[keyof typeof UpdatePredictionDtoStatusEnum];


/**
 * Check if a given object implements the UpdatePredictionDto interface.
 */
export function instanceOfUpdatePredictionDto(value: object): value is UpdatePredictionDto {
    return true;
}

export function UpdatePredictionDtoFromJSON(json: any): UpdatePredictionDto {
    return UpdatePredictionDtoFromJSONTyped(json, false);
}

export function UpdatePredictionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePredictionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'user_id': json['user_id'] == null ? undefined : json['user_id'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'outcome_uuid': json['outcome_uuid'] == null ? undefined : json['outcome_uuid'],
        'event_id': json['event_id'] == null ? undefined : json['event_id'],
        'market_id': json['market_id'] == null ? undefined : json['market_id'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'choice': json['choice'] == null ? undefined : json['choice'],
        'is_correct': json['is_correct'] == null ? undefined : json['is_correct'],
        'status': json['status'] == null ? undefined : json['status'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'guild_id': json['guild_id'] == null ? undefined : json['guild_id'],
        'market_key': json['market_key'] == null ? undefined : json['market_key'],
        'bookmaker_key': json['bookmaker_key'] == null ? undefined : json['bookmaker_key'],
    };
}

export function UpdatePredictionDtoToJSON(json: any): UpdatePredictionDto {
    return UpdatePredictionDtoToJSONTyped(json, false);
}

export function UpdatePredictionDtoToJSONTyped(value?: UpdatePredictionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'outcome_uuid': value['outcome_uuid'],
        'event_id': value['event_id'],
        'market_id': value['market_id'],
        'sport': value['sport'],
        'choice': value['choice'],
        'is_correct': value['is_correct'],
        'status': value['status'],
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
        'guild_id': value['guild_id'],
        'market_key': value['market_key'],
        'bookmaker_key': value['bookmaker_key'],
    };
}

