/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserProfile404Response
 */
export interface UserProfile404Response {
    /**
     * 
     * @type {any}
     * @memberof UserProfile404Response
     */
    statusCode: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserProfile404Response
     */
    message: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserProfile404Response
     */
    exception: any | null;
}

/**
 * Check if a given object implements the UserProfile404Response interface.
 */
export function instanceOfUserProfile404Response(value: object): value is UserProfile404Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('exception' in value) || value['exception'] === undefined) return false;
    return true;
}

export function UserProfile404ResponseFromJSON(json: any): UserProfile404Response {
    return UserProfile404ResponseFromJSONTyped(json, false);
}

export function UserProfile404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'exception': json['exception'],
    };
}

export function UserProfile404ResponseToJSON(json: any): UserProfile404Response {
    return UserProfile404ResponseToJSONTyped(json, false);
}

export function UserProfile404ResponseToJSONTyped(value?: UserProfile404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'exception': value['exception'],
    };
}

