/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookAcceptedResponseDto
 */
export interface WebhookAcceptedResponseDto {
    /**
     * Status of webhook acceptance
     * @type {string}
     * @memberof WebhookAcceptedResponseDto
     */
    status: WebhookAcceptedResponseDtoStatusEnum;
    /**
     * Correlation ID for tracking this webhook through the system
     * @type {string}
     * @memberof WebhookAcceptedResponseDto
     */
    correlation_id: string;
    /**
     * Optional note about processing (e.g., duplicate detection)
     * @type {string}
     * @memberof WebhookAcceptedResponseDto
     */
    note?: string;
}


/**
 * @export
 */
export const WebhookAcceptedResponseDtoStatusEnum = {
    Accepted: 'accepted'
} as const;
export type WebhookAcceptedResponseDtoStatusEnum = typeof WebhookAcceptedResponseDtoStatusEnum[keyof typeof WebhookAcceptedResponseDtoStatusEnum];


/**
 * Check if a given object implements the WebhookAcceptedResponseDto interface.
 */
export function instanceOfWebhookAcceptedResponseDto(value: object): value is WebhookAcceptedResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('correlation_id' in value) || value['correlation_id'] === undefined) return false;
    return true;
}

export function WebhookAcceptedResponseDtoFromJSON(json: any): WebhookAcceptedResponseDto {
    return WebhookAcceptedResponseDtoFromJSONTyped(json, false);
}

export function WebhookAcceptedResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAcceptedResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'correlation_id': json['correlation_id'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function WebhookAcceptedResponseDtoToJSON(json: any): WebhookAcceptedResponseDto {
    return WebhookAcceptedResponseDtoToJSONTyped(json, false);
}

export function WebhookAcceptedResponseDtoToJSONTyped(value?: WebhookAcceptedResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'correlation_id': value['correlation_id'],
        'note': value['note'],
    };
}

