/* tslint:disable */
/* eslint-disable */
/**
 * Khronos API Documentation
 * Khronos is a sports-focused API that integrates with my other app, Pluto for Discord.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookHealthResponseDto
 */
export interface WebhookHealthResponseDto {
    /**
     * Health status of the webhook endpoint
     * @type {string}
     * @memberof WebhookHealthResponseDto
     */
    status: WebhookHealthResponseDtoStatusEnum;
    /**
     * Service identifier
     * @type {string}
     * @memberof WebhookHealthResponseDto
     */
    service: string;
    /**
     * Timestamp of the health check
     * @type {string}
     * @memberof WebhookHealthResponseDto
     */
    timestamp: string;
}


/**
 * @export
 */
export const WebhookHealthResponseDtoStatusEnum = {
    Ok: 'ok'
} as const;
export type WebhookHealthResponseDtoStatusEnum = typeof WebhookHealthResponseDtoStatusEnum[keyof typeof WebhookHealthResponseDtoStatusEnum];


/**
 * Check if a given object implements the WebhookHealthResponseDto interface.
 */
export function instanceOfWebhookHealthResponseDto(value: object): value is WebhookHealthResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WebhookHealthResponseDtoFromJSON(json: any): WebhookHealthResponseDto {
    return WebhookHealthResponseDtoFromJSONTyped(json, false);
}

export function WebhookHealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookHealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'service': json['service'],
        'timestamp': json['timestamp'],
    };
}

export function WebhookHealthResponseDtoToJSON(json: any): WebhookHealthResponseDto {
    return WebhookHealthResponseDtoToJSONTyped(json, false);
}

export function WebhookHealthResponseDtoToJSONTyped(value?: WebhookHealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'timestamp': value['timestamp'],
    };
}

