/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  HttpCollectAllOddsResponse,
  HttpCollectOddsResponse,
  HttpErrorResponse,
} from '../models/index.js';
import {
    HttpCollectAllOddsResponseFromJSON,
    HttpCollectAllOddsResponseToJSON,
    HttpCollectOddsResponseFromJSON,
    HttpCollectOddsResponseToJSON,
    HttpErrorResponseFromJSON,
    HttpErrorResponseToJSON,
} from '../models/index.js';

export interface CollectAllOddsRequest {
    force?: boolean;
}

export interface CollectOddsRequest {
    sport: CollectOddsSportEnum;
    force?: boolean;
}

/**
 * CollectionApi - interface
 * 
 * @export
 * @interface CollectionApiInterface
 */
export interface CollectionApiInterface {
    /**
     * Trigger manual odds collection for all supported sports
     * @summary Collect odds for all sports
     * @param {boolean} [force] Force collection bypassing freshness checks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectAllOddsRaw(requestParameters: CollectAllOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpCollectAllOddsResponse>>;

    /**
     * Trigger manual odds collection for all supported sports
     * Collect odds for all sports
     */
    collectAllOdds(requestParameters: CollectAllOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpCollectAllOddsResponse>;

    /**
     * Trigger manual odds collection for a specific sport (nba or nfl)
     * @summary Collect odds for a sport
     * @param {'nba' | 'nfl'} sport Sport key
     * @param {boolean} [force] Force collection bypassing freshness checks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectOddsRaw(requestParameters: CollectOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpCollectOddsResponse>>;

    /**
     * Trigger manual odds collection for a specific sport (nba or nfl)
     * Collect odds for a sport
     */
    collectOdds(requestParameters: CollectOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpCollectOddsResponse>;

}

/**
 * 
 */
export class CollectionApi extends runtime.BaseAPI implements CollectionApiInterface {

    /**
     * Trigger manual odds collection for all supported sports
     * Collect odds for all sports
     */
    async collectAllOddsRaw(requestParameters: CollectAllOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpCollectAllOddsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/collect/all`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpCollectAllOddsResponseFromJSON(jsonValue));
    }

    /**
     * Trigger manual odds collection for all supported sports
     * Collect odds for all sports
     */
    async collectAllOdds(requestParameters: CollectAllOddsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpCollectAllOddsResponse> {
        const response = await this.collectAllOddsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger manual odds collection for a specific sport (nba or nfl)
     * Collect odds for a sport
     */
    async collectOddsRaw(requestParameters: CollectOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpCollectOddsResponse>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling collectOdds().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/collect`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpCollectOddsResponseFromJSON(jsonValue));
    }

    /**
     * Trigger manual odds collection for a specific sport (nba or nfl)
     * Collect odds for a sport
     */
    async collectOdds(requestParameters: CollectOddsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpCollectOddsResponse> {
        const response = await this.collectOddsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CollectOddsSportEnum = {
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type CollectOddsSportEnum = typeof CollectOddsSportEnum[keyof typeof CollectOddsSportEnum];
