/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  HttpErrorResponse,
  HttpManualSettleEventResponse,
  HttpManualSettleRequest,
  HttpResolveStaleEventResponse,
} from '../models/index.js';
import {
    HttpErrorResponseFromJSON,
    HttpErrorResponseToJSON,
    HttpManualSettleEventResponseFromJSON,
    HttpManualSettleEventResponseToJSON,
    HttpManualSettleRequestFromJSON,
    HttpManualSettleRequestToJSON,
    HttpResolveStaleEventResponseFromJSON,
    HttpResolveStaleEventResponseToJSON,
} from '../models/index.js';

export interface ManualSettleEventRequest {
    eventId: string;
    request: HttpManualSettleRequest;
}

export interface ResolveStaleEventRequest {
    eventId: string;
}

/**
 * EventsApi - interface
 * 
 * @export
 * @interface EventsApiInterface
 */
export interface EventsApiInterface {
    /**
     * Manually settle an event with final scores for all H2H markets
     * @summary Manually settle an event
     * @param {string} eventId Event ID
     * @param {HttpManualSettleRequest} request Settlement request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    manualSettleEventRaw(requestParameters: ManualSettleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpManualSettleEventResponse>>;

    /**
     * Manually settle an event with final scores for all H2H markets
     * Manually settle an event
     */
    manualSettleEvent(requestParameters: ManualSettleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpManualSettleEventResponse>;

    /**
     * Trigger one-time API call to resolve a stale event by ID (NO RETRIES)
     * @summary Manually resolve stale event
     * @param {string} eventId Event ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    resolveStaleEventRaw(requestParameters: ResolveStaleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpResolveStaleEventResponse>>;

    /**
     * Trigger one-time API call to resolve a stale event by ID (NO RETRIES)
     * Manually resolve stale event
     */
    resolveStaleEvent(requestParameters: ResolveStaleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpResolveStaleEventResponse>;

}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI implements EventsApiInterface {

    /**
     * Manually settle an event with final scores for all H2H markets
     * Manually settle an event
     */
    async manualSettleEventRaw(requestParameters: ManualSettleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpManualSettleEventResponse>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling manualSettleEvent().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling manualSettleEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/events/{eventId}/manual-settle`.replace(`{${"eventId"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HttpManualSettleRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpManualSettleEventResponseFromJSON(jsonValue));
    }

    /**
     * Manually settle an event with final scores for all H2H markets
     * Manually settle an event
     */
    async manualSettleEvent(requestParameters: ManualSettleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpManualSettleEventResponse> {
        const response = await this.manualSettleEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger one-time API call to resolve a stale event by ID (NO RETRIES)
     * Manually resolve stale event
     */
    async resolveStaleEventRaw(requestParameters: ResolveStaleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpResolveStaleEventResponse>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling resolveStaleEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/events/{eventId}/resolve-stale`.replace(`{${"eventId"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpResolveStaleEventResponseFromJSON(jsonValue));
    }

    /**
     * Trigger one-time API call to resolve a stale event by ID (NO RETRIES)
     * Manually resolve stale event
     */
    async resolveStaleEvent(requestParameters: ResolveStaleEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpResolveStaleEventResponse> {
        const response = await this.resolveStaleEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
