/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  HttpErrorResponse,
  HttpEventDetail,
  HttpGetMatchesResponse,
  HttpGetMultipleMatchDetailsResponse,
} from '../models/index.js';
import {
    HttpErrorResponseFromJSON,
    HttpErrorResponseToJSON,
    HttpEventDetailFromJSON,
    HttpEventDetailToJSON,
    HttpGetMatchesResponseFromJSON,
    HttpGetMatchesResponseToJSON,
    HttpGetMultipleMatchDetailsResponseFromJSON,
    HttpGetMultipleMatchDetailsResponseToJSON,
} from '../models/index.js';

export interface GetMatchDetailsRequest {
    eventId: string;
    market?: string;
}

export interface GetMatchesRequest {
    sport: GetMatchesSportEnum;
    from?: string;
    to?: string;
}

export interface GetMultipleMatchDetailsRequest {
    sport: string;
    ids: string;
}

/**
 * MatchesApi - interface
 * 
 * @export
 * @interface MatchesApiInterface
 */
export interface MatchesApiInterface {
    /**
     * Returns event with full details including all markets and outcomes. Use market query parameter to filter to specific market types (e.g., market=h2h for head-to-head only, market=spreads,totals for multiple markets). Defaults to H2H-only market filtering when no market parameter is provided. Completed events include computed winner field. H2H odds (home_team_odds and away_team_odds) are included when available in American odds format (e.g., -192 for favorites, +160 for underdogs). Odds fields are omitted from the response when unavailable.
     * @summary Get match details
     * @param {string} eventId Event ID
     * @param {string} [market] Market filter (e.g., \&#39;h2h\&#39;, \&#39;spreads\&#39;, \&#39;totals\&#39;, or comma-separated \&#39;spreads,totals\&#39;). Defaults to \&#39;h2h\&#39; if not provided.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApiInterface
     */
    getMatchDetailsRaw(requestParameters: GetMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpEventDetail>>;

    /**
     * Returns event with full details including all markets and outcomes. Use market query parameter to filter to specific market types (e.g., market=h2h for head-to-head only, market=spreads,totals for multiple markets). Defaults to H2H-only market filtering when no market parameter is provided. Completed events include computed winner field. H2H odds (home_team_odds and away_team_odds) are included when available in American odds format (e.g., -192 for favorites, +160 for underdogs). Odds fields are omitted from the response when unavailable.
     * Get match details
     */
    getMatchDetails(requestParameters: GetMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpEventDetail>;

    /**
     * Returns matches within a specified time window with flexible sport matching and timezone handling. H2H odds are included at the top level when available.  **Sport Matching (Flexible & Case-Insensitive):** - Accepts multiple formats: \"nba\", \"NBA\", \"basketball_nba\" all match NBA games - Accepts multiple formats: \"nfl\", \"NFL\", \"americanfootball_nfl\" all match NFL games - Matches against both sport_title and sport_key fields (case-insensitive) - Input is normalized (lowercase, trimmed whitespace) before matching  **H2H Odds (Included When Available):** - home_team_odds and away_team_odds are included in each match when available - Odds use American odds format (e.g., -192 for favorites, +160 for underdogs) - Odds fields are omitted from the response when unavailable (e.g., event not yet published, market suspended) - Example: {\"home_team_odds\": -192, \"away_team_odds\": 160} or fields omitted entirely when unavailable  **Timezone Handling (ISO 8601 Format):** - Input timestamps must be in ISO 8601 format (e.g., 2025-11-04T03:10:00Z) - Timestamps without timezone indicator are assumed to be UTC - Timestamps with timezone offset are converted to UTC (e.g., 2025-11-04T03:10:00-05:00) - Output timestamps are always returned in ISO 8601 format with UTC indicator (Z) - Example formats: \"2025-11-04T03:10:00Z\", \"2025-11-04T03:10:00.000Z\", \"2025-11-04T03:10:00-05:00\"  **Performance & Limits:** - Maximum 1000 matches returned per request to prevent memory issues - Results ordered by commence_time ascending - Typical response time: < 500ms for 1-hour to 7-day windows  **Error Responses:** - 400 Bad Request: Missing required parameters (sport, from, to) - 400 Bad Request: Invalid ISO 8601 timestamp format - 400 Bad Request: \'from\' timestamp is after \'to\' timestamp - 500 Internal Server Error: Database or system errors
     * @summary Get matches for a sport
     * @param {'basketball_nba' | 'americanfootball_nfl' | 'nba' | 'nfl'} sport Sport key (case-insensitive, matches sport_title or sport_key). Examples: \&#39;nba\&#39;, \&#39;NBA\&#39;, \&#39;basketball_nba\&#39;, \&#39;nfl\&#39;, \&#39;NFL\&#39;, \&#39;americanfootball_nfl\&#39;
     * @param {string} [from] Start of time window in ISO 8601 format. UTC assumed if no timezone. Examples: \&#39;2025-11-04T03:10:00Z\&#39;, \&#39;2025-11-04T03:10:00-05:00\&#39;. Defaults to now.
     * @param {string} [to] End of time window in ISO 8601 format. UTC assumed if no timezone. Examples: \&#39;2025-11-04T04:10:00Z\&#39;, \&#39;2025-11-04T04:10:00+00:00\&#39;. Defaults to 7 days from now.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApiInterface
     */
    getMatchesRaw(requestParameters: GetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetMatchesResponse>>;

    /**
     * Returns matches within a specified time window with flexible sport matching and timezone handling. H2H odds are included at the top level when available.  **Sport Matching (Flexible & Case-Insensitive):** - Accepts multiple formats: \"nba\", \"NBA\", \"basketball_nba\" all match NBA games - Accepts multiple formats: \"nfl\", \"NFL\", \"americanfootball_nfl\" all match NFL games - Matches against both sport_title and sport_key fields (case-insensitive) - Input is normalized (lowercase, trimmed whitespace) before matching  **H2H Odds (Included When Available):** - home_team_odds and away_team_odds are included in each match when available - Odds use American odds format (e.g., -192 for favorites, +160 for underdogs) - Odds fields are omitted from the response when unavailable (e.g., event not yet published, market suspended) - Example: {\"home_team_odds\": -192, \"away_team_odds\": 160} or fields omitted entirely when unavailable  **Timezone Handling (ISO 8601 Format):** - Input timestamps must be in ISO 8601 format (e.g., 2025-11-04T03:10:00Z) - Timestamps without timezone indicator are assumed to be UTC - Timestamps with timezone offset are converted to UTC (e.g., 2025-11-04T03:10:00-05:00) - Output timestamps are always returned in ISO 8601 format with UTC indicator (Z) - Example formats: \"2025-11-04T03:10:00Z\", \"2025-11-04T03:10:00.000Z\", \"2025-11-04T03:10:00-05:00\"  **Performance & Limits:** - Maximum 1000 matches returned per request to prevent memory issues - Results ordered by commence_time ascending - Typical response time: < 500ms for 1-hour to 7-day windows  **Error Responses:** - 400 Bad Request: Missing required parameters (sport, from, to) - 400 Bad Request: Invalid ISO 8601 timestamp format - 400 Bad Request: \'from\' timestamp is after \'to\' timestamp - 500 Internal Server Error: Database or system errors
     * Get matches for a sport
     */
    getMatches(requestParameters: GetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetMatchesResponse>;

    /**
     * Returns multiple events with simplified details for efficient bulk queries (max 50)
     * @summary Get multiple match details
     * @param {string} sport Sport key
     * @param {string} ids Comma-separated event IDs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApiInterface
     */
    getMultipleMatchDetailsRaw(requestParameters: GetMultipleMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetMultipleMatchDetailsResponse>>;

    /**
     * Returns multiple events with simplified details for efficient bulk queries (max 50)
     * Get multiple match details
     */
    getMultipleMatchDetails(requestParameters: GetMultipleMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetMultipleMatchDetailsResponse>;

}

/**
 * 
 */
export class MatchesApi extends runtime.BaseAPI implements MatchesApiInterface {

    /**
     * Returns event with full details including all markets and outcomes. Use market query parameter to filter to specific market types (e.g., market=h2h for head-to-head only, market=spreads,totals for multiple markets). Defaults to H2H-only market filtering when no market parameter is provided. Completed events include computed winner field. H2H odds (home_team_odds and away_team_odds) are included when available in American odds format (e.g., -192 for favorites, +160 for underdogs). Odds fields are omitted from the response when unavailable.
     * Get match details
     */
    async getMatchDetailsRaw(requestParameters: GetMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpEventDetail>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getMatchDetails().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['market'] != null) {
            queryParameters['market'] = requestParameters['market'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/events/{eventId}`.replace(`{${"eventId"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpEventDetailFromJSON(jsonValue));
    }

    /**
     * Returns event with full details including all markets and outcomes. Use market query parameter to filter to specific market types (e.g., market=h2h for head-to-head only, market=spreads,totals for multiple markets). Defaults to H2H-only market filtering when no market parameter is provided. Completed events include computed winner field. H2H odds (home_team_odds and away_team_odds) are included when available in American odds format (e.g., -192 for favorites, +160 for underdogs). Odds fields are omitted from the response when unavailable.
     * Get match details
     */
    async getMatchDetails(requestParameters: GetMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpEventDetail> {
        const response = await this.getMatchDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns matches within a specified time window with flexible sport matching and timezone handling. H2H odds are included at the top level when available.  **Sport Matching (Flexible & Case-Insensitive):** - Accepts multiple formats: \"nba\", \"NBA\", \"basketball_nba\" all match NBA games - Accepts multiple formats: \"nfl\", \"NFL\", \"americanfootball_nfl\" all match NFL games - Matches against both sport_title and sport_key fields (case-insensitive) - Input is normalized (lowercase, trimmed whitespace) before matching  **H2H Odds (Included When Available):** - home_team_odds and away_team_odds are included in each match when available - Odds use American odds format (e.g., -192 for favorites, +160 for underdogs) - Odds fields are omitted from the response when unavailable (e.g., event not yet published, market suspended) - Example: {\"home_team_odds\": -192, \"away_team_odds\": 160} or fields omitted entirely when unavailable  **Timezone Handling (ISO 8601 Format):** - Input timestamps must be in ISO 8601 format (e.g., 2025-11-04T03:10:00Z) - Timestamps without timezone indicator are assumed to be UTC - Timestamps with timezone offset are converted to UTC (e.g., 2025-11-04T03:10:00-05:00) - Output timestamps are always returned in ISO 8601 format with UTC indicator (Z) - Example formats: \"2025-11-04T03:10:00Z\", \"2025-11-04T03:10:00.000Z\", \"2025-11-04T03:10:00-05:00\"  **Performance & Limits:** - Maximum 1000 matches returned per request to prevent memory issues - Results ordered by commence_time ascending - Typical response time: < 500ms for 1-hour to 7-day windows  **Error Responses:** - 400 Bad Request: Missing required parameters (sport, from, to) - 400 Bad Request: Invalid ISO 8601 timestamp format - 400 Bad Request: \'from\' timestamp is after \'to\' timestamp - 500 Internal Server Error: Database or system errors
     * Get matches for a sport
     */
    async getMatchesRaw(requestParameters: GetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetMatchesResponse>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getMatches().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/matches/{sport}`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpGetMatchesResponseFromJSON(jsonValue));
    }

    /**
     * Returns matches within a specified time window with flexible sport matching and timezone handling. H2H odds are included at the top level when available.  **Sport Matching (Flexible & Case-Insensitive):** - Accepts multiple formats: \"nba\", \"NBA\", \"basketball_nba\" all match NBA games - Accepts multiple formats: \"nfl\", \"NFL\", \"americanfootball_nfl\" all match NFL games - Matches against both sport_title and sport_key fields (case-insensitive) - Input is normalized (lowercase, trimmed whitespace) before matching  **H2H Odds (Included When Available):** - home_team_odds and away_team_odds are included in each match when available - Odds use American odds format (e.g., -192 for favorites, +160 for underdogs) - Odds fields are omitted from the response when unavailable (e.g., event not yet published, market suspended) - Example: {\"home_team_odds\": -192, \"away_team_odds\": 160} or fields omitted entirely when unavailable  **Timezone Handling (ISO 8601 Format):** - Input timestamps must be in ISO 8601 format (e.g., 2025-11-04T03:10:00Z) - Timestamps without timezone indicator are assumed to be UTC - Timestamps with timezone offset are converted to UTC (e.g., 2025-11-04T03:10:00-05:00) - Output timestamps are always returned in ISO 8601 format with UTC indicator (Z) - Example formats: \"2025-11-04T03:10:00Z\", \"2025-11-04T03:10:00.000Z\", \"2025-11-04T03:10:00-05:00\"  **Performance & Limits:** - Maximum 1000 matches returned per request to prevent memory issues - Results ordered by commence_time ascending - Typical response time: < 500ms for 1-hour to 7-day windows  **Error Responses:** - 400 Bad Request: Missing required parameters (sport, from, to) - 400 Bad Request: Invalid ISO 8601 timestamp format - 400 Bad Request: \'from\' timestamp is after \'to\' timestamp - 500 Internal Server Error: Database or system errors
     * Get matches for a sport
     */
    async getMatches(requestParameters: GetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetMatchesResponse> {
        const response = await this.getMatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns multiple events with simplified details for efficient bulk queries (max 50)
     * Get multiple match details
     */
    async getMultipleMatchDetailsRaw(requestParameters: GetMultipleMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetMultipleMatchDetailsResponse>> {
        if (requestParameters['sport'] == null) {
            throw new runtime.RequiredError(
                'sport',
                'Required parameter "sport" was null or undefined when calling getMultipleMatchDetails().'
            );
        }

        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling getMultipleMatchDetails().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/matches/{sport}/bulk`.replace(`{${"sport"}}`, encodeURIComponent(String(requestParameters['sport']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpGetMultipleMatchDetailsResponseFromJSON(jsonValue));
    }

    /**
     * Returns multiple events with simplified details for efficient bulk queries (max 50)
     * Get multiple match details
     */
    async getMultipleMatchDetails(requestParameters: GetMultipleMatchDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetMultipleMatchDetailsResponse> {
        const response = await this.getMultipleMatchDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetMatchesSportEnum = {
    BasketballNba: 'basketball_nba',
    AmericanfootballNfl: 'americanfootball_nfl',
    Nba: 'nba',
    Nfl: 'nfl'
} as const;
export type GetMatchesSportEnum = typeof GetMatchesSportEnum[keyof typeof GetMatchesSportEnum];
