/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  HttpErrorResponse,
  HttpGetOutcomesByEventResponse,
  HttpOutcomeDetailResponse,
  HttpSettleOutcomeRequest,
  HttpSettleOutcomeResponse,
} from '../models/index.js';
import {
    HttpErrorResponseFromJSON,
    HttpErrorResponseToJSON,
    HttpGetOutcomesByEventResponseFromJSON,
    HttpGetOutcomesByEventResponseToJSON,
    HttpOutcomeDetailResponseFromJSON,
    HttpOutcomeDetailResponseToJSON,
    HttpSettleOutcomeRequestFromJSON,
    HttpSettleOutcomeRequestToJSON,
    HttpSettleOutcomeResponseFromJSON,
    HttpSettleOutcomeResponseToJSON,
} from '../models/index.js';

export interface GetOutcomeByUUIDRequest {
    uuid: string;
}

export interface GetOutcomesByEventRequest {
    eventId: string;
}

export interface SettleOutcomeRequest {
    uuid: string;
    request: HttpSettleOutcomeRequest;
}

/**
 * OutcomesApi - interface
 * 
 * @export
 * @interface OutcomesApiInterface
 */
export interface OutcomesApiInterface {
    /**
     * Returns a single outcome by UUID - used by Khronos to validate predictions
     * @summary Get outcome by UUID
     * @param {string} uuid Outcome UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OutcomesApiInterface
     */
    getOutcomeByUUIDRaw(requestParameters: GetOutcomeByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpOutcomeDetailResponse>>;

    /**
     * Returns a single outcome by UUID - used by Khronos to validate predictions
     * Get outcome by UUID
     */
    getOutcomeByUUID(requestParameters: GetOutcomeByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpOutcomeDetailResponse>;

    /**
     * Returns all outcomes for a given event across all markets and bookmakers
     * @summary Get outcomes by event
     * @param {string} eventId Event ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OutcomesApiInterface
     */
    getOutcomesByEventRaw(requestParameters: GetOutcomesByEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetOutcomesByEventResponse>>;

    /**
     * Returns all outcomes for a given event across all markets and bookmakers
     * Get outcomes by event
     */
    getOutcomesByEvent(requestParameters: GetOutcomesByEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetOutcomesByEventResponse>;

    /**
     * Manually settles an outcome - used primarily for player props
     * @summary Manually settle an outcome
     * @param {string} uuid Outcome UUID
     * @param {HttpSettleOutcomeRequest} request Settlement request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OutcomesApiInterface
     */
    settleOutcomeRaw(requestParameters: SettleOutcomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpSettleOutcomeResponse>>;

    /**
     * Manually settles an outcome - used primarily for player props
     * Manually settle an outcome
     */
    settleOutcome(requestParameters: SettleOutcomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpSettleOutcomeResponse>;

}

/**
 * 
 */
export class OutcomesApi extends runtime.BaseAPI implements OutcomesApiInterface {

    /**
     * Returns a single outcome by UUID - used by Khronos to validate predictions
     * Get outcome by UUID
     */
    async getOutcomeByUUIDRaw(requestParameters: GetOutcomeByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpOutcomeDetailResponse>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getOutcomeByUUID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/outcomes/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpOutcomeDetailResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single outcome by UUID - used by Khronos to validate predictions
     * Get outcome by UUID
     */
    async getOutcomeByUUID(requestParameters: GetOutcomeByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpOutcomeDetailResponse> {
        const response = await this.getOutcomeByUUIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all outcomes for a given event across all markets and bookmakers
     * Get outcomes by event
     */
    async getOutcomesByEventRaw(requestParameters: GetOutcomesByEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpGetOutcomesByEventResponse>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getOutcomesByEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/outcomes/event/{eventId}`.replace(`{${"eventId"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpGetOutcomesByEventResponseFromJSON(jsonValue));
    }

    /**
     * Returns all outcomes for a given event across all markets and bookmakers
     * Get outcomes by event
     */
    async getOutcomesByEvent(requestParameters: GetOutcomesByEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpGetOutcomesByEventResponse> {
        const response = await this.getOutcomesByEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Manually settles an outcome - used primarily for player props
     * Manually settle an outcome
     */
    async settleOutcomeRaw(requestParameters: SettleOutcomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HttpSettleOutcomeResponse>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling settleOutcome().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling settleOutcome().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/outcomes/{uuid}/settle`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HttpSettleOutcomeRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HttpSettleOutcomeResponseFromJSON(jsonValue));
    }

    /**
     * Manually settles an outcome - used primarily for player props
     * Manually settle an outcome
     */
    async settleOutcome(requestParameters: SettleOutcomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HttpSettleOutcomeResponse> {
        const response = await this.settleOutcomeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
