export enum MarketKeyAbbreviations {
	player_pass_tds = 'PTD',
	player_pass_yds = 'PYD',
	player_pass_completions = 'CMP',
	player_pass_attempts = 'ATT',
	player_pass_interceptions = 'INT',
	player_pass_longest_completion = 'LNG',
	player_rush_yds = 'RYD',
	player_reception_yds = 'REY',
	player_receptions = 'REC',
	player_rush_attempts = 'CAR',
	player_rush_longest = 'LNG',
	player_kicking_points = 'PTS',
	player_field_goals = 'FGM',
	player_tackles_assists = 'TKL',
	player_1st_td = '1TD',
	player_last_td = 'LTD',
	player_anytime_td = 'ATD',
	player_pass_tds_alternate = 'PTD',
	player_pass_yds_alternate = 'PYD',
	player_rush_yds_alternate = 'RYD',
	player_rush_reception_yds_alternate = 'YFS',
	player_reception_yds_alternate = 'REY',
	player_receptions_alternate = 'REC',
}
