/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainOutcomeType = {
    /**
    * 
    */
    OutcomeOver: 'OVER',
    /**
    * 
    */
    OutcomeUnder: 'UNDER',
    /**
    * 
    */
    OutcomeTeamHome: 'TEAM_HOME',
    /**
    * 
    */
    OutcomeTeamAway: 'TEAM_AWAY',
    /**
    * Future: binary props
    */
    OutcomeYes: 'YES',
    /**
    * Future: binary props
    */
    OutcomeNo: 'NO'
} as const;
export type DomainOutcomeType = typeof DomainOutcomeType[keyof typeof DomainOutcomeType];


export function instanceOfDomainOutcomeType(value: any): boolean {
    for (const key in DomainOutcomeType) {
        if (Object.prototype.hasOwnProperty.call(DomainOutcomeType, key)) {
            if (DomainOutcomeType[key as keyof typeof DomainOutcomeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainOutcomeTypeFromJSON(json: any): DomainOutcomeType {
    return DomainOutcomeTypeFromJSONTyped(json, false);
}

export function DomainOutcomeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainOutcomeType {
    return json as DomainOutcomeType;
}

export function DomainOutcomeTypeToJSON(value?: DomainOutcomeType | null): any {
    return value as any;
}

export function DomainOutcomeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainOutcomeType {
    return value as DomainOutcomeType;
}

