/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpSettleOutcomeRequest
 */
export interface HttpSettleOutcomeRequest {
    /**
     * 
     * @type {number}
     * @memberof HttpSettleOutcomeRequest
     */
    actual_value?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpSettleOutcomeRequest
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpSettleOutcomeRequest
     */
    result: string;
}

/**
 * Check if a given object implements the HttpSettleOutcomeRequest interface.
 */
export function instanceOfHttpSettleOutcomeRequest(value: object): value is HttpSettleOutcomeRequest {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function HttpSettleOutcomeRequestFromJSON(json: any): HttpSettleOutcomeRequest {
    return HttpSettleOutcomeRequestFromJSONTyped(json, false);
}

export function HttpSettleOutcomeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpSettleOutcomeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'actual_value': json['actual_value'] == null ? undefined : json['actual_value'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'result': json['result'],
    };
}

export function HttpSettleOutcomeRequestToJSON(json: any): HttpSettleOutcomeRequest {
    return HttpSettleOutcomeRequestToJSONTyped(json, false);
}

export function HttpSettleOutcomeRequestToJSONTyped(value?: HttpSettleOutcomeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual_value': value['actual_value'],
        'reason': value['reason'],
        'result': value['result'],
    };
}

