/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HttpRawPropResponse } from './HttpRawPropResponse.js';
import {
    HttpRawPropResponseFromJSON,
    HttpRawPropResponseFromJSONTyped,
    HttpRawPropResponseToJSON,
    HttpRawPropResponseToJSONTyped,
} from './HttpRawPropResponse.js';

/**
 * 
 * @export
 * @interface HttpGetAvailablePropsResponse
 */
export interface HttpGetAvailablePropsResponse {
    /**
     * 
     * @type {number}
     * @memberof HttpGetAvailablePropsResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpGetAvailablePropsResponse
     */
    from?: string;
    /**
     * 
     * @type {Array<HttpRawPropResponse>}
     * @memberof HttpGetAvailablePropsResponse
     */
    props?: Array<HttpRawPropResponse>;
    /**
     * 
     * @type {string}
     * @memberof HttpGetAvailablePropsResponse
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpGetAvailablePropsResponse
     */
    to?: string;
}

/**
 * Check if a given object implements the HttpGetAvailablePropsResponse interface.
 */
export function instanceOfHttpGetAvailablePropsResponse(value: object): value is HttpGetAvailablePropsResponse {
    return true;
}

export function HttpGetAvailablePropsResponseFromJSON(json: any): HttpGetAvailablePropsResponse {
    return HttpGetAvailablePropsResponseFromJSONTyped(json, false);
}

export function HttpGetAvailablePropsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpGetAvailablePropsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'from': json['from'] == null ? undefined : json['from'],
        'props': json['props'] == null ? undefined : ((json['props'] as Array<any>).map(HttpRawPropResponseFromJSON)),
        'sport': json['sport'] == null ? undefined : json['sport'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function HttpGetAvailablePropsResponseToJSON(json: any): HttpGetAvailablePropsResponse {
    return HttpGetAvailablePropsResponseToJSONTyped(json, false);
}

export function HttpGetAvailablePropsResponseToJSONTyped(value?: HttpGetAvailablePropsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'from': value['from'],
        'props': value['props'] == null ? undefined : ((value['props'] as Array<any>).map(HttpRawPropResponseToJSON)),
        'sport': value['sport'],
        'to': value['to'],
    };
}

