/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpManualSettleEventResponse
 */
export interface HttpManualSettleEventResponse {
    /**
     * 
     * @type {string}
     * @memberof HttpManualSettleEventResponse
     */
    event_id?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpManualSettleEventResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the HttpManualSettleEventResponse interface.
 */
export function instanceOfHttpManualSettleEventResponse(value: object): value is HttpManualSettleEventResponse {
    return true;
}

export function HttpManualSettleEventResponseFromJSON(json: any): HttpManualSettleEventResponse {
    return HttpManualSettleEventResponseFromJSONTyped(json, false);
}

export function HttpManualSettleEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpManualSettleEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'] == null ? undefined : json['event_id'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function HttpManualSettleEventResponseToJSON(json: any): HttpManualSettleEventResponse {
    return HttpManualSettleEventResponseToJSONTyped(json, false);
}

export function HttpManualSettleEventResponseToJSONTyped(value?: HttpManualSettleEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'message': value['message'],
    };
}

