/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HttpMarketData } from './HttpMarketData.js';
import {
    HttpMarketDataFromJSON,
    HttpMarketDataFromJSONTyped,
    HttpMarketDataToJSON,
    HttpMarketDataToJSONTyped,
} from './HttpMarketData.js';

/**
 * 
 * @export
 * @interface HttpBookmakerData
 */
export interface HttpBookmakerData {
    /**
     * 
     * @type {string}
     * @memberof HttpBookmakerData
     */
    key?: string;
    /**
     * 
     * @type {Array<HttpMarketData>}
     * @memberof HttpBookmakerData
     */
    markets?: Array<HttpMarketData>;
}

/**
 * Check if a given object implements the HttpBookmakerData interface.
 */
export function instanceOfHttpBookmakerData(value: object): value is HttpBookmakerData {
    return true;
}

export function HttpBookmakerDataFromJSON(json: any): HttpBookmakerData {
    return HttpBookmakerDataFromJSONTyped(json, false);
}

export function HttpBookmakerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpBookmakerData {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'markets': json['markets'] == null ? undefined : ((json['markets'] as Array<any>).map(HttpMarketDataFromJSON)),
    };
}

export function HttpBookmakerDataToJSON(json: any): HttpBookmakerData {
    return HttpBookmakerDataToJSONTyped(json, false);
}

export function HttpBookmakerDataToJSONTyped(value?: HttpBookmakerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'markets': value['markets'] == null ? undefined : ((value['markets'] as Array<any>).map(HttpMarketDataToJSON)),
    };
}

