/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HttpEventDetail } from './HttpEventDetail.js';
import {
    HttpEventDetailFromJSON,
    HttpEventDetailFromJSONTyped,
    HttpEventDetailToJSON,
    HttpEventDetailToJSONTyped,
} from './HttpEventDetail.js';

/**
 * 
 * @export
 * @interface HttpGetMultipleMatchDetailsResponse
 */
export interface HttpGetMultipleMatchDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof HttpGetMultipleMatchDetailsResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<HttpEventDetail>}
     * @memberof HttpGetMultipleMatchDetailsResponse
     */
    matches?: Array<HttpEventDetail>;
    /**
     * 
     * @type {string}
     * @memberof HttpGetMultipleMatchDetailsResponse
     */
    sport?: string;
}

/**
 * Check if a given object implements the HttpGetMultipleMatchDetailsResponse interface.
 */
export function instanceOfHttpGetMultipleMatchDetailsResponse(value: object): value is HttpGetMultipleMatchDetailsResponse {
    return true;
}

export function HttpGetMultipleMatchDetailsResponseFromJSON(json: any): HttpGetMultipleMatchDetailsResponse {
    return HttpGetMultipleMatchDetailsResponseFromJSONTyped(json, false);
}

export function HttpGetMultipleMatchDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpGetMultipleMatchDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'matches': json['matches'] == null ? undefined : ((json['matches'] as Array<any>).map(HttpEventDetailFromJSON)),
        'sport': json['sport'] == null ? undefined : json['sport'],
    };
}

export function HttpGetMultipleMatchDetailsResponseToJSON(json: any): HttpGetMultipleMatchDetailsResponse {
    return HttpGetMultipleMatchDetailsResponseToJSONTyped(json, false);
}

export function HttpGetMultipleMatchDetailsResponseToJSONTyped(value?: HttpGetMultipleMatchDetailsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'matches': value['matches'] == null ? undefined : ((value['matches'] as Array<any>).map(HttpEventDetailToJSON)),
        'sport': value['sport'],
    };
}

