/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainOutcomeType } from './DomainOutcomeType.js';
import {
    DomainOutcomeTypeFromJSON,
    DomainOutcomeTypeFromJSONTyped,
    DomainOutcomeTypeToJSON,
    DomainOutcomeTypeToJSONTyped,
} from './DomainOutcomeType.js';

/**
 * 
 * @export
 * @interface HttpOutcomeDetailRelatedOption
 */
export interface HttpOutcomeDetailRelatedOption {
    /**
     * 
     * @type {number}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    actual_value?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    completed_at?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    name?: string;
    /**
     * 
     * @type {DomainOutcomeType}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    outcome_type?: DomainOutcomeType;
    /**
     * 
     * @type {number}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    point?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    position?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    result?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeDetailRelatedOption
     */
    uuid?: string;
}



/**
 * Check if a given object implements the HttpOutcomeDetailRelatedOption interface.
 */
export function instanceOfHttpOutcomeDetailRelatedOption(value: object): value is HttpOutcomeDetailRelatedOption {
    return true;
}

export function HttpOutcomeDetailRelatedOptionFromJSON(json: any): HttpOutcomeDetailRelatedOption {
    return HttpOutcomeDetailRelatedOptionFromJSONTyped(json, false);
}

export function HttpOutcomeDetailRelatedOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpOutcomeDetailRelatedOption {
    if (json == null) {
        return json;
    }
    return {
        
        'actual_value': json['actual_value'] == null ? undefined : json['actual_value'],
        'completed_at': json['completed_at'] == null ? undefined : json['completed_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'outcome_type': json['outcome_type'] == null ? undefined : DomainOutcomeTypeFromJSON(json['outcome_type']),
        'point': json['point'] == null ? undefined : json['point'],
        'position': json['position'] == null ? undefined : json['position'],
        'price': json['price'] == null ? undefined : json['price'],
        'result': json['result'] == null ? undefined : json['result'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function HttpOutcomeDetailRelatedOptionToJSON(json: any): HttpOutcomeDetailRelatedOption {
    return HttpOutcomeDetailRelatedOptionToJSONTyped(json, false);
}

export function HttpOutcomeDetailRelatedOptionToJSONTyped(value?: HttpOutcomeDetailRelatedOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual_value': value['actual_value'],
        'completed_at': value['completed_at'],
        'description': value['description'],
        'name': value['name'],
        'outcome_type': DomainOutcomeTypeToJSON(value['outcome_type']),
        'point': value['point'],
        'position': value['position'],
        'price': value['price'],
        'result': value['result'],
        'uuid': value['uuid'],
    };
}

