/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpHealthCheckResponse
 */
export interface HttpHealthCheckResponse {
    /**
     * 
     * @type {string}
     * @memberof HttpHealthCheckResponse
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpHealthCheckResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the HttpHealthCheckResponse interface.
 */
export function instanceOfHttpHealthCheckResponse(value: object): value is HttpHealthCheckResponse {
    return true;
}

export function HttpHealthCheckResponseFromJSON(json: any): HttpHealthCheckResponse {
    return HttpHealthCheckResponseFromJSONTyped(json, false);
}

export function HttpHealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpHealthCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HttpHealthCheckResponseToJSON(json: any): HttpHealthCheckResponse {
    return HttpHealthCheckResponseToJSONTyped(json, false);
}

export function HttpHealthCheckResponseToJSONTyped(value?: HttpHealthCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'status': value['status'],
    };
}

