/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpMatchSummary
 */
export interface HttpMatchSummary {
    /**
     * 
     * @type {number}
     * @memberof HttpMatchSummary
     */
    away_score?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    away_team?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpMatchSummary
     */
    away_team_odds?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    commence_time?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpMatchSummary
     */
    home_score?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    home_team?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpMatchSummary
     */
    home_team_odds?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    sport_title?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpMatchSummary
     */
    status?: string;
}

/**
 * Check if a given object implements the HttpMatchSummary interface.
 */
export function instanceOfHttpMatchSummary(value: object): value is HttpMatchSummary {
    return true;
}

export function HttpMatchSummaryFromJSON(json: any): HttpMatchSummary {
    return HttpMatchSummaryFromJSONTyped(json, false);
}

export function HttpMatchSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpMatchSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'away_score': json['away_score'] == null ? undefined : json['away_score'],
        'away_team': json['away_team'] == null ? undefined : json['away_team'],
        'away_team_odds': json['away_team_odds'] == null ? undefined : json['away_team_odds'],
        'commence_time': json['commence_time'] == null ? undefined : json['commence_time'],
        'home_score': json['home_score'] == null ? undefined : json['home_score'],
        'home_team': json['home_team'] == null ? undefined : json['home_team'],
        'home_team_odds': json['home_team_odds'] == null ? undefined : json['home_team_odds'],
        'id': json['id'] == null ? undefined : json['id'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'sport_title': json['sport_title'] == null ? undefined : json['sport_title'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HttpMatchSummaryToJSON(json: any): HttpMatchSummary {
    return HttpMatchSummaryToJSONTyped(json, false);
}

export function HttpMatchSummaryToJSONTyped(value?: HttpMatchSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'away_score': value['away_score'],
        'away_team': value['away_team'],
        'away_team_odds': value['away_team_odds'],
        'commence_time': value['commence_time'],
        'home_score': value['home_score'],
        'home_team': value['home_team'],
        'home_team_odds': value['home_team_odds'],
        'id': value['id'],
        'sport': value['sport'],
        'sport_title': value['sport_title'],
        'status': value['status'],
    };
}

