/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpCollectOddsResponse
 */
export interface HttpCollectOddsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HttpCollectOddsResponse
     */
    force?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpCollectOddsResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCollectOddsResponse
     */
    request_id?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCollectOddsResponse
     */
    sport?: string;
}

/**
 * Check if a given object implements the HttpCollectOddsResponse interface.
 */
export function instanceOfHttpCollectOddsResponse(value: object): value is HttpCollectOddsResponse {
    return true;
}

export function HttpCollectOddsResponseFromJSON(json: any): HttpCollectOddsResponse {
    return HttpCollectOddsResponseFromJSONTyped(json, false);
}

export function HttpCollectOddsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpCollectOddsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'] == null ? undefined : json['force'],
        'message': json['message'] == null ? undefined : json['message'],
        'request_id': json['request_id'] == null ? undefined : json['request_id'],
        'sport': json['sport'] == null ? undefined : json['sport'],
    };
}

export function HttpCollectOddsResponseToJSON(json: any): HttpCollectOddsResponse {
    return HttpCollectOddsResponseToJSONTyped(json, false);
}

export function HttpCollectOddsResponseToJSONTyped(value?: HttpCollectOddsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
        'message': value['message'],
        'request_id': value['request_id'],
        'sport': value['sport'],
    };
}

