/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpManualSettleRequest
 */
export interface HttpManualSettleRequest {
    /**
     * 
     * @type {number}
     * @memberof HttpManualSettleRequest
     */
    away: number;
    /**
     * 
     * @type {number}
     * @memberof HttpManualSettleRequest
     */
    home: number;
}

/**
 * Check if a given object implements the HttpManualSettleRequest interface.
 */
export function instanceOfHttpManualSettleRequest(value: object): value is HttpManualSettleRequest {
    if (!('away' in value) || value['away'] === undefined) return false;
    if (!('home' in value) || value['home'] === undefined) return false;
    return true;
}

export function HttpManualSettleRequestFromJSON(json: any): HttpManualSettleRequest {
    return HttpManualSettleRequestFromJSONTyped(json, false);
}

export function HttpManualSettleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpManualSettleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'away': json['away'],
        'home': json['home'],
    };
}

export function HttpManualSettleRequestToJSON(json: any): HttpManualSettleRequest {
    return HttpManualSettleRequestToJSONTyped(json, false);
}

export function HttpManualSettleRequestToJSONTyped(value?: HttpManualSettleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'away': value['away'],
        'home': value['home'],
    };
}

