/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpEventContext
 */
export interface HttpEventContext {
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    away_team?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    commence_time?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    home_team?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpEventContext
     */
    sport_title?: string;
}

/**
 * Check if a given object implements the HttpEventContext interface.
 */
export function instanceOfHttpEventContext(value: object): value is HttpEventContext {
    return true;
}

export function HttpEventContextFromJSON(json: any): HttpEventContext {
    return HttpEventContextFromJSONTyped(json, false);
}

export function HttpEventContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpEventContext {
    if (json == null) {
        return json;
    }
    return {
        
        'away_team': json['away_team'] == null ? undefined : json['away_team'],
        'commence_time': json['commence_time'] == null ? undefined : json['commence_time'],
        'home_team': json['home_team'] == null ? undefined : json['home_team'],
        'id': json['id'] == null ? undefined : json['id'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'sport_title': json['sport_title'] == null ? undefined : json['sport_title'],
    };
}

export function HttpEventContextToJSON(json: any): HttpEventContext {
    return HttpEventContextToJSONTyped(json, false);
}

export function HttpEventContextToJSONTyped(value?: HttpEventContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'away_team': value['away_team'],
        'commence_time': value['commence_time'],
        'home_team': value['home_team'],
        'id': value['id'],
        'sport': value['sport'],
        'sport_title': value['sport_title'],
    };
}

