/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainOutcomeType } from './DomainOutcomeType.js';
import {
    DomainOutcomeTypeFromJSON,
    DomainOutcomeTypeFromJSONTyped,
    DomainOutcomeTypeToJSON,
    DomainOutcomeTypeToJSONTyped,
} from './DomainOutcomeType.js';

/**
 * 
 * @export
 * @interface HttpOutcomeData
 */
export interface HttpOutcomeData {
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeData
     */
    name?: string;
    /**
     * 
     * @type {DomainOutcomeType}
     * @memberof HttpOutcomeData
     */
    outcome_type?: DomainOutcomeType;
    /**
     * 
     * @type {number}
     * @memberof HttpOutcomeData
     */
    point?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeData
     */
    position?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpOutcomeData
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeData
     */
    result?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpOutcomeData
     */
    uuid?: string;
}



/**
 * Check if a given object implements the HttpOutcomeData interface.
 */
export function instanceOfHttpOutcomeData(value: object): value is HttpOutcomeData {
    return true;
}

export function HttpOutcomeDataFromJSON(json: any): HttpOutcomeData {
    return HttpOutcomeDataFromJSONTyped(json, false);
}

export function HttpOutcomeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpOutcomeData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'outcome_type': json['outcome_type'] == null ? undefined : DomainOutcomeTypeFromJSON(json['outcome_type']),
        'point': json['point'] == null ? undefined : json['point'],
        'position': json['position'] == null ? undefined : json['position'],
        'price': json['price'] == null ? undefined : json['price'],
        'result': json['result'] == null ? undefined : json['result'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function HttpOutcomeDataToJSON(json: any): HttpOutcomeData {
    return HttpOutcomeDataToJSONTyped(json, false);
}

export function HttpOutcomeDataToJSONTyped(value?: HttpOutcomeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'outcome_type': DomainOutcomeTypeToJSON(value['outcome_type']),
        'point': value['point'],
        'position': value['position'],
        'price': value['price'],
        'result': value['result'],
        'uuid': value['uuid'],
    };
}

