/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HttpMatchSummary } from './HttpMatchSummary.js';
import {
    HttpMatchSummaryFromJSON,
    HttpMatchSummaryFromJSONTyped,
    HttpMatchSummaryToJSON,
    HttpMatchSummaryToJSONTyped,
} from './HttpMatchSummary.js';

/**
 * 
 * @export
 * @interface HttpGetMatchesResponse
 */
export interface HttpGetMatchesResponse {
    /**
     * 
     * @type {number}
     * @memberof HttpGetMatchesResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpGetMatchesResponse
     */
    from?: string;
    /**
     * 
     * @type {Array<HttpMatchSummary>}
     * @memberof HttpGetMatchesResponse
     */
    matches?: Array<HttpMatchSummary>;
    /**
     * 
     * @type {string}
     * @memberof HttpGetMatchesResponse
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpGetMatchesResponse
     */
    to?: string;
}

/**
 * Check if a given object implements the HttpGetMatchesResponse interface.
 */
export function instanceOfHttpGetMatchesResponse(value: object): value is HttpGetMatchesResponse {
    return true;
}

export function HttpGetMatchesResponseFromJSON(json: any): HttpGetMatchesResponse {
    return HttpGetMatchesResponseFromJSONTyped(json, false);
}

export function HttpGetMatchesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpGetMatchesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'from': json['from'] == null ? undefined : json['from'],
        'matches': json['matches'] == null ? undefined : ((json['matches'] as Array<any>).map(HttpMatchSummaryFromJSON)),
        'sport': json['sport'] == null ? undefined : json['sport'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function HttpGetMatchesResponseToJSON(json: any): HttpGetMatchesResponse {
    return HttpGetMatchesResponseToJSONTyped(json, false);
}

export function HttpGetMatchesResponseToJSONTyped(value?: HttpGetMatchesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'from': value['from'],
        'matches': value['matches'] == null ? undefined : ((value['matches'] as Array<any>).map(HttpMatchSummaryToJSON)),
        'sport': value['sport'],
        'to': value['to'],
    };
}

