/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpErrorResponse
 */
export interface HttpErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof HttpErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HttpErrorResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the HttpErrorResponse interface.
 */
export function instanceOfHttpErrorResponse(value: object): value is HttpErrorResponse {
    return true;
}

export function HttpErrorResponseFromJSON(json: any): HttpErrorResponse {
    return HttpErrorResponseFromJSONTyped(json, false);
}

export function HttpErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function HttpErrorResponseToJSON(json: any): HttpErrorResponse {
    return HttpErrorResponseToJSONTyped(json, false);
}

export function HttpErrorResponseToJSONTyped(value?: HttpErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
    };
}

