/* tslint:disable */
/* eslint-disable */
/**
 * Goracle API
 * Sports data and odds collection microservice. Goracle is the single source of truth for sports events, betting odds, and outcome results.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HttpCollectAllOddsResponse
 */
export interface HttpCollectAllOddsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HttpCollectAllOddsResponse
     */
    force?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpCollectAllOddsResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCollectAllOddsResponse
     */
    request_id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpCollectAllOddsResponse
     */
    sports?: Array<string>;
}

/**
 * Check if a given object implements the HttpCollectAllOddsResponse interface.
 */
export function instanceOfHttpCollectAllOddsResponse(value: object): value is HttpCollectAllOddsResponse {
    return true;
}

export function HttpCollectAllOddsResponseFromJSON(json: any): HttpCollectAllOddsResponse {
    return HttpCollectAllOddsResponseFromJSONTyped(json, false);
}

export function HttpCollectAllOddsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpCollectAllOddsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'] == null ? undefined : json['force'],
        'message': json['message'] == null ? undefined : json['message'],
        'request_id': json['request_id'] == null ? undefined : json['request_id'],
        'sports': json['sports'] == null ? undefined : json['sports'],
    };
}

export function HttpCollectAllOddsResponseToJSON(json: any): HttpCollectAllOddsResponse {
    return HttpCollectAllOddsResponseToJSONTyped(json, false);
}

export function HttpCollectAllOddsResponseToJSONTyped(value?: HttpCollectAllOddsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
        'message': value['message'],
        'request_id': value['request_id'],
        'sports': value['sports'],
    };
}

